// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: customer.proto

package customer

import (
	"context"

	"erp/app/customer/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCustomerCategoryReq                = pb.AddCustomerCategoryReq
	AddCustomerCategoryResp               = pb.AddCustomerCategoryResp
	AddCustomerReq                        = pb.AddCustomerReq
	AddCustomerResp                       = pb.AddCustomerResp
	AddCustomerSatisfactionSurveyReq      = pb.AddCustomerSatisfactionSurveyReq
	AddCustomerSatisfactionSurveyResp     = pb.AddCustomerSatisfactionSurveyResp
	Customer                              = pb.Customer
	CustomerCategory                      = pb.CustomerCategory
	CustomerSatisfactionSurvey            = pb.CustomerSatisfactionSurvey
	DelCustomerCategoryReq                = pb.DelCustomerCategoryReq
	DelCustomerCategoryResp               = pb.DelCustomerCategoryResp
	GetCustomerByCodeReq                  = pb.GetCustomerByCodeReq
	GetCustomerByCodeResp                 = pb.GetCustomerByCodeResp
	GetCustomerByIdReq                    = pb.GetCustomerByIdReq
	GetCustomerByIdResp                   = pb.GetCustomerByIdResp
	GetCustomerCategoryByIdReq            = pb.GetCustomerCategoryByIdReq
	GetCustomerCategoryByIdResp           = pb.GetCustomerCategoryByIdResp
	GetCustomerSatisfactionSurveyByIdReq  = pb.GetCustomerSatisfactionSurveyByIdReq
	GetCustomerSatisfactionSurveyByIdResp = pb.GetCustomerSatisfactionSurveyByIdResp
	SearchCustomerCategoryReq             = pb.SearchCustomerCategoryReq
	SearchCustomerCategoryResp            = pb.SearchCustomerCategoryResp
	SearchCustomerReq                     = pb.SearchCustomerReq
	SearchCustomerResp                    = pb.SearchCustomerResp
	SearchCustomerSatisfactionSurveyReq   = pb.SearchCustomerSatisfactionSurveyReq
	SearchCustomerSatisfactionSurveyResp  = pb.SearchCustomerSatisfactionSurveyResp
	UpdateCustomerCategoryReq             = pb.UpdateCustomerCategoryReq
	UpdateCustomerCategoryResp            = pb.UpdateCustomerCategoryResp
	UpdateCustomerReq                     = pb.UpdateCustomerReq
	UpdateCustomerResp                    = pb.UpdateCustomerResp

	CustomerZrpcClient interface {
		// -----------------------customer-----------------------
		AddCustomer(ctx context.Context, in *AddCustomerReq, opts ...grpc.CallOption) (*AddCustomerResp, error)
		UpdateCustomer(ctx context.Context, in *UpdateCustomerReq, opts ...grpc.CallOption) (*UpdateCustomerResp, error)
		// rpc DelCustomer(DelCustomerReq) returns (DelCustomerResp);
		GetCustomerById(ctx context.Context, in *GetCustomerByIdReq, opts ...grpc.CallOption) (*GetCustomerByIdResp, error)
		GetCustomerByCode(ctx context.Context, in *GetCustomerByCodeReq, opts ...grpc.CallOption) (*GetCustomerByCodeResp, error)
		SearchCustomer(ctx context.Context, in *SearchCustomerReq, opts ...grpc.CallOption) (*SearchCustomerResp, error)
		// -----------------------customerCategory-----------------------
		AddCustomerCategory(ctx context.Context, in *AddCustomerCategoryReq, opts ...grpc.CallOption) (*AddCustomerCategoryResp, error)
		UpdateCustomerCategory(ctx context.Context, in *UpdateCustomerCategoryReq, opts ...grpc.CallOption) (*UpdateCustomerCategoryResp, error)
		DelCustomerCategory(ctx context.Context, in *DelCustomerCategoryReq, opts ...grpc.CallOption) (*DelCustomerCategoryResp, error)
		GetCustomerCategoryById(ctx context.Context, in *GetCustomerCategoryByIdReq, opts ...grpc.CallOption) (*GetCustomerCategoryByIdResp, error)
		SearchCustomerCategory(ctx context.Context, in *SearchCustomerCategoryReq, opts ...grpc.CallOption) (*SearchCustomerCategoryResp, error)
		// -----------------------customerSatisfactionSurvey-----------------------
		AddCustomerSatisfactionSurvey(ctx context.Context, in *AddCustomerSatisfactionSurveyReq, opts ...grpc.CallOption) (*AddCustomerSatisfactionSurveyResp, error)
		// rpc UpdateCustomerSatisfactionSurvey(UpdateCustomerSatisfactionSurveyReq) returns (UpdateCustomerSatisfactionSurveyResp);
		GetCustomerSatisfactionSurveyById(ctx context.Context, in *GetCustomerSatisfactionSurveyByIdReq, opts ...grpc.CallOption) (*GetCustomerSatisfactionSurveyByIdResp, error)
		SearchCustomerSatisfactionSurvey(ctx context.Context, in *SearchCustomerSatisfactionSurveyReq, opts ...grpc.CallOption) (*SearchCustomerSatisfactionSurveyResp, error)
	}

	defaultCustomerZrpcClient struct {
		cli zrpc.Client
	}
)

func NewCustomerZrpcClient(cli zrpc.Client) CustomerZrpcClient {
	return &defaultCustomerZrpcClient{
		cli: cli,
	}
}

// -----------------------customer-----------------------
func (m *defaultCustomerZrpcClient) AddCustomer(ctx context.Context, in *AddCustomerReq, opts ...grpc.CallOption) (*AddCustomerResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.AddCustomer(ctx, in, opts...)
}

func (m *defaultCustomerZrpcClient) UpdateCustomer(ctx context.Context, in *UpdateCustomerReq, opts ...grpc.CallOption) (*UpdateCustomerResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.UpdateCustomer(ctx, in, opts...)
}

// rpc DelCustomer(DelCustomerReq) returns (DelCustomerResp);
func (m *defaultCustomerZrpcClient) GetCustomerById(ctx context.Context, in *GetCustomerByIdReq, opts ...grpc.CallOption) (*GetCustomerByIdResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.GetCustomerById(ctx, in, opts...)
}

func (m *defaultCustomerZrpcClient) GetCustomerByCode(ctx context.Context, in *GetCustomerByCodeReq, opts ...grpc.CallOption) (*GetCustomerByCodeResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.GetCustomerByCode(ctx, in, opts...)
}

func (m *defaultCustomerZrpcClient) SearchCustomer(ctx context.Context, in *SearchCustomerReq, opts ...grpc.CallOption) (*SearchCustomerResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.SearchCustomer(ctx, in, opts...)
}

// -----------------------customerCategory-----------------------
func (m *defaultCustomerZrpcClient) AddCustomerCategory(ctx context.Context, in *AddCustomerCategoryReq, opts ...grpc.CallOption) (*AddCustomerCategoryResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.AddCustomerCategory(ctx, in, opts...)
}

func (m *defaultCustomerZrpcClient) UpdateCustomerCategory(ctx context.Context, in *UpdateCustomerCategoryReq, opts ...grpc.CallOption) (*UpdateCustomerCategoryResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.UpdateCustomerCategory(ctx, in, opts...)
}

func (m *defaultCustomerZrpcClient) DelCustomerCategory(ctx context.Context, in *DelCustomerCategoryReq, opts ...grpc.CallOption) (*DelCustomerCategoryResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.DelCustomerCategory(ctx, in, opts...)
}

func (m *defaultCustomerZrpcClient) GetCustomerCategoryById(ctx context.Context, in *GetCustomerCategoryByIdReq, opts ...grpc.CallOption) (*GetCustomerCategoryByIdResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.GetCustomerCategoryById(ctx, in, opts...)
}

func (m *defaultCustomerZrpcClient) SearchCustomerCategory(ctx context.Context, in *SearchCustomerCategoryReq, opts ...grpc.CallOption) (*SearchCustomerCategoryResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.SearchCustomerCategory(ctx, in, opts...)
}

// -----------------------customerSatisfactionSurvey-----------------------
func (m *defaultCustomerZrpcClient) AddCustomerSatisfactionSurvey(ctx context.Context, in *AddCustomerSatisfactionSurveyReq, opts ...grpc.CallOption) (*AddCustomerSatisfactionSurveyResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.AddCustomerSatisfactionSurvey(ctx, in, opts...)
}

// rpc UpdateCustomerSatisfactionSurvey(UpdateCustomerSatisfactionSurveyReq) returns (UpdateCustomerSatisfactionSurveyResp);
func (m *defaultCustomerZrpcClient) GetCustomerSatisfactionSurveyById(ctx context.Context, in *GetCustomerSatisfactionSurveyByIdReq, opts ...grpc.CallOption) (*GetCustomerSatisfactionSurveyByIdResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.GetCustomerSatisfactionSurveyById(ctx, in, opts...)
}

func (m *defaultCustomerZrpcClient) SearchCustomerSatisfactionSurvey(ctx context.Context, in *SearchCustomerSatisfactionSurveyReq, opts ...grpc.CallOption) (*SearchCustomerSatisfactionSurveyResp, error) {
	client := pb.NewCustomerClient(m.cli.Conn())
	return client.SearchCustomerSatisfactionSurvey(ctx, in, opts...)
}
