// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: product.proto

package productbatch

import (
	"context"

	"erp/app/product/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddProductBatchReq         = pb.AddProductBatchReq
	AddProductBatchResp        = pb.AddProductBatchResp
	AddProductCategoryReq      = pb.AddProductCategoryReq
	AddProductCategoryResp     = pb.AddProductCategoryResp
	AddProductReq              = pb.AddProductReq
	AddProductResp             = pb.AddProductResp
	DelProductCategoryReq      = pb.DelProductCategoryReq
	DelProductCategoryResp     = pb.DelProductCategoryResp
	GetProductBatchByIdReq     = pb.GetProductBatchByIdReq
	GetProductBatchByIdResp    = pb.GetProductBatchByIdResp
	GetProductByIdReq          = pb.GetProductByIdReq
	GetProductByIdResp         = pb.GetProductByIdResp
	GetProductByNoReq          = pb.GetProductByNoReq
	GetProductByNoResp         = pb.GetProductByNoResp
	GetProductCategoryByIdReq  = pb.GetProductCategoryByIdReq
	GetProductCategoryByIdResp = pb.GetProductCategoryByIdResp
	Product                    = pb.Product
	ProductBatch               = pb.ProductBatch
	ProductCategory            = pb.ProductCategory
	SearchProductBatchReq      = pb.SearchProductBatchReq
	SearchProductBatchResp     = pb.SearchProductBatchResp
	SearchProductCategoryReq   = pb.SearchProductCategoryReq
	SearchProductCategoryResp  = pb.SearchProductCategoryResp
	SearchProductReq           = pb.SearchProductReq
	SearchProductResp          = pb.SearchProductResp
	UpdateProductCategoryReq   = pb.UpdateProductCategoryReq
	UpdateProductCategoryResp  = pb.UpdateProductCategoryResp
	UpdateProductReq           = pb.UpdateProductReq
	UpdateProductResp          = pb.UpdateProductResp

	ProductBatchZrpcClient interface {
		AddProductBatch(ctx context.Context, in *AddProductBatchReq, opts ...grpc.CallOption) (*AddProductBatchResp, error)
		GetProductBatchById(ctx context.Context, in *GetProductBatchByIdReq, opts ...grpc.CallOption) (*GetProductBatchByIdResp, error)
		SearchProductBatch(ctx context.Context, in *SearchProductBatchReq, opts ...grpc.CallOption) (*SearchProductBatchResp, error)
	}

	defaultProductBatchZrpcClient struct {
		cli zrpc.Client
	}
)

func NewProductBatchZrpcClient(cli zrpc.Client) ProductBatchZrpcClient {
	return &defaultProductBatchZrpcClient{
		cli: cli,
	}
}

func (m *defaultProductBatchZrpcClient) AddProductBatch(ctx context.Context, in *AddProductBatchReq, opts ...grpc.CallOption) (*AddProductBatchResp, error) {
	client := pb.NewProductBatchClient(m.cli.Conn())
	return client.AddProductBatch(ctx, in, opts...)
}

func (m *defaultProductBatchZrpcClient) GetProductBatchById(ctx context.Context, in *GetProductBatchByIdReq, opts ...grpc.CallOption) (*GetProductBatchByIdResp, error) {
	client := pb.NewProductBatchClient(m.cli.Conn())
	return client.GetProductBatchById(ctx, in, opts...)
}

func (m *defaultProductBatchZrpcClient) SearchProductBatch(ctx context.Context, in *SearchProductBatchReq, opts ...grpc.CallOption) (*SearchProductBatchResp, error) {
	client := pb.NewProductBatchClient(m.cli.Conn())
	return client.SearchProductBatch(ctx, in, opts...)
}
