// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: purchase.proto

package purchaseorder

import (
	"context"

	"erp/app/purchase/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApproveRequisitionReq            = pb.ApproveRequisitionReq
	ApproveRequisitionResp           = pb.ApproveRequisitionResp
	CancelPurchaseOrderReq           = pb.CancelPurchaseOrderReq
	CancelPurchaseOrderResp          = pb.CancelPurchaseOrderResp
	CreateOrderFromRequisitionReq    = pb.CreateOrderFromRequisitionReq
	CreateOrderFromRequisitionResp   = pb.CreateOrderFromRequisitionResp
	CreateOrderWithDetailsReq        = pb.CreateOrderWithDetailsReq
	CreateOrderWithDetailsResp       = pb.CreateOrderWithDetailsResp
	CreateReceiptFromOrderReq        = pb.CreateReceiptFromOrderReq
	CreateReceiptFromOrderResp       = pb.CreateReceiptFromOrderResp
	CreateReceiptWithDetailsReq      = pb.CreateReceiptWithDetailsReq
	CreateReceiptWithDetailsResp     = pb.CreateReceiptWithDetailsResp
	CreateRequisitionWithDetailsReq  = pb.CreateRequisitionWithDetailsReq
	CreateRequisitionWithDetailsResp = pb.CreateRequisitionWithDetailsResp
	GetOrderWithDetailsReq           = pb.GetOrderWithDetailsReq
	GetOrderWithDetailsResp          = pb.GetOrderWithDetailsResp
	GetReceiptWithDetailsReq         = pb.GetReceiptWithDetailsReq
	GetReceiptWithDetailsResp        = pb.GetReceiptWithDetailsResp
	GetRequisitionWithDetailsReq     = pb.GetRequisitionWithDetailsReq
	GetRequisitionWithDetailsResp    = pb.GetRequisitionWithDetailsResp
	OrderDetailInput                 = pb.OrderDetailInput
	PurchaseOrder                    = pb.PurchaseOrder
	PurchaseOrderDetail              = pb.PurchaseOrderDetail
	PurchaseOrderWithDetails         = pb.PurchaseOrderWithDetails
	PurchaseReceipt                  = pb.PurchaseReceipt
	PurchaseReceiptDetail            = pb.PurchaseReceiptDetail
	PurchaseReceiptWithDetails       = pb.PurchaseReceiptWithDetails
	PurchaseRequisition              = pb.PurchaseRequisition
	PurchaseRequisitionDetail        = pb.PurchaseRequisitionDetail
	PurchaseRequisitionWithDetails   = pb.PurchaseRequisitionWithDetails
	ReceiptDetailInput               = pb.ReceiptDetailInput
	RequisitionDetailInput           = pb.RequisitionDetailInput
	SearchOrderReq                   = pb.SearchOrderReq
	SearchOrderResp                  = pb.SearchOrderResp
	SearchReceiptReq                 = pb.SearchReceiptReq
	SearchReceiptResp                = pb.SearchReceiptResp
	SearchRequisitionReq             = pb.SearchRequisitionReq
	SearchRequisitionResp            = pb.SearchRequisitionResp
	UpdateOrderDetailReq             = pb.UpdateOrderDetailReq
	UpdateOrderDetailResp            = pb.UpdateOrderDetailResp
	UpdateOrderReq                   = pb.UpdateOrderReq
	UpdateOrderResp                  = pb.UpdateOrderResp
	UpdateReceiptDetailReq           = pb.UpdateReceiptDetailReq
	UpdateReceiptDetailResp          = pb.UpdateReceiptDetailResp
	UpdateReceiptReq                 = pb.UpdateReceiptReq
	UpdateReceiptResp                = pb.UpdateReceiptResp
	UpdateRequisitionDetailReq       = pb.UpdateRequisitionDetailReq
	UpdateRequisitionDetailResp      = pb.UpdateRequisitionDetailResp
	UpdateRequisitionReq             = pb.UpdateRequisitionReq
	UpdateRequisitionResp            = pb.UpdateRequisitionResp

	PurchaseOrderZrpcClient interface {
		// 从采购申请创建采购订单（通过 requisition_id 获取申请明细数据，保证一致性）
		CreateOrderFromRequisition(ctx context.Context, in *CreateOrderFromRequisitionReq, opts ...grpc.CallOption) (*CreateOrderFromRequisitionResp, error)
		// 直接创建采购订单及明细（事务）
		CreateOrderWithDetails(ctx context.Context, in *CreateOrderWithDetailsReq, opts ...grpc.CallOption) (*CreateOrderWithDetailsResp, error)
		// 取消采购订单
		CancelPurchaseOrder(ctx context.Context, in *CancelPurchaseOrderReq, opts ...grpc.CallOption) (*CancelPurchaseOrderResp, error)
		// 获取采购订单及明细
		GetOrderWithDetails(ctx context.Context, in *GetOrderWithDetailsReq, opts ...grpc.CallOption) (*GetOrderWithDetailsResp, error)
		// 查询采购订单
		SearchOrder(ctx context.Context, in *SearchOrderReq, opts ...grpc.CallOption) (*SearchOrderResp, error)
		// 更新采购订单（动态SQL拼接）
		UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...grpc.CallOption) (*UpdateOrderResp, error)
		// 更新采购订单明细（动态SQL拼接）
		UpdateOrderDetail(ctx context.Context, in *UpdateOrderDetailReq, opts ...grpc.CallOption) (*UpdateOrderDetailResp, error)
	}

	defaultPurchaseOrderZrpcClient struct {
		cli zrpc.Client
	}
)

func NewPurchaseOrderZrpcClient(cli zrpc.Client) PurchaseOrderZrpcClient {
	return &defaultPurchaseOrderZrpcClient{
		cli: cli,
	}
}

// 从采购申请创建采购订单（通过 requisition_id 获取申请明细数据，保证一致性）
func (m *defaultPurchaseOrderZrpcClient) CreateOrderFromRequisition(ctx context.Context, in *CreateOrderFromRequisitionReq, opts ...grpc.CallOption) (*CreateOrderFromRequisitionResp, error) {
	client := pb.NewPurchaseOrderClient(m.cli.Conn())
	return client.CreateOrderFromRequisition(ctx, in, opts...)
}

// 直接创建采购订单及明细（事务）
func (m *defaultPurchaseOrderZrpcClient) CreateOrderWithDetails(ctx context.Context, in *CreateOrderWithDetailsReq, opts ...grpc.CallOption) (*CreateOrderWithDetailsResp, error) {
	client := pb.NewPurchaseOrderClient(m.cli.Conn())
	return client.CreateOrderWithDetails(ctx, in, opts...)
}

// 取消采购订单
func (m *defaultPurchaseOrderZrpcClient) CancelPurchaseOrder(ctx context.Context, in *CancelPurchaseOrderReq, opts ...grpc.CallOption) (*CancelPurchaseOrderResp, error) {
	client := pb.NewPurchaseOrderClient(m.cli.Conn())
	return client.CancelPurchaseOrder(ctx, in, opts...)
}

// 获取采购订单及明细
func (m *defaultPurchaseOrderZrpcClient) GetOrderWithDetails(ctx context.Context, in *GetOrderWithDetailsReq, opts ...grpc.CallOption) (*GetOrderWithDetailsResp, error) {
	client := pb.NewPurchaseOrderClient(m.cli.Conn())
	return client.GetOrderWithDetails(ctx, in, opts...)
}

// 查询采购订单
func (m *defaultPurchaseOrderZrpcClient) SearchOrder(ctx context.Context, in *SearchOrderReq, opts ...grpc.CallOption) (*SearchOrderResp, error) {
	client := pb.NewPurchaseOrderClient(m.cli.Conn())
	return client.SearchOrder(ctx, in, opts...)
}

// 更新采购订单（动态SQL拼接）
func (m *defaultPurchaseOrderZrpcClient) UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...grpc.CallOption) (*UpdateOrderResp, error) {
	client := pb.NewPurchaseOrderClient(m.cli.Conn())
	return client.UpdateOrder(ctx, in, opts...)
}

// 更新采购订单明细（动态SQL拼接）
func (m *defaultPurchaseOrderZrpcClient) UpdateOrderDetail(ctx context.Context, in *UpdateOrderDetailReq, opts ...grpc.CallOption) (*UpdateOrderDetailResp, error) {
	client := pb.NewPurchaseOrderClient(m.cli.Conn())
	return client.UpdateOrderDetail(ctx, in, opts...)
}
