// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: hr.proto

package server

import (
	"context"

	"erp/app/hr/rpc/internal/logic/resignedapplication"
	"erp/app/hr/rpc/internal/svc"
	"erp/app/hr/rpc/pb"
)

type ResignedApplicationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedResignedApplicationServer
}

func NewResignedApplicationServer(svcCtx *svc.ServiceContext) *ResignedApplicationServer {
	return &ResignedApplicationServer{
		svcCtx: svcCtx,
	}
}

// -----------------------离职申请表-----------------------
func (s *ResignedApplicationServer) AddResignedApplication(ctx context.Context, in *pb.AddResignedApplicationReq) (*pb.AddResignedApplicationResp, error) {
	l := resignedapplicationlogic.NewAddResignedApplicationLogic(ctx, s.svcCtx)
	return l.AddResignedApplication(in)
}

func (s *ResignedApplicationServer) UpdateResignedApplication(ctx context.Context, in *pb.UpdateResignedApplicationReq) (*pb.UpdateResignedApplicationResp, error) {
	l := resignedapplicationlogic.NewUpdateResignedApplicationLogic(ctx, s.svcCtx)
	return l.UpdateResignedApplication(in)
}

func (s *ResignedApplicationServer) GetResignedApplicationById(ctx context.Context, in *pb.GetResignedApplicationByIdReq) (*pb.GetResignedApplicationByIdResp, error) {
	l := resignedapplicationlogic.NewGetResignedApplicationByIdLogic(ctx, s.svcCtx)
	return l.GetResignedApplicationById(in)
}

func (s *ResignedApplicationServer) SearchResignedApplication(ctx context.Context, in *pb.SearchResignedApplicationReq) (*pb.SearchResignedApplicationResp, error) {
	l := resignedapplicationlogic.NewSearchResignedApplicationLogic(ctx, s.svcCtx)
	return l.SearchResignedApplication(in)
}
