// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	salaryPaymentFieldNames          = builder.RawFieldNames(&SalaryPayment{})
	salaryPaymentRows                = strings.Join(salaryPaymentFieldNames, ",")
	salaryPaymentRowsExpectAutoSet   = strings.Join(stringx.Remove(salaryPaymentFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	salaryPaymentRowsWithPlaceHolder = strings.Join(stringx.Remove(salaryPaymentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpFinanceSalaryPaymentIdPrefix = "cache:erpFinance:salaryPayment:id:"
)

type (
	salaryPaymentModel interface {
		Insert(ctx context.Context, data *SalaryPayment) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SalaryPayment, error)
		Update(ctx context.Context, data *SalaryPayment) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSalaryPaymentModel struct {
		sqlc.CachedConn
		table string
	}

	SalaryPayment struct {
		Id            int64           `db:"id"`             // 主键ID，雪花
		PayrollId     sql.NullInt64   `db:"payroll_id"`     // 关联payroll_record.id
		EmployeeId    int64           `db:"employee_id"`    // 员工ID
		EmployeeName  string          `db:"employee_name"`  // 员工姓名
		DepartmentId  sql.NullInt64   `db:"department_id"`  // 部门ID
		PaymentMonth  time.Time       `db:"payment_month"`  // 工资月份（如 2024-06-01 表示 6 月工资）
		BaseSalary    sql.NullFloat64 `db:"base_salary"`    // 基本工资
		Bonus         float64         `db:"bonus"`          // 奖金
		OvertimePay   float64         `db:"overtime_pay"`   // 加班费
		Deduction     float64         `db:"deduction"`      // 扣款（如社保、个税）
		NetPayment    float64         `db:"net_payment"`    // 实发工资（最终打款金额）
		PaymentDate   time.Time       `db:"payment_date"`   // 实际付款日期
		PaymentMethod sql.NullString  `db:"payment_method"` // 付款方式（如银行转账）
		BankAccount   sql.NullString  `db:"bank_account"`   // 收款银行账号（可选）
		ReferenceNo   sql.NullString  `db:"reference_no"`   // 银行流水号 / 付款单号
		Status        int64           `db:"status"`         // 状态：1-待支付，2-已支付，3-已撤销
		CreatedAt     time.Time       `db:"created_at"`     // 创建时间
		UpdatedAt     time.Time       `db:"updated_at"`     // 更新时间
	}
)

func newSalaryPaymentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSalaryPaymentModel {
	return &defaultSalaryPaymentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`salary_payment`",
	}
}

func (m *defaultSalaryPaymentModel) Delete(ctx context.Context, id int64) error {
	erpFinanceSalaryPaymentIdKey := fmt.Sprintf("%s%v", cacheErpFinanceSalaryPaymentIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpFinanceSalaryPaymentIdKey)
	return err
}

func (m *defaultSalaryPaymentModel) FindOne(ctx context.Context, id int64) (*SalaryPayment, error) {
	erpFinanceSalaryPaymentIdKey := fmt.Sprintf("%s%v", cacheErpFinanceSalaryPaymentIdPrefix, id)
	var resp SalaryPayment
	err := m.QueryRowCtx(ctx, &resp, erpFinanceSalaryPaymentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", salaryPaymentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSalaryPaymentModel) Insert(ctx context.Context, data *SalaryPayment) (sql.Result, error) {
	erpFinanceSalaryPaymentIdKey := fmt.Sprintf("%s%v", cacheErpFinanceSalaryPaymentIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, salaryPaymentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.PayrollId, data.EmployeeId, data.EmployeeName, data.DepartmentId, data.PaymentMonth, data.BaseSalary, data.Bonus, data.OvertimePay, data.Deduction, data.NetPayment, data.PaymentDate, data.PaymentMethod, data.BankAccount, data.ReferenceNo, data.Status)
	}, erpFinanceSalaryPaymentIdKey)
	return ret, err
}

func (m *defaultSalaryPaymentModel) Update(ctx context.Context, data *SalaryPayment) error {
	erpFinanceSalaryPaymentIdKey := fmt.Sprintf("%s%v", cacheErpFinanceSalaryPaymentIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, salaryPaymentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PayrollId, data.EmployeeId, data.EmployeeName, data.DepartmentId, data.PaymentMonth, data.BaseSalary, data.Bonus, data.OvertimePay, data.Deduction, data.NetPayment, data.PaymentDate, data.PaymentMethod, data.BankAccount, data.ReferenceNo, data.Status, data.Id)
	}, erpFinanceSalaryPaymentIdKey)
	return err
}

func (m *defaultSalaryPaymentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpFinanceSalaryPaymentIdPrefix, primary)
}

func (m *defaultSalaryPaymentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", salaryPaymentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSalaryPaymentModel) tableName() string {
	return m.table
}
