Name: product-api
Host: 0.0.0.0
Port: 8004


Etcd:
  Key: rpcServer
  Hosts:
    - "127.0.0.1:2379"

Auth:
  AccessSecret: qsHUADZu9izXb8-rRl8SeSuZBYdoO
  # 20分钟
  #  AccessExpire: 1200
  AccessExpire: 604800
AuthRPC:
  Etcd:
    Key: auth.rpc
  NonBlock: true
ProductRPC:
  Etcd:
    Key: product.rpc
  NonBlock: true
InventoryRPC:
  Etcd:
    Key: inventory.rpc
  NonBlock: true

BizRedis:
  Host: 127.0.0.1:6379
  Pass:
  Type: node
HrRPC:
  Etcd:
    Key: hr.rpc
  NonBlock: true