// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: supplier.proto

package supplier

import (
	"context"

	"erp/app/supplier/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddSupplierEvaluationReq      = pb.AddSupplierEvaluationReq
	AddSupplierEvaluationResp     = pb.AddSupplierEvaluationResp
	AddSupplierReq                = pb.AddSupplierReq
	AddSupplierResp               = pb.AddSupplierResp
	GetSupplierByIdReq            = pb.GetSupplierByIdReq
	GetSupplierByIdResp           = pb.GetSupplierByIdResp
	GetSupplierEvaluationByIdReq  = pb.GetSupplierEvaluationByIdReq
	GetSupplierEvaluationByIdResp = pb.GetSupplierEvaluationByIdResp
	SearchSupplierEvaluationReq   = pb.SearchSupplierEvaluationReq
	SearchSupplierEvaluationResp  = pb.SearchSupplierEvaluationResp
	SearchSupplierReq             = pb.SearchSupplierReq
	SearchSupplierResp            = pb.SearchSupplierResp
	Supplier                      = pb.Supplier
	SupplierEvaluation            = pb.SupplierEvaluation
	UpdateSupplierReq             = pb.UpdateSupplierReq
	UpdateSupplierResp            = pb.UpdateSupplierResp

	SupplierZrpcClient interface {
		// -----------------------supplier-----------------------
		AddSupplier(ctx context.Context, in *AddSupplierReq, opts ...grpc.CallOption) (*AddSupplierResp, error)
		UpdateSupplier(ctx context.Context, in *UpdateSupplierReq, opts ...grpc.CallOption) (*UpdateSupplierResp, error)
		// rpc DelSupplier(DelSupplierReq) returns (DelSupplierResp);
		GetSupplierById(ctx context.Context, in *GetSupplierByIdReq, opts ...grpc.CallOption) (*GetSupplierByIdResp, error)
		SearchSupplier(ctx context.Context, in *SearchSupplierReq, opts ...grpc.CallOption) (*SearchSupplierResp, error)
		// -----------------------supplierEvaluation-----------------------
		AddSupplierEvaluation(ctx context.Context, in *AddSupplierEvaluationReq, opts ...grpc.CallOption) (*AddSupplierEvaluationResp, error)
		// rpc UpdateSupplierEvaluation(UpdateSupplierEvaluationReq) returns (UpdateSupplierEvaluationResp);
		GetSupplierEvaluationById(ctx context.Context, in *GetSupplierEvaluationByIdReq, opts ...grpc.CallOption) (*GetSupplierEvaluationByIdResp, error)
		SearchSupplierEvaluation(ctx context.Context, in *SearchSupplierEvaluationReq, opts ...grpc.CallOption) (*SearchSupplierEvaluationResp, error)
	}

	defaultSupplierZrpcClient struct {
		cli zrpc.Client
	}
)

func NewSupplierZrpcClient(cli zrpc.Client) SupplierZrpcClient {
	return &defaultSupplierZrpcClient{
		cli: cli,
	}
}

// -----------------------supplier-----------------------
func (m *defaultSupplierZrpcClient) AddSupplier(ctx context.Context, in *AddSupplierReq, opts ...grpc.CallOption) (*AddSupplierResp, error) {
	client := pb.NewSupplierClient(m.cli.Conn())
	return client.AddSupplier(ctx, in, opts...)
}

func (m *defaultSupplierZrpcClient) UpdateSupplier(ctx context.Context, in *UpdateSupplierReq, opts ...grpc.CallOption) (*UpdateSupplierResp, error) {
	client := pb.NewSupplierClient(m.cli.Conn())
	return client.UpdateSupplier(ctx, in, opts...)
}

// rpc DelSupplier(DelSupplierReq) returns (DelSupplierResp);
func (m *defaultSupplierZrpcClient) GetSupplierById(ctx context.Context, in *GetSupplierByIdReq, opts ...grpc.CallOption) (*GetSupplierByIdResp, error) {
	client := pb.NewSupplierClient(m.cli.Conn())
	return client.GetSupplierById(ctx, in, opts...)
}

func (m *defaultSupplierZrpcClient) SearchSupplier(ctx context.Context, in *SearchSupplierReq, opts ...grpc.CallOption) (*SearchSupplierResp, error) {
	client := pb.NewSupplierClient(m.cli.Conn())
	return client.SearchSupplier(ctx, in, opts...)
}

// -----------------------supplierEvaluation-----------------------
func (m *defaultSupplierZrpcClient) AddSupplierEvaluation(ctx context.Context, in *AddSupplierEvaluationReq, opts ...grpc.CallOption) (*AddSupplierEvaluationResp, error) {
	client := pb.NewSupplierClient(m.cli.Conn())
	return client.AddSupplierEvaluation(ctx, in, opts...)
}

// rpc UpdateSupplierEvaluation(UpdateSupplierEvaluationReq) returns (UpdateSupplierEvaluationResp);
func (m *defaultSupplierZrpcClient) GetSupplierEvaluationById(ctx context.Context, in *GetSupplierEvaluationByIdReq, opts ...grpc.CallOption) (*GetSupplierEvaluationByIdResp, error) {
	client := pb.NewSupplierClient(m.cli.Conn())
	return client.GetSupplierEvaluationById(ctx, in, opts...)
}

func (m *defaultSupplierZrpcClient) SearchSupplierEvaluation(ctx context.Context, in *SearchSupplierEvaluationReq, opts ...grpc.CallOption) (*SearchSupplierEvaluationResp, error) {
	client := pb.NewSupplierClient(m.cli.Conn())
	return client.SearchSupplierEvaluation(ctx, in, opts...)
}
