// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: product.proto

package server

import (
	"context"

	"erp/app/product/rpc/internal/logic/product"
	"erp/app/product/rpc/internal/svc"
	"erp/app/product/rpc/pb"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

// -----------------------product-----------------------
func (s *ProductServer) AddProduct(ctx context.Context, in *pb.AddProductReq) (*pb.AddProductResp, error) {
	l := productlogic.NewAddProductLogic(ctx, s.svcCtx)
	return l.AddProduct(in)
}

func (s *ProductServer) UpdateProduct(ctx context.Context, in *pb.UpdateProductReq) (*pb.UpdateProductResp, error) {
	l := productlogic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

// rpc DelProduct(DelProductReq) returns (DelProductResp);
func (s *ProductServer) GetProductByNo(ctx context.Context, in *pb.GetProductByNoReq) (*pb.GetProductByNoResp, error) {
	l := productlogic.NewGetProductByNoLogic(ctx, s.svcCtx)
	return l.GetProductByNo(in)
}

func (s *ProductServer) GetProductById(ctx context.Context, in *pb.GetProductByIdReq) (*pb.GetProductByIdResp, error) {
	l := productlogic.NewGetProductByIdLogic(ctx, s.svcCtx)
	return l.GetProductById(in)
}

func (s *ProductServer) SearchProduct(ctx context.Context, in *pb.SearchProductReq) (*pb.SearchProductResp, error) {
	l := productlogic.NewSearchProductLogic(ctx, s.svcCtx)
	return l.SearchProduct(in)
}
