// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	purchaseRequisitionFieldNames          = builder.RawFieldNames(&PurchaseRequisition{})
	purchaseRequisitionRows                = strings.Join(purchaseRequisitionFieldNames, ",")
	purchaseRequisitionRowsExpectAutoSet   = strings.Join(stringx.Remove(purchaseRequisitionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	purchaseRequisitionRowsWithPlaceHolder = strings.Join(stringx.Remove(purchaseRequisitionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpPurchasePurchaseRequisitionIdPrefix            = "cache:erpPurchase:purchaseRequisition:id:"
	cacheErpPurchasePurchaseRequisitionRequisitionNoPrefix = "cache:erpPurchase:purchaseRequisition:requisitionNo:"
)

type (
	purchaseRequisitionModel interface {
		Insert(ctx context.Context, data *PurchaseRequisition) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PurchaseRequisition, error)
		FindOneByRequisitionNo(ctx context.Context, requisitionNo string) (*PurchaseRequisition, error)
		Update(ctx context.Context, data *PurchaseRequisition) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPurchaseRequisitionModel struct {
		sqlc.CachedConn
		table string
	}

	PurchaseRequisition struct {
		Id            int64          `db:"id"`             // 采购申请ID，雪花
		RequisitionNo string         `db:"requisition_no"` // 采购申请单号
		DepartmentId  int64          `db:"department_id"`  // 申请部门
		ApplicantId   int64          `db:"applicant_id"`   // 申请人（员工工号）
		RequestDate   time.Time      `db:"request_date"`   // 申请日期
		TotalAmount   float64        `db:"total_amount"`   // 申请总金额
		Status        int64          `db:"status"`         // 状态： 1-待审批 2-已审批 3-已驳回 4-已转订单
		ApproverId    sql.NullInt64  `db:"approver_id"`    // 审批人
		ApproveTime   sql.NullTime   `db:"approve_time"`   // 审批时间
		ApproveRemark sql.NullString `db:"approve_remark"` // 审批意见
		CreatedAt     time.Time      `db:"created_at"`
		UpdatedAt     time.Time      `db:"updated_at"`
	}
)

func newPurchaseRequisitionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPurchaseRequisitionModel {
	return &defaultPurchaseRequisitionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`purchase_requisition`",
	}
}

func (m *defaultPurchaseRequisitionModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	erpPurchasePurchaseRequisitionIdKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseRequisitionIdPrefix, id)
	erpPurchasePurchaseRequisitionRequisitionNoKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseRequisitionRequisitionNoPrefix, data.RequisitionNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpPurchasePurchaseRequisitionIdKey, erpPurchasePurchaseRequisitionRequisitionNoKey)
	return err
}

func (m *defaultPurchaseRequisitionModel) FindOne(ctx context.Context, id int64) (*PurchaseRequisition, error) {
	erpPurchasePurchaseRequisitionIdKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseRequisitionIdPrefix, id)
	var resp PurchaseRequisition
	err := m.QueryRowCtx(ctx, &resp, erpPurchasePurchaseRequisitionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", purchaseRequisitionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseRequisitionModel) FindOneByRequisitionNo(ctx context.Context, requisitionNo string) (*PurchaseRequisition, error) {
	erpPurchasePurchaseRequisitionRequisitionNoKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseRequisitionRequisitionNoPrefix, requisitionNo)
	var resp PurchaseRequisition
	err := m.QueryRowIndexCtx(ctx, &resp, erpPurchasePurchaseRequisitionRequisitionNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `requisition_no` = ? limit 1", purchaseRequisitionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, requisitionNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseRequisitionModel) Insert(ctx context.Context, data *PurchaseRequisition) (sql.Result, error) {
	erpPurchasePurchaseRequisitionIdKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseRequisitionIdPrefix, data.Id)
	erpPurchasePurchaseRequisitionRequisitionNoKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseRequisitionRequisitionNoPrefix, data.RequisitionNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, purchaseRequisitionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.RequisitionNo, data.DepartmentId, data.ApplicantId, data.RequestDate, data.TotalAmount, data.Status, data.ApproverId, data.ApproveTime, data.ApproveRemark)
	}, erpPurchasePurchaseRequisitionIdKey, erpPurchasePurchaseRequisitionRequisitionNoKey)
	return ret, err
}

func (m *defaultPurchaseRequisitionModel) Update(ctx context.Context, newData *PurchaseRequisition) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	erpPurchasePurchaseRequisitionIdKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseRequisitionIdPrefix, data.Id)
	erpPurchasePurchaseRequisitionRequisitionNoKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseRequisitionRequisitionNoPrefix, data.RequisitionNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, purchaseRequisitionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RequisitionNo, newData.DepartmentId, newData.ApplicantId, newData.RequestDate, newData.TotalAmount, newData.Status, newData.ApproverId, newData.ApproveTime, newData.ApproveRemark, newData.Id)
	}, erpPurchasePurchaseRequisitionIdKey, erpPurchasePurchaseRequisitionRequisitionNoKey)
	return err
}

func (m *defaultPurchaseRequisitionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpPurchasePurchaseRequisitionIdPrefix, primary)
}

func (m *defaultPurchaseRequisitionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", purchaseRequisitionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPurchaseRequisitionModel) tableName() string {
	return m.table
}
