// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	purchaseOrderFieldNames          = builder.RawFieldNames(&PurchaseOrder{})
	purchaseOrderRows                = strings.Join(purchaseOrderFieldNames, ",")
	purchaseOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(purchaseOrderFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	purchaseOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(purchaseOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpPurchasePurchaseOrderIdPrefix      = "cache:erpPurchase:purchaseOrder:id:"
	cacheErpPurchasePurchaseOrderOrderNoPrefix = "cache:erpPurchase:purchaseOrder:orderNo:"
)

type (
	purchaseOrderModel interface {
		Insert(ctx context.Context, data *PurchaseOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PurchaseOrder, error)
		FindOneByOrderNo(ctx context.Context, orderNo string) (*PurchaseOrder, error)
		Update(ctx context.Context, data *PurchaseOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPurchaseOrderModel struct {
		sqlc.CachedConn
		table string
	}

	PurchaseOrder struct {
		Id           int64          `db:"id"`            // 采购订单ID
		OrderNo      string         `db:"order_no"`      // 采购订单号
		SupplierId   int64          `db:"supplier_id"`   // 供应商ID
		OrderDate    time.Time      `db:"order_date"`    // 下单日期
		ExpectedDate sql.NullTime   `db:"expected_date"` // 期望到货日期
		TotalAmount  float64        `db:"total_amount"`  // 订单总金额
		Status       int64          `db:"status"`        // 状态： 1-已提交 2-已确认 3-部分收货 4-已完成 5-已取消
		PurchaserId  int64          `db:"purchaser_id"`  // 采购人（员工id）
		ContractUrl  sql.NullString `db:"contract_url"`  // 合同URL
		CreatedAt    time.Time      `db:"created_at"`
		UpdatedAt    time.Time      `db:"updated_at"`
	}
)

func newPurchaseOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPurchaseOrderModel {
	return &defaultPurchaseOrderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`purchase_order`",
	}
}

func (m *defaultPurchaseOrderModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	erpPurchasePurchaseOrderIdKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseOrderIdPrefix, id)
	erpPurchasePurchaseOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpPurchasePurchaseOrderIdKey, erpPurchasePurchaseOrderOrderNoKey)
	return err
}

func (m *defaultPurchaseOrderModel) FindOne(ctx context.Context, id int64) (*PurchaseOrder, error) {
	erpPurchasePurchaseOrderIdKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseOrderIdPrefix, id)
	var resp PurchaseOrder
	err := m.QueryRowCtx(ctx, &resp, erpPurchasePurchaseOrderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", purchaseOrderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseOrderModel) FindOneByOrderNo(ctx context.Context, orderNo string) (*PurchaseOrder, error) {
	erpPurchasePurchaseOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseOrderOrderNoPrefix, orderNo)
	var resp PurchaseOrder
	err := m.QueryRowIndexCtx(ctx, &resp, erpPurchasePurchaseOrderOrderNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", purchaseOrderRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, orderNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseOrderModel) Insert(ctx context.Context, data *PurchaseOrder) (sql.Result, error) {
	erpPurchasePurchaseOrderIdKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseOrderIdPrefix, data.Id)
	erpPurchasePurchaseOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseOrderOrderNoPrefix, data.OrderNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, purchaseOrderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.OrderNo, data.SupplierId, data.OrderDate, data.ExpectedDate, data.TotalAmount, data.Status, data.PurchaserId, data.ContractUrl)
	}, erpPurchasePurchaseOrderIdKey, erpPurchasePurchaseOrderOrderNoKey)
	return ret, err
}

func (m *defaultPurchaseOrderModel) Update(ctx context.Context, newData *PurchaseOrder) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	erpPurchasePurchaseOrderIdKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseOrderIdPrefix, data.Id)
	erpPurchasePurchaseOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpPurchasePurchaseOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, purchaseOrderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.OrderNo, newData.SupplierId, newData.OrderDate, newData.ExpectedDate, newData.TotalAmount, newData.Status, newData.PurchaserId, newData.ContractUrl, newData.Id)
	}, erpPurchasePurchaseOrderIdKey, erpPurchasePurchaseOrderOrderNoKey)
	return err
}

func (m *defaultPurchaseOrderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpPurchasePurchaseOrderIdPrefix, primary)
}

func (m *defaultPurchaseOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", purchaseOrderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPurchaseOrderModel) tableName() string {
	return m.table
}
