// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	inventory "erp/app/inventory/api/internal/handler/inventory"
	warehouse "erp/app/inventory/api/internal/handler/warehouse"
	"erp/app/inventory/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: inventory.CreateInventoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: inventory.GetInventoryDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/adjust",
					Handler: inventory.AdjustInventoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/alerts",
					Handler: inventory.GetLowStockAlertHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/check",
					Handler: inventory.InventoryCheckHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: inventory.GetInventoryListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/setInventoryLock",
					Handler: inventory.SetInventoryLockHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/summary",
					Handler: inventory.GetProductInventorySummaryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/transactions",
					Handler: inventory.GetInventoryTransactionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/inventory"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: warehouse.CreateWarehouseHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: warehouse.UpdateWarehouseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: warehouse.GetWarehouseDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: warehouse.GetWarehouseListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/warehouse"),
	)
}
