// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	employeeDetailFieldNames          = builder.RawFieldNames(&EmployeeDetail{})
	employeeDetailRows                = strings.Join(employeeDetailFieldNames, ",")
	employeeDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(employeeDetailFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	employeeDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(employeeDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpHrEmployeeDetailIdPrefix         = "cache:erpHr:employeeDetail:id:"
	cacheErpHrEmployeeDetailEmployeeNoPrefix = "cache:erpHr:employeeDetail:employeeNo:"
)

type (
	employeeDetailModel interface {
		Insert(ctx context.Context, data *EmployeeDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*EmployeeDetail, error)
		FindOneByEmployeeNo(ctx context.Context, employeeNo string) (*EmployeeDetail, error)
		Update(ctx context.Context, data *EmployeeDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEmployeeDetailModel struct {
		sqlc.CachedConn
		table string
	}

	EmployeeDetail struct {
		Id           int64           `db:"id"`            // 主键ID，雪花
		EmployeeNo   string          `db:"employee_no"`   // 员工编号,E+年月日+随机四位
		Name         string          `db:"name"`          // 真实姓名
		IdCard       string          `db:"id_card"`       // 身份证号
		Account      sql.NullString  `db:"account"`       // 银行卡号
		Gender       int64           `db:"gender"`        // 性别：1-男 2-女
		BirthDate    time.Time       `db:"birth_date"`    // 出生日期
		DepartmentId int64           `db:"department_id"` // 所属部门
		PositionId   int64           `db:"position_id"`   // 职位
		Salary       sql.NullFloat64 `db:"salary"`        // 基本工资
		HireDate     time.Time       `db:"hire_date"`     // 入职日期
		LeaveDate    sql.NullTime    `db:"leave_date"`    // 离职日期
	}
)

func newEmployeeDetailModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultEmployeeDetailModel {
	return &defaultEmployeeDetailModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`employee_detail`",
	}
}

func (m *defaultEmployeeDetailModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	erpHrEmployeeDetailEmployeeNoKey := fmt.Sprintf("%s%v", cacheErpHrEmployeeDetailEmployeeNoPrefix, data.EmployeeNo)
	erpHrEmployeeDetailIdKey := fmt.Sprintf("%s%v", cacheErpHrEmployeeDetailIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpHrEmployeeDetailEmployeeNoKey, erpHrEmployeeDetailIdKey)
	return err
}

func (m *defaultEmployeeDetailModel) FindOne(ctx context.Context, id int64) (*EmployeeDetail, error) {
	erpHrEmployeeDetailIdKey := fmt.Sprintf("%s%v", cacheErpHrEmployeeDetailIdPrefix, id)
	var resp EmployeeDetail
	err := m.QueryRowCtx(ctx, &resp, erpHrEmployeeDetailIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", employeeDetailRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmployeeDetailModel) FindOneByEmployeeNo(ctx context.Context, employeeNo string) (*EmployeeDetail, error) {
	erpHrEmployeeDetailEmployeeNoKey := fmt.Sprintf("%s%v", cacheErpHrEmployeeDetailEmployeeNoPrefix, employeeNo)
	var resp EmployeeDetail
	err := m.QueryRowIndexCtx(ctx, &resp, erpHrEmployeeDetailEmployeeNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `employee_no` = ? limit 1", employeeDetailRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, employeeNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmployeeDetailModel) Insert(ctx context.Context, data *EmployeeDetail) (sql.Result, error) {
	erpHrEmployeeDetailEmployeeNoKey := fmt.Sprintf("%s%v", cacheErpHrEmployeeDetailEmployeeNoPrefix, data.EmployeeNo)
	erpHrEmployeeDetailIdKey := fmt.Sprintf("%s%v", cacheErpHrEmployeeDetailIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, employeeDetailRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.EmployeeNo, data.Name, data.IdCard, data.Account, data.Gender, data.BirthDate, data.DepartmentId, data.PositionId, data.Salary, data.HireDate, data.LeaveDate)
	}, erpHrEmployeeDetailEmployeeNoKey, erpHrEmployeeDetailIdKey)
	return ret, err
}

func (m *defaultEmployeeDetailModel) Update(ctx context.Context, newData *EmployeeDetail) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	erpHrEmployeeDetailEmployeeNoKey := fmt.Sprintf("%s%v", cacheErpHrEmployeeDetailEmployeeNoPrefix, data.EmployeeNo)
	erpHrEmployeeDetailIdKey := fmt.Sprintf("%s%v", cacheErpHrEmployeeDetailIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, employeeDetailRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.EmployeeNo, newData.Name, newData.IdCard, newData.Account, newData.Gender, newData.BirthDate, newData.DepartmentId, newData.PositionId, newData.Salary, newData.HireDate, newData.LeaveDate, newData.Id)
	}, erpHrEmployeeDetailEmployeeNoKey, erpHrEmployeeDetailIdKey)
	return err
}

func (m *defaultEmployeeDetailModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpHrEmployeeDetailIdPrefix, primary)
}

func (m *defaultEmployeeDetailModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", employeeDetailRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultEmployeeDetailModel) tableName() string {
	return m.table
}
