// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	payrollRecordFieldNames          = builder.RawFieldNames(&PayrollRecord{})
	payrollRecordRows                = strings.Join(payrollRecordFieldNames, ",")
	payrollRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(payrollRecordFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	payrollRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(payrollRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpHrPayrollRecordIdPrefix                     = "cache:erpHr:payrollRecord:id:"
	cacheErpHrPayrollRecordEmployeeIdPaymentMonthPrefix = "cache:erpHr:payrollRecord:employeeId:paymentMonth:"
)

type (
	payrollRecordModel interface {
		Insert(ctx context.Context, data *PayrollRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PayrollRecord, error)
		FindOneByEmployeeIdPaymentMonth(ctx context.Context, employeeId int64, paymentMonth time.Time) (*PayrollRecord, error)
		Update(ctx context.Context, data *PayrollRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPayrollRecordModel struct {
		sqlc.CachedConn
		table string
	}

	PayrollRecord struct {
		Id           int64           `db:"id"`            // 主键ID，雪花
		EmployeeId   int64           `db:"employee_id"`   // 员工id
		PaymentMonth time.Time       `db:"payment_month"` // 薪资月份(如2025-06-01表示6月)
		BaseSalary   sql.NullFloat64 `db:"base_salary"`   // 基本工资
		Bonus        float64         `db:"bonus"`         // 奖金
		Deductions   float64         `db:"deductions"`    // 扣款
		NetSalary    sql.NullFloat64 `db:"net_salary"`    // 实发工资
		CalculatedBy sql.NullInt64   `db:"calculated_by"` // 核算人id
		CalculatedAt sql.NullTime    `db:"calculated_at"` // 核算日期时间
		Status       int64           `db:"status"`        // 薪酬状态：1-未核算，2-已核算，3-已提交，4-待发放，5-已发放，6-发放失败
		Description  sql.NullString  `db:"description"`   // 描述/备注
		PaymentAt    sql.NullTime    `db:"payment_at"`    // 发放日期
		CreatedAt    time.Time       `db:"created_at"`    // 创建时间
	}
)

func newPayrollRecordModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPayrollRecordModel {
	return &defaultPayrollRecordModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`payroll_record`",
	}
}

func (m *defaultPayrollRecordModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	erpHrPayrollRecordEmployeeIdPaymentMonthKey := fmt.Sprintf("%s%v:%v", cacheErpHrPayrollRecordEmployeeIdPaymentMonthPrefix, data.EmployeeId, data.PaymentMonth)
	erpHrPayrollRecordIdKey := fmt.Sprintf("%s%v", cacheErpHrPayrollRecordIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpHrPayrollRecordEmployeeIdPaymentMonthKey, erpHrPayrollRecordIdKey)
	return err
}

func (m *defaultPayrollRecordModel) FindOne(ctx context.Context, id int64) (*PayrollRecord, error) {
	erpHrPayrollRecordIdKey := fmt.Sprintf("%s%v", cacheErpHrPayrollRecordIdPrefix, id)
	var resp PayrollRecord
	err := m.QueryRowCtx(ctx, &resp, erpHrPayrollRecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", payrollRecordRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPayrollRecordModel) FindOneByEmployeeIdPaymentMonth(ctx context.Context, employeeId int64, paymentMonth time.Time) (*PayrollRecord, error) {
	erpHrPayrollRecordEmployeeIdPaymentMonthKey := fmt.Sprintf("%s%v:%v", cacheErpHrPayrollRecordEmployeeIdPaymentMonthPrefix, employeeId, paymentMonth)
	var resp PayrollRecord
	err := m.QueryRowIndexCtx(ctx, &resp, erpHrPayrollRecordEmployeeIdPaymentMonthKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `employee_id` = ? and `payment_month` = ? limit 1", payrollRecordRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, employeeId, paymentMonth); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPayrollRecordModel) Insert(ctx context.Context, data *PayrollRecord) (sql.Result, error) {
	erpHrPayrollRecordEmployeeIdPaymentMonthKey := fmt.Sprintf("%s%v:%v", cacheErpHrPayrollRecordEmployeeIdPaymentMonthPrefix, data.EmployeeId, data.PaymentMonth)
	erpHrPayrollRecordIdKey := fmt.Sprintf("%s%v", cacheErpHrPayrollRecordIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, payrollRecordRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.EmployeeId, data.PaymentMonth, data.BaseSalary, data.Bonus, data.Deductions, data.NetSalary, data.CalculatedBy, data.CalculatedAt, data.Status, data.Description, data.PaymentAt)
	}, erpHrPayrollRecordEmployeeIdPaymentMonthKey, erpHrPayrollRecordIdKey)
	return ret, err
}

func (m *defaultPayrollRecordModel) Update(ctx context.Context, newData *PayrollRecord) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	erpHrPayrollRecordEmployeeIdPaymentMonthKey := fmt.Sprintf("%s%v:%v", cacheErpHrPayrollRecordEmployeeIdPaymentMonthPrefix, data.EmployeeId, data.PaymentMonth)
	erpHrPayrollRecordIdKey := fmt.Sprintf("%s%v", cacheErpHrPayrollRecordIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, payrollRecordRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.EmployeeId, newData.PaymentMonth, newData.BaseSalary, newData.Bonus, newData.Deductions, newData.NetSalary, newData.CalculatedBy, newData.CalculatedAt, newData.Status, newData.Description, newData.PaymentAt, newData.Id)
	}, erpHrPayrollRecordEmployeeIdPaymentMonthKey, erpHrPayrollRecordIdKey)
	return err
}

func (m *defaultPayrollRecordModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpHrPayrollRecordIdPrefix, primary)
}

func (m *defaultPayrollRecordModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", payrollRecordRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPayrollRecordModel) tableName() string {
	return m.table
}
