// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: purchase.proto

package server

import (
	"context"

	"erp/app/purchase/rpc/internal/logic/purchaseorder"
	"erp/app/purchase/rpc/internal/svc"
	"erp/app/purchase/rpc/pb"
)

type PurchaseOrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPurchaseOrderServer
}

func NewPurchaseOrderServer(svcCtx *svc.ServiceContext) *PurchaseOrderServer {
	return &PurchaseOrderServer{
		svcCtx: svcCtx,
	}
}

// 从采购申请创建采购订单（通过 requisition_id 获取申请明细数据，保证一致性）
func (s *PurchaseOrderServer) CreateOrderFromRequisition(ctx context.Context, in *pb.CreateOrderFromRequisitionReq) (*pb.CreateOrderFromRequisitionResp, error) {
	l := purchaseorderlogic.NewCreateOrderFromRequisitionLogic(ctx, s.svcCtx)
	return l.CreateOrderFromRequisition(in)
}

// 直接创建采购订单及明细（事务）
func (s *PurchaseOrderServer) CreateOrderWithDetails(ctx context.Context, in *pb.CreateOrderWithDetailsReq) (*pb.CreateOrderWithDetailsResp, error) {
	l := purchaseorderlogic.NewCreateOrderWithDetailsLogic(ctx, s.svcCtx)
	return l.CreateOrderWithDetails(in)
}

// 取消采购订单
func (s *PurchaseOrderServer) CancelPurchaseOrder(ctx context.Context, in *pb.CancelPurchaseOrderReq) (*pb.CancelPurchaseOrderResp, error) {
	l := purchaseorderlogic.NewCancelPurchaseOrderLogic(ctx, s.svcCtx)
	return l.CancelPurchaseOrder(in)
}

// 获取采购订单及明细
func (s *PurchaseOrderServer) GetOrderWithDetails(ctx context.Context, in *pb.GetOrderWithDetailsReq) (*pb.GetOrderWithDetailsResp, error) {
	l := purchaseorderlogic.NewGetOrderWithDetailsLogic(ctx, s.svcCtx)
	return l.GetOrderWithDetails(in)
}

// 查询采购订单
func (s *PurchaseOrderServer) SearchOrder(ctx context.Context, in *pb.SearchOrderReq) (*pb.SearchOrderResp, error) {
	l := purchaseorderlogic.NewSearchOrderLogic(ctx, s.svcCtx)
	return l.SearchOrder(in)
}

// 更新采购订单（动态SQL拼接）
func (s *PurchaseOrderServer) UpdateOrder(ctx context.Context, in *pb.UpdateOrderReq) (*pb.UpdateOrderResp, error) {
	l := purchaseorderlogic.NewUpdateOrderLogic(ctx, s.svcCtx)
	return l.UpdateOrder(in)
}

// 更新采购订单明细（动态SQL拼接）
func (s *PurchaseOrderServer) UpdateOrderDetail(ctx context.Context, in *pb.UpdateOrderDetailReq) (*pb.UpdateOrderDetailResp, error) {
	l := purchaseorderlogic.NewUpdateOrderDetailLogic(ctx, s.svcCtx)
	return l.UpdateOrderDetail(in)
}
