// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: finance.proto

package server

import (
	"context"

	"erp/app/finance/rpc/internal/logic/salarypayment"
	"erp/app/finance/rpc/internal/svc"
	"erp/app/finance/rpc/pb"
)

type SalaryPaymentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSalaryPaymentServer
}

func NewSalaryPaymentServer(svcCtx *svc.ServiceContext) *SalaryPaymentServer {
	return &SalaryPaymentServer{
		svcCtx: svcCtx,
	}
}

// -----------------------salaryPayment-----------------------
func (s *SalaryPaymentServer) AddSalaryPayment(ctx context.Context, in *pb.AddSalaryPaymentReq) (*pb.AddSalaryPaymentResp, error) {
	l := salarypaymentlogic.NewAddSalaryPaymentLogic(ctx, s.svcCtx)
	return l.AddSalaryPayment(in)
}

func (s *SalaryPaymentServer) UpdateSalaryPayment(ctx context.Context, in *pb.UpdateSalaryPaymentReq) (*pb.UpdateSalaryPaymentResp, error) {
	l := salarypaymentlogic.NewUpdateSalaryPaymentLogic(ctx, s.svcCtx)
	return l.UpdateSalaryPayment(in)
}

func (s *SalaryPaymentServer) GetSalaryPaymentById(ctx context.Context, in *pb.GetSalaryPaymentByIdReq) (*pb.GetSalaryPaymentByIdResp, error) {
	l := salarypaymentlogic.NewGetSalaryPaymentByIdLogic(ctx, s.svcCtx)
	return l.GetSalaryPaymentById(in)
}

func (s *SalaryPaymentServer) SearchSalaryPayment(ctx context.Context, in *pb.SearchSalaryPaymentReq) (*pb.SearchSalaryPaymentResp, error) {
	l := salarypaymentlogic.NewSearchSalaryPaymentLogic(ctx, s.svcCtx)
	return l.SearchSalaryPayment(in)
}
