// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: production.proto

package production

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Production_CreateBom_FullMethodName             = "/production.Production/CreateBom"
	Production_UpdateBom_FullMethodName             = "/production.Production/UpdateBom"
	Production_DeleteBom_FullMethodName             = "/production.Production/DeleteBom"
	Production_GetBom_FullMethodName                = "/production.Production/GetBom"
	Production_GetBomList_FullMethodName            = "/production.Production/GetBomList"
	Production_CreateBomItem_FullMethodName         = "/production.Production/CreateBomItem"
	Production_UpdateBomItem_FullMethodName         = "/production.Production/UpdateBomItem"
	Production_DeleteBomItem_FullMethodName         = "/production.Production/DeleteBomItem"
	Production_CreateWorkOrder_FullMethodName       = "/production.Production/CreateWorkOrder"
	Production_UpdateWorkOrder_FullMethodName       = "/production.Production/UpdateWorkOrder"
	Production_DeleteWorkOrder_FullMethodName       = "/production.Production/DeleteWorkOrder"
	Production_GetWorkOrder_FullMethodName          = "/production.Production/GetWorkOrder"
	Production_GetWorkOrderList_FullMethodName      = "/production.Production/GetWorkOrderList"
	Production_CreateRequisition_FullMethodName     = "/production.Production/CreateRequisition"
	Production_UpdateRequisition_FullMethodName     = "/production.Production/UpdateRequisition"
	Production_GetRequisition_FullMethodName        = "/production.Production/GetRequisition"
	Production_GetRequisitionList_FullMethodName    = "/production.Production/GetRequisitionList"
	Production_ApproveRequisition_FullMethodName    = "/production.Production/ApproveRequisition"
	Production_CreateRequisitionItem_FullMethodName = "/production.Production/CreateRequisitionItem"
	Production_UpdateRequisitionItem_FullMethodName = "/production.Production/UpdateRequisitionItem"
	Production_DeleteRequisitionItem_FullMethodName = "/production.Production/DeleteRequisitionItem"
)

// ProductionClient is the client API for Production service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 生产服务
type ProductionClient interface {
	// BOM管理
	CreateBom(ctx context.Context, in *CreateBomReq, opts ...grpc.CallOption) (*CreateBomResp, error)
	UpdateBom(ctx context.Context, in *UpdateBomReq, opts ...grpc.CallOption) (*UpdateBomResp, error)
	DeleteBom(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error)
	GetBom(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*BomInfo, error)
	GetBomList(ctx context.Context, in *BomListReq, opts ...grpc.CallOption) (*BomListResp, error)
	// BOM明细管理
	CreateBomItem(ctx context.Context, in *CreateBomItemReq, opts ...grpc.CallOption) (*CreateBomItemResp, error)
	UpdateBomItem(ctx context.Context, in *UpdateBomItemReq, opts ...grpc.CallOption) (*UpdateBomItemResp, error)
	DeleteBomItem(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error)
	// 生产工单管理
	CreateWorkOrder(ctx context.Context, in *CreateWorkOrderReq, opts ...grpc.CallOption) (*CreateWorkOrderResp, error)
	UpdateWorkOrder(ctx context.Context, in *UpdateWorkOrderReq, opts ...grpc.CallOption) (*UpdateWorkOrderResp, error)
	DeleteWorkOrder(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error)
	GetWorkOrder(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*WorkOrderInfo, error)
	GetWorkOrderList(ctx context.Context, in *WorkOrderListReq, opts ...grpc.CallOption) (*WorkOrderListResp, error)
	// 领料单管理
	CreateRequisition(ctx context.Context, in *CreateRequisitionReq, opts ...grpc.CallOption) (*CreateRequisitionResp, error)
	UpdateRequisition(ctx context.Context, in *UpdateRequisitionReq, opts ...grpc.CallOption) (*UpdateRequisitionResp, error)
	GetRequisition(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*RequisitionInfo, error)
	GetRequisitionList(ctx context.Context, in *RequisitionListReq, opts ...grpc.CallOption) (*RequisitionListResp, error)
	ApproveRequisition(ctx context.Context, in *ApproveRequisitionReq, opts ...grpc.CallOption) (*ApproveRequisitionResp, error)
	// 领料单明细管理
	CreateRequisitionItem(ctx context.Context, in *CreateRequisitionItemReq, opts ...grpc.CallOption) (*CreateRequisitionItemResp, error)
	UpdateRequisitionItem(ctx context.Context, in *UpdateRequisitionItemReq, opts ...grpc.CallOption) (*UpdateRequisitionItemResp, error)
	DeleteRequisitionItem(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error)
}

type productionClient struct {
	cc grpc.ClientConnInterface
}

func NewProductionClient(cc grpc.ClientConnInterface) ProductionClient {
	return &productionClient{cc}
}

func (c *productionClient) CreateBom(ctx context.Context, in *CreateBomReq, opts ...grpc.CallOption) (*CreateBomResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBomResp)
	err := c.cc.Invoke(ctx, Production_CreateBom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) UpdateBom(ctx context.Context, in *UpdateBomReq, opts ...grpc.CallOption) (*UpdateBomResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBomResp)
	err := c.cc.Invoke(ctx, Production_UpdateBom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) DeleteBom(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Production_DeleteBom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) GetBom(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*BomInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BomInfo)
	err := c.cc.Invoke(ctx, Production_GetBom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) GetBomList(ctx context.Context, in *BomListReq, opts ...grpc.CallOption) (*BomListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BomListResp)
	err := c.cc.Invoke(ctx, Production_GetBomList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) CreateBomItem(ctx context.Context, in *CreateBomItemReq, opts ...grpc.CallOption) (*CreateBomItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBomItemResp)
	err := c.cc.Invoke(ctx, Production_CreateBomItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) UpdateBomItem(ctx context.Context, in *UpdateBomItemReq, opts ...grpc.CallOption) (*UpdateBomItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBomItemResp)
	err := c.cc.Invoke(ctx, Production_UpdateBomItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) DeleteBomItem(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Production_DeleteBomItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) CreateWorkOrder(ctx context.Context, in *CreateWorkOrderReq, opts ...grpc.CallOption) (*CreateWorkOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkOrderResp)
	err := c.cc.Invoke(ctx, Production_CreateWorkOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) UpdateWorkOrder(ctx context.Context, in *UpdateWorkOrderReq, opts ...grpc.CallOption) (*UpdateWorkOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkOrderResp)
	err := c.cc.Invoke(ctx, Production_UpdateWorkOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) DeleteWorkOrder(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Production_DeleteWorkOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) GetWorkOrder(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*WorkOrderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkOrderInfo)
	err := c.cc.Invoke(ctx, Production_GetWorkOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) GetWorkOrderList(ctx context.Context, in *WorkOrderListReq, opts ...grpc.CallOption) (*WorkOrderListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkOrderListResp)
	err := c.cc.Invoke(ctx, Production_GetWorkOrderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) CreateRequisition(ctx context.Context, in *CreateRequisitionReq, opts ...grpc.CallOption) (*CreateRequisitionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRequisitionResp)
	err := c.cc.Invoke(ctx, Production_CreateRequisition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) UpdateRequisition(ctx context.Context, in *UpdateRequisitionReq, opts ...grpc.CallOption) (*UpdateRequisitionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRequisitionResp)
	err := c.cc.Invoke(ctx, Production_UpdateRequisition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) GetRequisition(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*RequisitionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequisitionInfo)
	err := c.cc.Invoke(ctx, Production_GetRequisition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) GetRequisitionList(ctx context.Context, in *RequisitionListReq, opts ...grpc.CallOption) (*RequisitionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequisitionListResp)
	err := c.cc.Invoke(ctx, Production_GetRequisitionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) ApproveRequisition(ctx context.Context, in *ApproveRequisitionReq, opts ...grpc.CallOption) (*ApproveRequisitionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveRequisitionResp)
	err := c.cc.Invoke(ctx, Production_ApproveRequisition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) CreateRequisitionItem(ctx context.Context, in *CreateRequisitionItemReq, opts ...grpc.CallOption) (*CreateRequisitionItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRequisitionItemResp)
	err := c.cc.Invoke(ctx, Production_CreateRequisitionItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) UpdateRequisitionItem(ctx context.Context, in *UpdateRequisitionItemReq, opts ...grpc.CallOption) (*UpdateRequisitionItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRequisitionItemResp)
	err := c.cc.Invoke(ctx, Production_UpdateRequisitionItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionClient) DeleteRequisitionItem(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Production_DeleteRequisitionItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductionServer is the server API for Production service.
// All implementations must embed UnimplementedProductionServer
// for forward compatibility.
//
// 生产服务
type ProductionServer interface {
	// BOM管理
	CreateBom(context.Context, *CreateBomReq) (*CreateBomResp, error)
	UpdateBom(context.Context, *UpdateBomReq) (*UpdateBomResp, error)
	DeleteBom(context.Context, *IdReq) (*EmptyResp, error)
	GetBom(context.Context, *IdReq) (*BomInfo, error)
	GetBomList(context.Context, *BomListReq) (*BomListResp, error)
	// BOM明细管理
	CreateBomItem(context.Context, *CreateBomItemReq) (*CreateBomItemResp, error)
	UpdateBomItem(context.Context, *UpdateBomItemReq) (*UpdateBomItemResp, error)
	DeleteBomItem(context.Context, *IdReq) (*EmptyResp, error)
	// 生产工单管理
	CreateWorkOrder(context.Context, *CreateWorkOrderReq) (*CreateWorkOrderResp, error)
	UpdateWorkOrder(context.Context, *UpdateWorkOrderReq) (*UpdateWorkOrderResp, error)
	DeleteWorkOrder(context.Context, *IdReq) (*EmptyResp, error)
	GetWorkOrder(context.Context, *IdReq) (*WorkOrderInfo, error)
	GetWorkOrderList(context.Context, *WorkOrderListReq) (*WorkOrderListResp, error)
	// 领料单管理
	CreateRequisition(context.Context, *CreateRequisitionReq) (*CreateRequisitionResp, error)
	UpdateRequisition(context.Context, *UpdateRequisitionReq) (*UpdateRequisitionResp, error)
	GetRequisition(context.Context, *IdReq) (*RequisitionInfo, error)
	GetRequisitionList(context.Context, *RequisitionListReq) (*RequisitionListResp, error)
	ApproveRequisition(context.Context, *ApproveRequisitionReq) (*ApproveRequisitionResp, error)
	// 领料单明细管理
	CreateRequisitionItem(context.Context, *CreateRequisitionItemReq) (*CreateRequisitionItemResp, error)
	UpdateRequisitionItem(context.Context, *UpdateRequisitionItemReq) (*UpdateRequisitionItemResp, error)
	DeleteRequisitionItem(context.Context, *IdReq) (*EmptyResp, error)
	mustEmbedUnimplementedProductionServer()
}

// UnimplementedProductionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductionServer struct{}

func (UnimplementedProductionServer) CreateBom(context.Context, *CreateBomReq) (*CreateBomResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBom not implemented")
}
func (UnimplementedProductionServer) UpdateBom(context.Context, *UpdateBomReq) (*UpdateBomResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBom not implemented")
}
func (UnimplementedProductionServer) DeleteBom(context.Context, *IdReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBom not implemented")
}
func (UnimplementedProductionServer) GetBom(context.Context, *IdReq) (*BomInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBom not implemented")
}
func (UnimplementedProductionServer) GetBomList(context.Context, *BomListReq) (*BomListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBomList not implemented")
}
func (UnimplementedProductionServer) CreateBomItem(context.Context, *CreateBomItemReq) (*CreateBomItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBomItem not implemented")
}
func (UnimplementedProductionServer) UpdateBomItem(context.Context, *UpdateBomItemReq) (*UpdateBomItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBomItem not implemented")
}
func (UnimplementedProductionServer) DeleteBomItem(context.Context, *IdReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBomItem not implemented")
}
func (UnimplementedProductionServer) CreateWorkOrder(context.Context, *CreateWorkOrderReq) (*CreateWorkOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkOrder not implemented")
}
func (UnimplementedProductionServer) UpdateWorkOrder(context.Context, *UpdateWorkOrderReq) (*UpdateWorkOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkOrder not implemented")
}
func (UnimplementedProductionServer) DeleteWorkOrder(context.Context, *IdReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkOrder not implemented")
}
func (UnimplementedProductionServer) GetWorkOrder(context.Context, *IdReq) (*WorkOrderInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkOrder not implemented")
}
func (UnimplementedProductionServer) GetWorkOrderList(context.Context, *WorkOrderListReq) (*WorkOrderListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkOrderList not implemented")
}
func (UnimplementedProductionServer) CreateRequisition(context.Context, *CreateRequisitionReq) (*CreateRequisitionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRequisition not implemented")
}
func (UnimplementedProductionServer) UpdateRequisition(context.Context, *UpdateRequisitionReq) (*UpdateRequisitionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRequisition not implemented")
}
func (UnimplementedProductionServer) GetRequisition(context.Context, *IdReq) (*RequisitionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequisition not implemented")
}
func (UnimplementedProductionServer) GetRequisitionList(context.Context, *RequisitionListReq) (*RequisitionListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequisitionList not implemented")
}
func (UnimplementedProductionServer) ApproveRequisition(context.Context, *ApproveRequisitionReq) (*ApproveRequisitionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveRequisition not implemented")
}
func (UnimplementedProductionServer) CreateRequisitionItem(context.Context, *CreateRequisitionItemReq) (*CreateRequisitionItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRequisitionItem not implemented")
}
func (UnimplementedProductionServer) UpdateRequisitionItem(context.Context, *UpdateRequisitionItemReq) (*UpdateRequisitionItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRequisitionItem not implemented")
}
func (UnimplementedProductionServer) DeleteRequisitionItem(context.Context, *IdReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRequisitionItem not implemented")
}
func (UnimplementedProductionServer) mustEmbedUnimplementedProductionServer() {}
func (UnimplementedProductionServer) testEmbeddedByValue()                    {}

// UnsafeProductionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductionServer will
// result in compilation errors.
type UnsafeProductionServer interface {
	mustEmbedUnimplementedProductionServer()
}

func RegisterProductionServer(s grpc.ServiceRegistrar, srv ProductionServer) {
	// If the following call pancis, it indicates UnimplementedProductionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Production_ServiceDesc, srv)
}

func _Production_CreateBom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).CreateBom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_CreateBom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).CreateBom(ctx, req.(*CreateBomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_UpdateBom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).UpdateBom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_UpdateBom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).UpdateBom(ctx, req.(*UpdateBomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_DeleteBom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).DeleteBom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_DeleteBom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).DeleteBom(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_GetBom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).GetBom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_GetBom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).GetBom(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_GetBomList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BomListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).GetBomList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_GetBomList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).GetBomList(ctx, req.(*BomListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_CreateBomItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBomItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).CreateBomItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_CreateBomItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).CreateBomItem(ctx, req.(*CreateBomItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_UpdateBomItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBomItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).UpdateBomItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_UpdateBomItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).UpdateBomItem(ctx, req.(*UpdateBomItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_DeleteBomItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).DeleteBomItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_DeleteBomItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).DeleteBomItem(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_CreateWorkOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).CreateWorkOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_CreateWorkOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).CreateWorkOrder(ctx, req.(*CreateWorkOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_UpdateWorkOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).UpdateWorkOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_UpdateWorkOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).UpdateWorkOrder(ctx, req.(*UpdateWorkOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_DeleteWorkOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).DeleteWorkOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_DeleteWorkOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).DeleteWorkOrder(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_GetWorkOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).GetWorkOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_GetWorkOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).GetWorkOrder(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_GetWorkOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkOrderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).GetWorkOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_GetWorkOrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).GetWorkOrderList(ctx, req.(*WorkOrderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_CreateRequisition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequisitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).CreateRequisition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_CreateRequisition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).CreateRequisition(ctx, req.(*CreateRequisitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_UpdateRequisition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequisitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).UpdateRequisition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_UpdateRequisition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).UpdateRequisition(ctx, req.(*UpdateRequisitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_GetRequisition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).GetRequisition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_GetRequisition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).GetRequisition(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_GetRequisitionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequisitionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).GetRequisitionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_GetRequisitionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).GetRequisitionList(ctx, req.(*RequisitionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_ApproveRequisition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequisitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).ApproveRequisition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_ApproveRequisition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).ApproveRequisition(ctx, req.(*ApproveRequisitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_CreateRequisitionItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequisitionItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).CreateRequisitionItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_CreateRequisitionItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).CreateRequisitionItem(ctx, req.(*CreateRequisitionItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_UpdateRequisitionItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequisitionItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).UpdateRequisitionItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_UpdateRequisitionItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).UpdateRequisitionItem(ctx, req.(*UpdateRequisitionItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Production_DeleteRequisitionItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServer).DeleteRequisitionItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Production_DeleteRequisitionItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServer).DeleteRequisitionItem(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Production_ServiceDesc is the grpc.ServiceDesc for Production service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Production_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "production.Production",
	HandlerType: (*ProductionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBom",
			Handler:    _Production_CreateBom_Handler,
		},
		{
			MethodName: "UpdateBom",
			Handler:    _Production_UpdateBom_Handler,
		},
		{
			MethodName: "DeleteBom",
			Handler:    _Production_DeleteBom_Handler,
		},
		{
			MethodName: "GetBom",
			Handler:    _Production_GetBom_Handler,
		},
		{
			MethodName: "GetBomList",
			Handler:    _Production_GetBomList_Handler,
		},
		{
			MethodName: "CreateBomItem",
			Handler:    _Production_CreateBomItem_Handler,
		},
		{
			MethodName: "UpdateBomItem",
			Handler:    _Production_UpdateBomItem_Handler,
		},
		{
			MethodName: "DeleteBomItem",
			Handler:    _Production_DeleteBomItem_Handler,
		},
		{
			MethodName: "CreateWorkOrder",
			Handler:    _Production_CreateWorkOrder_Handler,
		},
		{
			MethodName: "UpdateWorkOrder",
			Handler:    _Production_UpdateWorkOrder_Handler,
		},
		{
			MethodName: "DeleteWorkOrder",
			Handler:    _Production_DeleteWorkOrder_Handler,
		},
		{
			MethodName: "GetWorkOrder",
			Handler:    _Production_GetWorkOrder_Handler,
		},
		{
			MethodName: "GetWorkOrderList",
			Handler:    _Production_GetWorkOrderList_Handler,
		},
		{
			MethodName: "CreateRequisition",
			Handler:    _Production_CreateRequisition_Handler,
		},
		{
			MethodName: "UpdateRequisition",
			Handler:    _Production_UpdateRequisition_Handler,
		},
		{
			MethodName: "GetRequisition",
			Handler:    _Production_GetRequisition_Handler,
		},
		{
			MethodName: "GetRequisitionList",
			Handler:    _Production_GetRequisitionList_Handler,
		},
		{
			MethodName: "ApproveRequisition",
			Handler:    _Production_ApproveRequisition_Handler,
		},
		{
			MethodName: "CreateRequisitionItem",
			Handler:    _Production_CreateRequisitionItem_Handler,
		},
		{
			MethodName: "UpdateRequisitionItem",
			Handler:    _Production_UpdateRequisitionItem_Handler,
		},
		{
			MethodName: "DeleteRequisitionItem",
			Handler:    _Production_DeleteRequisitionItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "production.proto",
}
