// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	inventoryFieldNames          = builder.RawFieldNames(&Inventory{})
	inventoryRows                = strings.Join(inventoryFieldNames, ",")
	inventoryRowsExpectAutoSet   = strings.Join(stringx.Remove(inventoryFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	inventoryRowsWithPlaceHolder = strings.Join(stringx.Remove(inventoryFieldNames, "`inventory_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpInventoryInventoryInventoryIdPrefix          = "cache:erpInventory:inventory:inventoryId:"
	cacheErpInventoryInventoryProductIdWarehouseIdPrefix = "cache:erpInventory:inventory:productId:warehouseId:"
)

type (
	inventoryModel interface {
		Insert(ctx context.Context, data *Inventory) (sql.Result, error)
		FindOne(ctx context.Context, inventoryId int64) (*Inventory, error)
		FindOneByProductIdWarehouseId(ctx context.Context, productId int64, warehouseId int64) (*Inventory, error)
		Update(ctx context.Context, data *Inventory) error
		Delete(ctx context.Context, inventoryId int64) error
	}

	defaultInventoryModel struct {
		sqlc.CachedConn
		table string
	}

	Inventory struct {
		InventoryId  int64   `db:"inventory_id"`  // 库存ID
		ProductId    int64   `db:"product_id"`    // 商品ID
		WarehouseId  int64   `db:"warehouse_id"`  // 仓库编号
		CurrentStock float64 `db:"current_stock"` // 当前库存
		SafetyStock  float64 `db:"safety_stock"`  // 安全库存
		LockedStock  float64 `db:"locked_stock"`  // 锁定库存
	}
)

func newInventoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultInventoryModel {
	return &defaultInventoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`inventory`",
	}
}

func (m *defaultInventoryModel) Delete(ctx context.Context, inventoryId int64) error {
	data, err := m.FindOne(ctx, inventoryId)
	if err != nil {
		return err
	}

	erpInventoryInventoryInventoryIdKey := fmt.Sprintf("%s%v", cacheErpInventoryInventoryInventoryIdPrefix, inventoryId)
	erpInventoryInventoryProductIdWarehouseIdKey := fmt.Sprintf("%s%v:%v", cacheErpInventoryInventoryProductIdWarehouseIdPrefix, data.ProductId, data.WarehouseId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `inventory_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, inventoryId)
	}, erpInventoryInventoryInventoryIdKey, erpInventoryInventoryProductIdWarehouseIdKey)
	return err
}

func (m *defaultInventoryModel) FindOne(ctx context.Context, inventoryId int64) (*Inventory, error) {
	erpInventoryInventoryInventoryIdKey := fmt.Sprintf("%s%v", cacheErpInventoryInventoryInventoryIdPrefix, inventoryId)
	var resp Inventory
	err := m.QueryRowCtx(ctx, &resp, erpInventoryInventoryInventoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `inventory_id` = ? limit 1", inventoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, inventoryId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInventoryModel) FindOneByProductIdWarehouseId(ctx context.Context, productId int64, warehouseId int64) (*Inventory, error) {
	erpInventoryInventoryProductIdWarehouseIdKey := fmt.Sprintf("%s%v:%v", cacheErpInventoryInventoryProductIdWarehouseIdPrefix, productId, warehouseId)
	var resp Inventory
	err := m.QueryRowIndexCtx(ctx, &resp, erpInventoryInventoryProductIdWarehouseIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `product_id` = ? and `warehouse_id` = ? limit 1", inventoryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, productId, warehouseId); err != nil {
			return nil, err
		}
		return resp.InventoryId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInventoryModel) Insert(ctx context.Context, data *Inventory) (sql.Result, error) {
	erpInventoryInventoryInventoryIdKey := fmt.Sprintf("%s%v", cacheErpInventoryInventoryInventoryIdPrefix, data.InventoryId)
	erpInventoryInventoryProductIdWarehouseIdKey := fmt.Sprintf("%s%v:%v", cacheErpInventoryInventoryProductIdWarehouseIdPrefix, data.ProductId, data.WarehouseId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, inventoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.InventoryId, data.ProductId, data.WarehouseId, data.CurrentStock, data.SafetyStock, data.LockedStock)
	}, erpInventoryInventoryInventoryIdKey, erpInventoryInventoryProductIdWarehouseIdKey)
	return ret, err
}

func (m *defaultInventoryModel) Update(ctx context.Context, newData *Inventory) error {
	data, err := m.FindOne(ctx, newData.InventoryId)
	if err != nil {
		return err
	}

	erpInventoryInventoryInventoryIdKey := fmt.Sprintf("%s%v", cacheErpInventoryInventoryInventoryIdPrefix, data.InventoryId)
	erpInventoryInventoryProductIdWarehouseIdKey := fmt.Sprintf("%s%v:%v", cacheErpInventoryInventoryProductIdWarehouseIdPrefix, data.ProductId, data.WarehouseId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `inventory_id` = ?", m.table, inventoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ProductId, newData.WarehouseId, newData.CurrentStock, newData.SafetyStock, newData.LockedStock, newData.InventoryId)
	}, erpInventoryInventoryInventoryIdKey, erpInventoryInventoryProductIdWarehouseIdKey)
	return err
}

func (m *defaultInventoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpInventoryInventoryInventoryIdPrefix, primary)
}

func (m *defaultInventoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `inventory_id` = ? limit 1", inventoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultInventoryModel) tableName() string {
	return m.table
}
