// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: purchase.proto

package purchaserequisition

import (
	"context"

	"erp/app/purchase/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApproveRequisitionReq            = pb.ApproveRequisitionReq
	ApproveRequisitionResp           = pb.ApproveRequisitionResp
	CancelPurchaseOrderReq           = pb.CancelPurchaseOrderReq
	CancelPurchaseOrderResp          = pb.CancelPurchaseOrderResp
	CreateOrderFromRequisitionReq    = pb.CreateOrderFromRequisitionReq
	CreateOrderFromRequisitionResp   = pb.CreateOrderFromRequisitionResp
	CreateOrderWithDetailsReq        = pb.CreateOrderWithDetailsReq
	CreateOrderWithDetailsResp       = pb.CreateOrderWithDetailsResp
	CreateReceiptFromOrderReq        = pb.CreateReceiptFromOrderReq
	CreateReceiptFromOrderResp       = pb.CreateReceiptFromOrderResp
	CreateReceiptWithDetailsReq      = pb.CreateReceiptWithDetailsReq
	CreateReceiptWithDetailsResp     = pb.CreateReceiptWithDetailsResp
	CreateRequisitionWithDetailsReq  = pb.CreateRequisitionWithDetailsReq
	CreateRequisitionWithDetailsResp = pb.CreateRequisitionWithDetailsResp
	GetOrderWithDetailsReq           = pb.GetOrderWithDetailsReq
	GetOrderWithDetailsResp          = pb.GetOrderWithDetailsResp
	GetReceiptWithDetailsReq         = pb.GetReceiptWithDetailsReq
	GetReceiptWithDetailsResp        = pb.GetReceiptWithDetailsResp
	GetRequisitionWithDetailsReq     = pb.GetRequisitionWithDetailsReq
	GetRequisitionWithDetailsResp    = pb.GetRequisitionWithDetailsResp
	OrderDetailInput                 = pb.OrderDetailInput
	PurchaseOrder                    = pb.PurchaseOrder
	PurchaseOrderDetail              = pb.PurchaseOrderDetail
	PurchaseOrderWithDetails         = pb.PurchaseOrderWithDetails
	PurchaseReceipt                  = pb.PurchaseReceipt
	PurchaseReceiptDetail            = pb.PurchaseReceiptDetail
	PurchaseReceiptWithDetails       = pb.PurchaseReceiptWithDetails
	PurchaseRequisition              = pb.PurchaseRequisition
	PurchaseRequisitionDetail        = pb.PurchaseRequisitionDetail
	PurchaseRequisitionWithDetails   = pb.PurchaseRequisitionWithDetails
	ReceiptDetailInput               = pb.ReceiptDetailInput
	RequisitionDetailInput           = pb.RequisitionDetailInput
	SearchOrderReq                   = pb.SearchOrderReq
	SearchOrderResp                  = pb.SearchOrderResp
	SearchReceiptReq                 = pb.SearchReceiptReq
	SearchReceiptResp                = pb.SearchReceiptResp
	SearchRequisitionReq             = pb.SearchRequisitionReq
	SearchRequisitionResp            = pb.SearchRequisitionResp
	UpdateOrderDetailReq             = pb.UpdateOrderDetailReq
	UpdateOrderDetailResp            = pb.UpdateOrderDetailResp
	UpdateOrderReq                   = pb.UpdateOrderReq
	UpdateOrderResp                  = pb.UpdateOrderResp
	UpdateReceiptDetailReq           = pb.UpdateReceiptDetailReq
	UpdateReceiptDetailResp          = pb.UpdateReceiptDetailResp
	UpdateReceiptReq                 = pb.UpdateReceiptReq
	UpdateReceiptResp                = pb.UpdateReceiptResp
	UpdateRequisitionDetailReq       = pb.UpdateRequisitionDetailReq
	UpdateRequisitionDetailResp      = pb.UpdateRequisitionDetailResp
	UpdateRequisitionReq             = pb.UpdateRequisitionReq
	UpdateRequisitionResp            = pb.UpdateRequisitionResp

	PurchaseRequisitionZrpcClient interface {
		// 创建采购申请及明细（事务）
		CreateRequisitionWithDetails(ctx context.Context, in *CreateRequisitionWithDetailsReq, opts ...grpc.CallOption) (*CreateRequisitionWithDetailsResp, error)
		// 审批采购申请
		ApproveRequisition(ctx context.Context, in *ApproveRequisitionReq, opts ...grpc.CallOption) (*ApproveRequisitionResp, error)
		// 获取采购申请及明细
		GetRequisitionWithDetails(ctx context.Context, in *GetRequisitionWithDetailsReq, opts ...grpc.CallOption) (*GetRequisitionWithDetailsResp, error)
		// 查询采购申请
		SearchRequisition(ctx context.Context, in *SearchRequisitionReq, opts ...grpc.CallOption) (*SearchRequisitionResp, error)
		// 更新采购申请（动态SQL拼接）
		UpdateRequisition(ctx context.Context, in *UpdateRequisitionReq, opts ...grpc.CallOption) (*UpdateRequisitionResp, error)
		// 更新采购申请明细（动态SQL拼接）
		UpdateRequisitionDetail(ctx context.Context, in *UpdateRequisitionDetailReq, opts ...grpc.CallOption) (*UpdateRequisitionDetailResp, error)
	}

	defaultPurchaseRequisitionZrpcClient struct {
		cli zrpc.Client
	}
)

func NewPurchaseRequisitionZrpcClient(cli zrpc.Client) PurchaseRequisitionZrpcClient {
	return &defaultPurchaseRequisitionZrpcClient{
		cli: cli,
	}
}

// 创建采购申请及明细（事务）
func (m *defaultPurchaseRequisitionZrpcClient) CreateRequisitionWithDetails(ctx context.Context, in *CreateRequisitionWithDetailsReq, opts ...grpc.CallOption) (*CreateRequisitionWithDetailsResp, error) {
	client := pb.NewPurchaseRequisitionClient(m.cli.Conn())
	return client.CreateRequisitionWithDetails(ctx, in, opts...)
}

// 审批采购申请
func (m *defaultPurchaseRequisitionZrpcClient) ApproveRequisition(ctx context.Context, in *ApproveRequisitionReq, opts ...grpc.CallOption) (*ApproveRequisitionResp, error) {
	client := pb.NewPurchaseRequisitionClient(m.cli.Conn())
	return client.ApproveRequisition(ctx, in, opts...)
}

// 获取采购申请及明细
func (m *defaultPurchaseRequisitionZrpcClient) GetRequisitionWithDetails(ctx context.Context, in *GetRequisitionWithDetailsReq, opts ...grpc.CallOption) (*GetRequisitionWithDetailsResp, error) {
	client := pb.NewPurchaseRequisitionClient(m.cli.Conn())
	return client.GetRequisitionWithDetails(ctx, in, opts...)
}

// 查询采购申请
func (m *defaultPurchaseRequisitionZrpcClient) SearchRequisition(ctx context.Context, in *SearchRequisitionReq, opts ...grpc.CallOption) (*SearchRequisitionResp, error) {
	client := pb.NewPurchaseRequisitionClient(m.cli.Conn())
	return client.SearchRequisition(ctx, in, opts...)
}

// 更新采购申请（动态SQL拼接）
func (m *defaultPurchaseRequisitionZrpcClient) UpdateRequisition(ctx context.Context, in *UpdateRequisitionReq, opts ...grpc.CallOption) (*UpdateRequisitionResp, error) {
	client := pb.NewPurchaseRequisitionClient(m.cli.Conn())
	return client.UpdateRequisition(ctx, in, opts...)
}

// 更新采购申请明细（动态SQL拼接）
func (m *defaultPurchaseRequisitionZrpcClient) UpdateRequisitionDetail(ctx context.Context, in *UpdateRequisitionDetailReq, opts ...grpc.CallOption) (*UpdateRequisitionDetailResp, error) {
	client := pb.NewPurchaseRequisitionClient(m.cli.Conn())
	return client.UpdateRequisitionDetail(ctx, in, opts...)
}
