// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: purchase.proto

package server

import (
	"context"

	"erp/app/purchase/rpc/internal/logic/purchaserequisition"
	"erp/app/purchase/rpc/internal/svc"
	"erp/app/purchase/rpc/pb"
)

type PurchaseRequisitionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPurchaseRequisitionServer
}

func NewPurchaseRequisitionServer(svcCtx *svc.ServiceContext) *PurchaseRequisitionServer {
	return &PurchaseRequisitionServer{
		svcCtx: svcCtx,
	}
}

// 创建采购申请及明细（事务）
func (s *PurchaseRequisitionServer) CreateRequisitionWithDetails(ctx context.Context, in *pb.CreateRequisitionWithDetailsReq) (*pb.CreateRequisitionWithDetailsResp, error) {
	l := purchaserequisitionlogic.NewCreateRequisitionWithDetailsLogic(ctx, s.svcCtx)
	return l.CreateRequisitionWithDetails(in)
}

// 审批采购申请
func (s *PurchaseRequisitionServer) ApproveRequisition(ctx context.Context, in *pb.ApproveRequisitionReq) (*pb.ApproveRequisitionResp, error) {
	l := purchaserequisitionlogic.NewApproveRequisitionLogic(ctx, s.svcCtx)
	return l.ApproveRequisition(in)
}

// 获取采购申请及明细
func (s *PurchaseRequisitionServer) GetRequisitionWithDetails(ctx context.Context, in *pb.GetRequisitionWithDetailsReq) (*pb.GetRequisitionWithDetailsResp, error) {
	l := purchaserequisitionlogic.NewGetRequisitionWithDetailsLogic(ctx, s.svcCtx)
	return l.GetRequisitionWithDetails(in)
}

// 查询采购申请
func (s *PurchaseRequisitionServer) SearchRequisition(ctx context.Context, in *pb.SearchRequisitionReq) (*pb.SearchRequisitionResp, error) {
	l := purchaserequisitionlogic.NewSearchRequisitionLogic(ctx, s.svcCtx)
	return l.SearchRequisition(in)
}

// 更新采购申请（动态SQL拼接）
func (s *PurchaseRequisitionServer) UpdateRequisition(ctx context.Context, in *pb.UpdateRequisitionReq) (*pb.UpdateRequisitionResp, error) {
	l := purchaserequisitionlogic.NewUpdateRequisitionLogic(ctx, s.svcCtx)
	return l.UpdateRequisition(in)
}

// 更新采购申请明细（动态SQL拼接）
func (s *PurchaseRequisitionServer) UpdateRequisitionDetail(ctx context.Context, in *pb.UpdateRequisitionDetailReq) (*pb.UpdateRequisitionDetailResp, error) {
	l := purchaserequisitionlogic.NewUpdateRequisitionDetailLogic(ctx, s.svcCtx)
	return l.UpdateRequisitionDetail(in)
}
