// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: xAuth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Permission_GetAllPermissions_FullMethodName = "/pb.permission/GetAllPermissions"
)

// PermissionClient is the client API for Permission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionClient interface {
	// -----------------------permission-----------------------
	//
	//	rpc AddPermission(AddPermissionReq) returns (AddPermissionResp);
	//	rpc UpdatePermission(UpdatePermissionReq) returns (UpdatePermissionResp);
	//	rpc DelPermission(DelPermissionReq) returns (DelPermissionResp);
	//	rpc GetPermissionById(GetPermissionByIdReq) returns (GetPermissionByIdResp);
	//	rpc SearchPermission(SearchPermissionReq) returns (SearchPermissionResp);
	GetAllPermissions(ctx context.Context, in *GetAllPermissionsReq, opts ...grpc.CallOption) (*GetAllPermissionsResp, error)
}

type permissionClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionClient(cc grpc.ClientConnInterface) PermissionClient {
	return &permissionClient{cc}
}

func (c *permissionClient) GetAllPermissions(ctx context.Context, in *GetAllPermissionsReq, opts ...grpc.CallOption) (*GetAllPermissionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPermissionsResp)
	err := c.cc.Invoke(ctx, Permission_GetAllPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionServer is the server API for Permission service.
// All implementations must embed UnimplementedPermissionServer
// for forward compatibility.
type PermissionServer interface {
	// -----------------------permission-----------------------
	//
	//	rpc AddPermission(AddPermissionReq) returns (AddPermissionResp);
	//	rpc UpdatePermission(UpdatePermissionReq) returns (UpdatePermissionResp);
	//	rpc DelPermission(DelPermissionReq) returns (DelPermissionResp);
	//	rpc GetPermissionById(GetPermissionByIdReq) returns (GetPermissionByIdResp);
	//	rpc SearchPermission(SearchPermissionReq) returns (SearchPermissionResp);
	GetAllPermissions(context.Context, *GetAllPermissionsReq) (*GetAllPermissionsResp, error)
	mustEmbedUnimplementedPermissionServer()
}

// UnimplementedPermissionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermissionServer struct{}

func (UnimplementedPermissionServer) GetAllPermissions(context.Context, *GetAllPermissionsReq) (*GetAllPermissionsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPermissions not implemented")
}
func (UnimplementedPermissionServer) mustEmbedUnimplementedPermissionServer() {}
func (UnimplementedPermissionServer) testEmbeddedByValue()                    {}

// UnsafePermissionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionServer will
// result in compilation errors.
type UnsafePermissionServer interface {
	mustEmbedUnimplementedPermissionServer()
}

func RegisterPermissionServer(s grpc.ServiceRegistrar, srv PermissionServer) {
	// If the following call pancis, it indicates UnimplementedPermissionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Permission_ServiceDesc, srv)
}

func _Permission_GetAllPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).GetAllPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_GetAllPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).GetAllPermissions(ctx, req.(*GetAllPermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Permission_ServiceDesc is the grpc.ServiceDesc for Permission service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Permission_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.permission",
	HandlerType: (*PermissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllPermissions",
			Handler:    _Permission_GetAllPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xAuth.proto",
}

const (
	Role_AddRole_FullMethodName     = "/pb.role/AddRole"
	Role_UpdateRole_FullMethodName  = "/pb.role/UpdateRole"
	Role_DelRole_FullMethodName     = "/pb.role/DelRole"
	Role_GetRoleById_FullMethodName = "/pb.role/GetRoleById"
	Role_SearchRole_FullMethodName  = "/pb.role/SearchRole"
)

// RoleClient is the client API for Role service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoleClient interface {
	// -----------------------role-----------------------
	AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleResp, error)
	UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error)
	DelRole(ctx context.Context, in *DelRoleReq, opts ...grpc.CallOption) (*DelRoleResp, error)
	GetRoleById(ctx context.Context, in *GetRoleByIdReq, opts ...grpc.CallOption) (*GetRoleByIdResp, error)
	SearchRole(ctx context.Context, in *SearchRoleReq, opts ...grpc.CallOption) (*SearchRoleResp, error)
}

type roleClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleClient(cc grpc.ClientConnInterface) RoleClient {
	return &roleClient{cc}
}

func (c *roleClient) AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRoleResp)
	err := c.cc.Invoke(ctx, Role_AddRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoleResp)
	err := c.cc.Invoke(ctx, Role_UpdateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) DelRole(ctx context.Context, in *DelRoleReq, opts ...grpc.CallOption) (*DelRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelRoleResp)
	err := c.cc.Invoke(ctx, Role_DelRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) GetRoleById(ctx context.Context, in *GetRoleByIdReq, opts ...grpc.CallOption) (*GetRoleByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleByIdResp)
	err := c.cc.Invoke(ctx, Role_GetRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) SearchRole(ctx context.Context, in *SearchRoleReq, opts ...grpc.CallOption) (*SearchRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchRoleResp)
	err := c.cc.Invoke(ctx, Role_SearchRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServer is the server API for Role service.
// All implementations must embed UnimplementedRoleServer
// for forward compatibility.
type RoleServer interface {
	// -----------------------role-----------------------
	AddRole(context.Context, *AddRoleReq) (*AddRoleResp, error)
	UpdateRole(context.Context, *UpdateRoleReq) (*UpdateRoleResp, error)
	DelRole(context.Context, *DelRoleReq) (*DelRoleResp, error)
	GetRoleById(context.Context, *GetRoleByIdReq) (*GetRoleByIdResp, error)
	SearchRole(context.Context, *SearchRoleReq) (*SearchRoleResp, error)
	mustEmbedUnimplementedRoleServer()
}

// UnimplementedRoleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoleServer struct{}

func (UnimplementedRoleServer) AddRole(context.Context, *AddRoleReq) (*AddRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRole not implemented")
}
func (UnimplementedRoleServer) UpdateRole(context.Context, *UpdateRoleReq) (*UpdateRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedRoleServer) DelRole(context.Context, *DelRoleReq) (*DelRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelRole not implemented")
}
func (UnimplementedRoleServer) GetRoleById(context.Context, *GetRoleByIdReq) (*GetRoleByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleById not implemented")
}
func (UnimplementedRoleServer) SearchRole(context.Context, *SearchRoleReq) (*SearchRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchRole not implemented")
}
func (UnimplementedRoleServer) mustEmbedUnimplementedRoleServer() {}
func (UnimplementedRoleServer) testEmbeddedByValue()              {}

// UnsafeRoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleServer will
// result in compilation errors.
type UnsafeRoleServer interface {
	mustEmbedUnimplementedRoleServer()
}

func RegisterRoleServer(s grpc.ServiceRegistrar, srv RoleServer) {
	// If the following call pancis, it indicates UnimplementedRoleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Role_ServiceDesc, srv)
}

func _Role_AddRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).AddRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_AddRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).AddRole(ctx, req.(*AddRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).UpdateRole(ctx, req.(*UpdateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_DelRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).DelRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_DelRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).DelRole(ctx, req.(*DelRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_GetRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).GetRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_GetRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).GetRoleById(ctx, req.(*GetRoleByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_SearchRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).SearchRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_SearchRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).SearchRole(ctx, req.(*SearchRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Role_ServiceDesc is the grpc.ServiceDesc for Role service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Role_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.role",
	HandlerType: (*RoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRole",
			Handler:    _Role_AddRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _Role_UpdateRole_Handler,
		},
		{
			MethodName: "DelRole",
			Handler:    _Role_DelRole_Handler,
		},
		{
			MethodName: "GetRoleById",
			Handler:    _Role_GetRoleById_Handler,
		},
		{
			MethodName: "SearchRole",
			Handler:    _Role_SearchRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xAuth.proto",
}

const (
	RolePermission_AddRolePermission_FullMethodName         = "/pb.rolePermission/AddRolePermission"
	RolePermission_DelRolePermission_FullMethodName         = "/pb.rolePermission/DelRolePermission"
	RolePermission_GetRolePermissionByRoleId_FullMethodName = "/pb.rolePermission/GetRolePermissionByRoleId"
	RolePermission_SearchRolePermission_FullMethodName      = "/pb.rolePermission/SearchRolePermission"
)

// RolePermissionClient is the client API for RolePermission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RolePermissionClient interface {
	// -----------------------rolePermission-----------------------
	AddRolePermission(ctx context.Context, in *AddRolePermissionReq, opts ...grpc.CallOption) (*AddRolePermissionResp, error)
	DelRolePermission(ctx context.Context, in *DelRolePermissionReq, opts ...grpc.CallOption) (*DelRolePermissionResp, error)
	GetRolePermissionByRoleId(ctx context.Context, in *GetRolePermissionByRoleIdReq, opts ...grpc.CallOption) (*GetRolePermissionByRoleIdResp, error)
	SearchRolePermission(ctx context.Context, in *SearchRolePermissionReq, opts ...grpc.CallOption) (*SearchRolePermissionResp, error)
}

type rolePermissionClient struct {
	cc grpc.ClientConnInterface
}

func NewRolePermissionClient(cc grpc.ClientConnInterface) RolePermissionClient {
	return &rolePermissionClient{cc}
}

func (c *rolePermissionClient) AddRolePermission(ctx context.Context, in *AddRolePermissionReq, opts ...grpc.CallOption) (*AddRolePermissionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRolePermissionResp)
	err := c.cc.Invoke(ctx, RolePermission_AddRolePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePermissionClient) DelRolePermission(ctx context.Context, in *DelRolePermissionReq, opts ...grpc.CallOption) (*DelRolePermissionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelRolePermissionResp)
	err := c.cc.Invoke(ctx, RolePermission_DelRolePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePermissionClient) GetRolePermissionByRoleId(ctx context.Context, in *GetRolePermissionByRoleIdReq, opts ...grpc.CallOption) (*GetRolePermissionByRoleIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolePermissionByRoleIdResp)
	err := c.cc.Invoke(ctx, RolePermission_GetRolePermissionByRoleId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePermissionClient) SearchRolePermission(ctx context.Context, in *SearchRolePermissionReq, opts ...grpc.CallOption) (*SearchRolePermissionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchRolePermissionResp)
	err := c.cc.Invoke(ctx, RolePermission_SearchRolePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolePermissionServer is the server API for RolePermission service.
// All implementations must embed UnimplementedRolePermissionServer
// for forward compatibility.
type RolePermissionServer interface {
	// -----------------------rolePermission-----------------------
	AddRolePermission(context.Context, *AddRolePermissionReq) (*AddRolePermissionResp, error)
	DelRolePermission(context.Context, *DelRolePermissionReq) (*DelRolePermissionResp, error)
	GetRolePermissionByRoleId(context.Context, *GetRolePermissionByRoleIdReq) (*GetRolePermissionByRoleIdResp, error)
	SearchRolePermission(context.Context, *SearchRolePermissionReq) (*SearchRolePermissionResp, error)
	mustEmbedUnimplementedRolePermissionServer()
}

// UnimplementedRolePermissionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRolePermissionServer struct{}

func (UnimplementedRolePermissionServer) AddRolePermission(context.Context, *AddRolePermissionReq) (*AddRolePermissionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRolePermission not implemented")
}
func (UnimplementedRolePermissionServer) DelRolePermission(context.Context, *DelRolePermissionReq) (*DelRolePermissionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelRolePermission not implemented")
}
func (UnimplementedRolePermissionServer) GetRolePermissionByRoleId(context.Context, *GetRolePermissionByRoleIdReq) (*GetRolePermissionByRoleIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRolePermissionByRoleId not implemented")
}
func (UnimplementedRolePermissionServer) SearchRolePermission(context.Context, *SearchRolePermissionReq) (*SearchRolePermissionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchRolePermission not implemented")
}
func (UnimplementedRolePermissionServer) mustEmbedUnimplementedRolePermissionServer() {}
func (UnimplementedRolePermissionServer) testEmbeddedByValue()                        {}

// UnsafeRolePermissionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RolePermissionServer will
// result in compilation errors.
type UnsafeRolePermissionServer interface {
	mustEmbedUnimplementedRolePermissionServer()
}

func RegisterRolePermissionServer(s grpc.ServiceRegistrar, srv RolePermissionServer) {
	// If the following call pancis, it indicates UnimplementedRolePermissionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RolePermission_ServiceDesc, srv)
}

func _RolePermission_AddRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRolePermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionServer).AddRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermission_AddRolePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionServer).AddRolePermission(ctx, req.(*AddRolePermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePermission_DelRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRolePermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionServer).DelRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermission_DelRolePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionServer).DelRolePermission(ctx, req.(*DelRolePermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePermission_GetRolePermissionByRoleId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionByRoleIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionServer).GetRolePermissionByRoleId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermission_GetRolePermissionByRoleId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionServer).GetRolePermissionByRoleId(ctx, req.(*GetRolePermissionByRoleIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePermission_SearchRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRolePermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionServer).SearchRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermission_SearchRolePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionServer).SearchRolePermission(ctx, req.(*SearchRolePermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RolePermission_ServiceDesc is the grpc.ServiceDesc for RolePermission service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RolePermission_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.rolePermission",
	HandlerType: (*RolePermissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRolePermission",
			Handler:    _RolePermission_AddRolePermission_Handler,
		},
		{
			MethodName: "DelRolePermission",
			Handler:    _RolePermission_DelRolePermission_Handler,
		},
		{
			MethodName: "GetRolePermissionByRoleId",
			Handler:    _RolePermission_GetRolePermissionByRoleId_Handler,
		},
		{
			MethodName: "SearchRolePermission",
			Handler:    _RolePermission_SearchRolePermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xAuth.proto",
}

const (
	UserRole_AddUserRole_FullMethodName         = "/pb.userRole/AddUserRole"
	UserRole_UpdateUserRole_FullMethodName      = "/pb.userRole/UpdateUserRole"
	UserRole_DelUserRole_FullMethodName         = "/pb.userRole/DelUserRole"
	UserRole_DelUserRoleByUserId_FullMethodName = "/pb.userRole/DelUserRoleByUserId"
	UserRole_GetUserRoleByUserId_FullMethodName = "/pb.userRole/GetUserRoleByUserId"
	UserRole_SearchUserRole_FullMethodName      = "/pb.userRole/SearchUserRole"
)

// UserRoleClient is the client API for UserRole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRoleClient interface {
	// -----------------------userRole-----------------------
	AddUserRole(ctx context.Context, in *AddUserRoleReq, opts ...grpc.CallOption) (*AddUserRoleResp, error)
	UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*UpdateUserRoleResp, error)
	DelUserRole(ctx context.Context, in *DelUserRoleReq, opts ...grpc.CallOption) (*DelUserRoleResp, error)
	DelUserRoleByUserId(ctx context.Context, in *DelUserRoleByUserIdReq, opts ...grpc.CallOption) (*DelUserRoleByUserIdReq, error)
	GetUserRoleByUserId(ctx context.Context, in *GetUserRoleByUserIdReq, opts ...grpc.CallOption) (*GetUserRoleByUserIdResp, error)
	SearchUserRole(ctx context.Context, in *SearchUserRoleReq, opts ...grpc.CallOption) (*SearchUserRoleResp, error)
}

type userRoleClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRoleClient(cc grpc.ClientConnInterface) UserRoleClient {
	return &userRoleClient{cc}
}

func (c *userRoleClient) AddUserRole(ctx context.Context, in *AddUserRoleReq, opts ...grpc.CallOption) (*AddUserRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserRoleResp)
	err := c.cc.Invoke(ctx, UserRole_AddUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleClient) UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*UpdateUserRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserRoleResp)
	err := c.cc.Invoke(ctx, UserRole_UpdateUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleClient) DelUserRole(ctx context.Context, in *DelUserRoleReq, opts ...grpc.CallOption) (*DelUserRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelUserRoleResp)
	err := c.cc.Invoke(ctx, UserRole_DelUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleClient) DelUserRoleByUserId(ctx context.Context, in *DelUserRoleByUserIdReq, opts ...grpc.CallOption) (*DelUserRoleByUserIdReq, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelUserRoleByUserIdReq)
	err := c.cc.Invoke(ctx, UserRole_DelUserRoleByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleClient) GetUserRoleByUserId(ctx context.Context, in *GetUserRoleByUserIdReq, opts ...grpc.CallOption) (*GetUserRoleByUserIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRoleByUserIdResp)
	err := c.cc.Invoke(ctx, UserRole_GetUserRoleByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleClient) SearchUserRole(ctx context.Context, in *SearchUserRoleReq, opts ...grpc.CallOption) (*SearchUserRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUserRoleResp)
	err := c.cc.Invoke(ctx, UserRole_SearchUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRoleServer is the server API for UserRole service.
// All implementations must embed UnimplementedUserRoleServer
// for forward compatibility.
type UserRoleServer interface {
	// -----------------------userRole-----------------------
	AddUserRole(context.Context, *AddUserRoleReq) (*AddUserRoleResp, error)
	UpdateUserRole(context.Context, *UpdateUserRoleReq) (*UpdateUserRoleResp, error)
	DelUserRole(context.Context, *DelUserRoleReq) (*DelUserRoleResp, error)
	DelUserRoleByUserId(context.Context, *DelUserRoleByUserIdReq) (*DelUserRoleByUserIdReq, error)
	GetUserRoleByUserId(context.Context, *GetUserRoleByUserIdReq) (*GetUserRoleByUserIdResp, error)
	SearchUserRole(context.Context, *SearchUserRoleReq) (*SearchUserRoleResp, error)
	mustEmbedUnimplementedUserRoleServer()
}

// UnimplementedUserRoleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRoleServer struct{}

func (UnimplementedUserRoleServer) AddUserRole(context.Context, *AddUserRoleReq) (*AddUserRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserRole not implemented")
}
func (UnimplementedUserRoleServer) UpdateUserRole(context.Context, *UpdateUserRoleReq) (*UpdateUserRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserRole not implemented")
}
func (UnimplementedUserRoleServer) DelUserRole(context.Context, *DelUserRoleReq) (*DelUserRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelUserRole not implemented")
}
func (UnimplementedUserRoleServer) DelUserRoleByUserId(context.Context, *DelUserRoleByUserIdReq) (*DelUserRoleByUserIdReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelUserRoleByUserId not implemented")
}
func (UnimplementedUserRoleServer) GetUserRoleByUserId(context.Context, *GetUserRoleByUserIdReq) (*GetUserRoleByUserIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRoleByUserId not implemented")
}
func (UnimplementedUserRoleServer) SearchUserRole(context.Context, *SearchUserRoleReq) (*SearchUserRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserRole not implemented")
}
func (UnimplementedUserRoleServer) mustEmbedUnimplementedUserRoleServer() {}
func (UnimplementedUserRoleServer) testEmbeddedByValue()                  {}

// UnsafeUserRoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRoleServer will
// result in compilation errors.
type UnsafeUserRoleServer interface {
	mustEmbedUnimplementedUserRoleServer()
}

func RegisterUserRoleServer(s grpc.ServiceRegistrar, srv UserRoleServer) {
	// If the following call pancis, it indicates UnimplementedUserRoleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRole_ServiceDesc, srv)
}

func _UserRole_AddUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServer).AddUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRole_AddUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServer).AddUserRole(ctx, req.(*AddUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRole_UpdateUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServer).UpdateUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRole_UpdateUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServer).UpdateUserRole(ctx, req.(*UpdateUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRole_DelUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServer).DelUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRole_DelUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServer).DelUserRole(ctx, req.(*DelUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRole_DelUserRoleByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserRoleByUserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServer).DelUserRoleByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRole_DelUserRoleByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServer).DelUserRoleByUserId(ctx, req.(*DelUserRoleByUserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRole_GetUserRoleByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRoleByUserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServer).GetUserRoleByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRole_GetUserRoleByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServer).GetUserRoleByUserId(ctx, req.(*GetUserRoleByUserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRole_SearchUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServer).SearchUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRole_SearchUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServer).SearchUserRole(ctx, req.(*SearchUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRole_ServiceDesc is the grpc.ServiceDesc for UserRole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.userRole",
	HandlerType: (*UserRoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUserRole",
			Handler:    _UserRole_AddUserRole_Handler,
		},
		{
			MethodName: "UpdateUserRole",
			Handler:    _UserRole_UpdateUserRole_Handler,
		},
		{
			MethodName: "DelUserRole",
			Handler:    _UserRole_DelUserRole_Handler,
		},
		{
			MethodName: "DelUserRoleByUserId",
			Handler:    _UserRole_DelUserRoleByUserId_Handler,
		},
		{
			MethodName: "GetUserRoleByUserId",
			Handler:    _UserRole_GetUserRoleByUserId_Handler,
		},
		{
			MethodName: "SearchUserRole",
			Handler:    _UserRole_SearchUserRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xAuth.proto",
}
