// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: customer.proto

package server

import (
	"context"

	"erp/app/customer/rpc/internal/logic"
	"erp/app/customer/rpc/internal/svc"
	"erp/app/customer/rpc/pb"
)

type CustomerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCustomerServer
}

func NewCustomerServer(svcCtx *svc.ServiceContext) *CustomerServer {
	return &CustomerServer{
		svcCtx: svcCtx,
	}
}

// -----------------------customer-----------------------
func (s *CustomerServer) AddCustomer(ctx context.Context, in *pb.AddCustomerReq) (*pb.AddCustomerResp, error) {
	l := logic.NewAddCustomerLogic(ctx, s.svcCtx)
	return l.AddCustomer(in)
}

func (s *CustomerServer) UpdateCustomer(ctx context.Context, in *pb.UpdateCustomerReq) (*pb.UpdateCustomerResp, error) {
	l := logic.NewUpdateCustomerLogic(ctx, s.svcCtx)
	return l.UpdateCustomer(in)
}

// rpc DelCustomer(DelCustomerReq) returns (DelCustomerResp);
func (s *CustomerServer) GetCustomerById(ctx context.Context, in *pb.GetCustomerByIdReq) (*pb.GetCustomerByIdResp, error) {
	l := logic.NewGetCustomerByIdLogic(ctx, s.svcCtx)
	return l.GetCustomerById(in)
}

func (s *CustomerServer) GetCustomerByCode(ctx context.Context, in *pb.GetCustomerByCodeReq) (*pb.GetCustomerByCodeResp, error) {
	l := logic.NewGetCustomerByCodeLogic(ctx, s.svcCtx)
	return l.GetCustomerByCode(in)
}

func (s *CustomerServer) SearchCustomer(ctx context.Context, in *pb.SearchCustomerReq) (*pb.SearchCustomerResp, error) {
	l := logic.NewSearchCustomerLogic(ctx, s.svcCtx)
	return l.SearchCustomer(in)
}

// -----------------------customerCategory-----------------------
func (s *CustomerServer) AddCustomerCategory(ctx context.Context, in *pb.AddCustomerCategoryReq) (*pb.AddCustomerCategoryResp, error) {
	l := logic.NewAddCustomerCategoryLogic(ctx, s.svcCtx)
	return l.AddCustomerCategory(in)
}

func (s *CustomerServer) UpdateCustomerCategory(ctx context.Context, in *pb.UpdateCustomerCategoryReq) (*pb.UpdateCustomerCategoryResp, error) {
	l := logic.NewUpdateCustomerCategoryLogic(ctx, s.svcCtx)
	return l.UpdateCustomerCategory(in)
}

func (s *CustomerServer) DelCustomerCategory(ctx context.Context, in *pb.DelCustomerCategoryReq) (*pb.DelCustomerCategoryResp, error) {
	l := logic.NewDelCustomerCategoryLogic(ctx, s.svcCtx)
	return l.DelCustomerCategory(in)
}

func (s *CustomerServer) GetCustomerCategoryById(ctx context.Context, in *pb.GetCustomerCategoryByIdReq) (*pb.GetCustomerCategoryByIdResp, error) {
	l := logic.NewGetCustomerCategoryByIdLogic(ctx, s.svcCtx)
	return l.GetCustomerCategoryById(in)
}

func (s *CustomerServer) SearchCustomerCategory(ctx context.Context, in *pb.SearchCustomerCategoryReq) (*pb.SearchCustomerCategoryResp, error) {
	l := logic.NewSearchCustomerCategoryLogic(ctx, s.svcCtx)
	return l.SearchCustomerCategory(in)
}

// -----------------------customerSatisfactionSurvey-----------------------
func (s *CustomerServer) AddCustomerSatisfactionSurvey(ctx context.Context, in *pb.AddCustomerSatisfactionSurveyReq) (*pb.AddCustomerSatisfactionSurveyResp, error) {
	l := logic.NewAddCustomerSatisfactionSurveyLogic(ctx, s.svcCtx)
	return l.AddCustomerSatisfactionSurvey(in)
}

// rpc UpdateCustomerSatisfactionSurvey(UpdateCustomerSatisfactionSurveyReq) returns (UpdateCustomerSatisfactionSurveyResp);
func (s *CustomerServer) GetCustomerSatisfactionSurveyById(ctx context.Context, in *pb.GetCustomerSatisfactionSurveyByIdReq) (*pb.GetCustomerSatisfactionSurveyByIdResp, error) {
	l := logic.NewGetCustomerSatisfactionSurveyByIdLogic(ctx, s.svcCtx)
	return l.GetCustomerSatisfactionSurveyById(in)
}

func (s *CustomerServer) SearchCustomerSatisfactionSurvey(ctx context.Context, in *pb.SearchCustomerSatisfactionSurveyReq) (*pb.SearchCustomerSatisfactionSurveyResp, error) {
	l := logic.NewSearchCustomerSatisfactionSurveyLogic(ctx, s.svcCtx)
	return l.SearchCustomerSatisfactionSurvey(in)
}
