// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bomFieldNames          = builder.RawFieldNames(&Bom{})
	bomRows                = strings.Join(bomFieldNames, ",")
	bomRowsExpectAutoSet   = strings.Join(stringx.Remove(bomFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bomRowsWithPlaceHolder = strings.Join(stringx.Remove(bomFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpProductionBomIdPrefix    = "cache:erpProduction:bom:id:"
	cacheErpProductionBomBomNoPrefix = "cache:erpProduction:bom:bomNo:"
)

type (
	bomModel interface {
		Insert(ctx context.Context, data *Bom) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Bom, error)
		FindOneByBomNo(ctx context.Context, bomNo string) (*Bom, error)
		Update(ctx context.Context, data *Bom) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBomModel struct {
		sqlc.CachedConn
		table string
	}

	Bom struct {
		Id          int64          `db:"id"`           // BOM ID
		BomNo       string         `db:"bom_no"`       // BOM编号
		ProductId   int64          `db:"product_id"`   // 产品ID
		ProductName sql.NullString `db:"product_name"` // 产品名称
		Version     string         `db:"version"`      // BOM版本
		UnitCost    float64        `db:"unit_cost"`    // 单位成本
		IsActive    int64          `db:"is_active"`    // 是否启用：1-启用 2-停用
		Remark      sql.NullString `db:"remark"`       // 备注
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		CreatedBy   sql.NullInt64  `db:"created_by"`   // 创建人ID
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
		UpdatedBy   sql.NullInt64  `db:"updated_by"`   // 更新人ID
	}
)

func newBomModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBomModel {
	return &defaultBomModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bom`",
	}
}

func (m *defaultBomModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	erpProductionBomBomNoKey := fmt.Sprintf("%s%v", cacheErpProductionBomBomNoPrefix, data.BomNo)
	erpProductionBomIdKey := fmt.Sprintf("%s%v", cacheErpProductionBomIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpProductionBomBomNoKey, erpProductionBomIdKey)
	return err
}

func (m *defaultBomModel) FindOne(ctx context.Context, id int64) (*Bom, error) {
	erpProductionBomIdKey := fmt.Sprintf("%s%v", cacheErpProductionBomIdPrefix, id)
	var resp Bom
	err := m.QueryRowCtx(ctx, &resp, erpProductionBomIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bomRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBomModel) FindOneByBomNo(ctx context.Context, bomNo string) (*Bom, error) {
	erpProductionBomBomNoKey := fmt.Sprintf("%s%v", cacheErpProductionBomBomNoPrefix, bomNo)
	var resp Bom
	err := m.QueryRowIndexCtx(ctx, &resp, erpProductionBomBomNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `bom_no` = ? limit 1", bomRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, bomNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBomModel) Insert(ctx context.Context, data *Bom) (sql.Result, error) {
	erpProductionBomBomNoKey := fmt.Sprintf("%s%v", cacheErpProductionBomBomNoPrefix, data.BomNo)
	erpProductionBomIdKey := fmt.Sprintf("%s%v", cacheErpProductionBomIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, bomRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.BomNo, data.ProductId, data.ProductName, data.Version, data.UnitCost, data.IsActive, data.Remark, data.CreatedBy, data.UpdatedBy)
	}, erpProductionBomBomNoKey, erpProductionBomIdKey)
	return ret, err
}

func (m *defaultBomModel) Update(ctx context.Context, newData *Bom) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	erpProductionBomBomNoKey := fmt.Sprintf("%s%v", cacheErpProductionBomBomNoPrefix, data.BomNo)
	erpProductionBomIdKey := fmt.Sprintf("%s%v", cacheErpProductionBomIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bomRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.BomNo, newData.ProductId, newData.ProductName, newData.Version, newData.UnitCost, newData.IsActive, newData.Remark, newData.CreatedBy, newData.UpdatedBy, newData.Id)
	}, erpProductionBomBomNoKey, erpProductionBomIdKey)
	return err
}

func (m *defaultBomModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpProductionBomIdPrefix, primary)
}

func (m *defaultBomModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bomRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBomModel) tableName() string {
	return m.table
}
