// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	customerSatisfactionSurveyFieldNames          = builder.RawFieldNames(&CustomerSatisfactionSurvey{})
	customerSatisfactionSurveyRows                = strings.Join(customerSatisfactionSurveyFieldNames, ",")
	customerSatisfactionSurveyRowsExpectAutoSet   = strings.Join(stringx.Remove(customerSatisfactionSurveyFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	customerSatisfactionSurveyRowsWithPlaceHolder = strings.Join(stringx.Remove(customerSatisfactionSurveyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpCustomerCustomerSatisfactionSurveyIdPrefix = "cache:erpCustomer:customerSatisfactionSurvey:id:"
)

type (
	customerSatisfactionSurveyModel interface {
		Insert(ctx context.Context, data *CustomerSatisfactionSurvey) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CustomerSatisfactionSurvey, error)
		Update(ctx context.Context, data *CustomerSatisfactionSurvey) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCustomerSatisfactionSurveyModel struct {
		sqlc.CachedConn
		table string
	}

	CustomerSatisfactionSurvey struct {
		Id            int64          `db:"id"`             // 调查ID
		CustomerId    int64          `db:"customer_id"`    // 客户ID
		QualityScore  float64        `db:"quality_score"`  // 质量评分
		DeliveryScore float64        `db:"delivery_score"` // 交付评分
		ServiceScore  float64        `db:"service_score"`  // 服务评分
		OverallScore  float64        `db:"overall_score"`  // 综合评分
		Remark        sql.NullString `db:"remark"`         // 评价
		CreatedAt     time.Time      `db:"created_at"`     // 调查日期
		CreatedBy     int64          `db:"created_by"`     // 创建人ID
	}
)

func newCustomerSatisfactionSurveyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCustomerSatisfactionSurveyModel {
	return &defaultCustomerSatisfactionSurveyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`customer_satisfaction_survey`",
	}
}

func (m *defaultCustomerSatisfactionSurveyModel) Delete(ctx context.Context, id int64) error {
	erpCustomerCustomerSatisfactionSurveyIdKey := fmt.Sprintf("%s%v", cacheErpCustomerCustomerSatisfactionSurveyIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpCustomerCustomerSatisfactionSurveyIdKey)
	return err
}

func (m *defaultCustomerSatisfactionSurveyModel) FindOne(ctx context.Context, id int64) (*CustomerSatisfactionSurvey, error) {
	erpCustomerCustomerSatisfactionSurveyIdKey := fmt.Sprintf("%s%v", cacheErpCustomerCustomerSatisfactionSurveyIdPrefix, id)
	var resp CustomerSatisfactionSurvey
	err := m.QueryRowCtx(ctx, &resp, erpCustomerCustomerSatisfactionSurveyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", customerSatisfactionSurveyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerSatisfactionSurveyModel) Insert(ctx context.Context, data *CustomerSatisfactionSurvey) (sql.Result, error) {
	erpCustomerCustomerSatisfactionSurveyIdKey := fmt.Sprintf("%s%v", cacheErpCustomerCustomerSatisfactionSurveyIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, customerSatisfactionSurveyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.CustomerId, data.QualityScore, data.DeliveryScore, data.ServiceScore, data.OverallScore, data.Remark, data.CreatedBy)
	}, erpCustomerCustomerSatisfactionSurveyIdKey)
	return ret, err
}

func (m *defaultCustomerSatisfactionSurveyModel) Update(ctx context.Context, data *CustomerSatisfactionSurvey) error {
	erpCustomerCustomerSatisfactionSurveyIdKey := fmt.Sprintf("%s%v", cacheErpCustomerCustomerSatisfactionSurveyIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, customerSatisfactionSurveyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CustomerId, data.QualityScore, data.DeliveryScore, data.ServiceScore, data.OverallScore, data.Remark, data.CreatedBy, data.Id)
	}, erpCustomerCustomerSatisfactionSurveyIdKey)
	return err
}

func (m *defaultCustomerSatisfactionSurveyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpCustomerCustomerSatisfactionSurveyIdPrefix, primary)
}

func (m *defaultCustomerSatisfactionSurveyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", customerSatisfactionSurveyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCustomerSatisfactionSurveyModel) tableName() string {
	return m.table
}
