// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	attendance "erp/app/hr/api/internal/handler/attendance"
	attendanceReplenish "erp/app/hr/api/internal/handler/attendanceReplenish"
	department "erp/app/hr/api/internal/handler/department"
	employeeDetail "erp/app/hr/api/internal/handler/employeeDetail"
	leave "erp/app/hr/api/internal/handler/leave"
	payroll "erp/app/hr/api/internal/handler/payroll"
	position "erp/app/hr/api/internal/handler/position"
	resigned "erp/app/hr/api/internal/handler/resigned"
	"erp/app/hr/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: attendance.GetAttendanceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/clock",
					Handler: attendance.ClockHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/search",
					Handler: attendance.SearchAttendanceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/attendance"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: attendanceReplenish.SubmitReplenishHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: attendanceReplenish.GetReplenishHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/approve",
					Handler: attendanceReplenish.ApproveReplenishHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/search",
					Handler: attendanceReplenish.SearchAttendanceReplenishHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/attendanceReplenish"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: department.CreateDepartmentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: department.UpdateDepartmentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: department.DeleteDepartmentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: department.GetDepartmentDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: department.GetDepartmentListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tree",
					Handler: department.GetDepartmentTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/department"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: employeeDetail.CreateEmployeeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: employeeDetail.UpdateEmployeeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: employeeDetail.GetEmployeeDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/adjustSalary",
					Handler: employeeDetail.AdjustSalaryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/department",
					Handler: employeeDetail.GetDepartmentEmployeesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/import",
					Handler: employeeDetail.ImportEmployeeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: employeeDetail.SearchEmployeeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/employeeDetail"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: leave.SubmitLeaveHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: leave.GetLeaveDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/approve",
					Handler: leave.ApproveLeaveHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: leave.GetLeaveListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/leave"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: payroll.AddPayrollHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: payroll.GetPayrollsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/approve",
					Handler: payroll.ApprovePayrollHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/executePayment",
					Handler: payroll.ExecutePaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/search",
					Handler: payroll.SearchPayrollsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/submitToFinance",
					Handler: payroll.SubmitToFinanceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/payroll"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: position.CreatePositionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: position.UpdatePositionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: position.DeletePositionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: position.GetPositionDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/batch-assign",
					Handler: position.BatchAssignPositionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/employees",
					Handler: position.GetPositionEmployeesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: position.GetPositionListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/position"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: resigned.ApplyResignApplicationHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: resigned.UpdateResignedApplicationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: resigned.GetResignedApplicationByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: resigned.GetResignedApplicationListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/review",
					Handler: resigned.ReviewResignedApplicationHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/resigned"),
	)
}
