// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: xAuth.proto

package userrole

import (
	"context"

	"erp/app/auth/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRolePermissionReq           = pb.AddRolePermissionReq
	AddRolePermissionResp          = pb.AddRolePermissionResp
	AddRoleReq                     = pb.AddRoleReq
	AddRoleResp                    = pb.AddRoleResp
	AddUserRoleReq                 = pb.AddUserRoleReq
	AddUserRoleResp                = pb.AddUserRoleResp
	DelRolePermissionReq           = pb.DelRolePermissionReq
	DelRolePermissionResp          = pb.DelRolePermissionResp
	DelRoleReq                     = pb.DelRoleReq
	DelRoleResp                    = pb.DelRoleResp
	DelUserRoleByUserIdReq         = pb.DelUserRoleByUserIdReq
	DelUserRoleByUserIdResp        = pb.DelUserRoleByUserIdResp
	DelUserRoleReq                 = pb.DelUserRoleReq
	DelUserRoleResp                = pb.DelUserRoleResp
	GetAllPermissionsReq           = pb.GetAllPermissionsReq
	GetAllPermissionsResp          = pb.GetAllPermissionsResp
	GetRoleByIdReq                 = pb.GetRoleByIdReq
	GetRoleByIdResp                = pb.GetRoleByIdResp
	GetRolePermissionByRoleIdReq   = pb.GetRolePermissionByRoleIdReq
	GetRolePermissionByRoleIdResp  = pb.GetRolePermissionByRoleIdResp
	GetUserRoleByUserIdReq         = pb.GetUserRoleByUserIdReq
	GetUserRoleByUserIdResp        = pb.GetUserRoleByUserIdResp
	Permission                     = pb.Permission
	PermissionItem                 = pb.PermissionItem
	PermissionWithRolePermissionId = pb.PermissionWithRolePermissionId
	Role                           = pb.Role
	RoleAndPermissionDetails       = pb.RoleAndPermissionDetails
	RoleAndPermissions             = pb.RoleAndPermissions
	RolePermission                 = pb.RolePermission
	SearchRolePermissionReq        = pb.SearchRolePermissionReq
	SearchRolePermissionResp       = pb.SearchRolePermissionResp
	SearchRoleReq                  = pb.SearchRoleReq
	SearchRoleResp                 = pb.SearchRoleResp
	SearchUserRoleReq              = pb.SearchUserRoleReq
	SearchUserRoleResp             = pb.SearchUserRoleResp
	UpdateRolePermissionReq        = pb.UpdateRolePermissionReq
	UpdateRolePermissionResp       = pb.UpdateRolePermissionResp
	UpdateRoleReq                  = pb.UpdateRoleReq
	UpdateRoleResp                 = pb.UpdateRoleResp
	UpdateUserRoleReq              = pb.UpdateUserRoleReq
	UpdateUserRoleResp             = pb.UpdateUserRoleResp
	UserRole                       = pb.UserRole

	UserRoleZrpcClient interface {
		// -----------------------userRole-----------------------
		AddUserRole(ctx context.Context, in *AddUserRoleReq, opts ...grpc.CallOption) (*AddUserRoleResp, error)
		UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*UpdateUserRoleResp, error)
		DelUserRole(ctx context.Context, in *DelUserRoleReq, opts ...grpc.CallOption) (*DelUserRoleResp, error)
		DelUserRoleByUserId(ctx context.Context, in *DelUserRoleByUserIdReq, opts ...grpc.CallOption) (*DelUserRoleByUserIdReq, error)
		GetUserRoleByUserId(ctx context.Context, in *GetUserRoleByUserIdReq, opts ...grpc.CallOption) (*GetUserRoleByUserIdResp, error)
		SearchUserRole(ctx context.Context, in *SearchUserRoleReq, opts ...grpc.CallOption) (*SearchUserRoleResp, error)
	}

	defaultUserRoleZrpcClient struct {
		cli zrpc.Client
	}
)

func NewUserRoleZrpcClient(cli zrpc.Client) UserRoleZrpcClient {
	return &defaultUserRoleZrpcClient{
		cli: cli,
	}
}

// -----------------------userRole-----------------------
func (m *defaultUserRoleZrpcClient) AddUserRole(ctx context.Context, in *AddUserRoleReq, opts ...grpc.CallOption) (*AddUserRoleResp, error) {
	client := pb.NewUserRoleClient(m.cli.Conn())
	return client.AddUserRole(ctx, in, opts...)
}

func (m *defaultUserRoleZrpcClient) UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*UpdateUserRoleResp, error) {
	client := pb.NewUserRoleClient(m.cli.Conn())
	return client.UpdateUserRole(ctx, in, opts...)
}

func (m *defaultUserRoleZrpcClient) DelUserRole(ctx context.Context, in *DelUserRoleReq, opts ...grpc.CallOption) (*DelUserRoleResp, error) {
	client := pb.NewUserRoleClient(m.cli.Conn())
	return client.DelUserRole(ctx, in, opts...)
}

func (m *defaultUserRoleZrpcClient) DelUserRoleByUserId(ctx context.Context, in *DelUserRoleByUserIdReq, opts ...grpc.CallOption) (*DelUserRoleByUserIdReq, error) {
	client := pb.NewUserRoleClient(m.cli.Conn())
	return client.DelUserRoleByUserId(ctx, in, opts...)
}

func (m *defaultUserRoleZrpcClient) GetUserRoleByUserId(ctx context.Context, in *GetUserRoleByUserIdReq, opts ...grpc.CallOption) (*GetUserRoleByUserIdResp, error) {
	client := pb.NewUserRoleClient(m.cli.Conn())
	return client.GetUserRoleByUserId(ctx, in, opts...)
}

func (m *defaultUserRoleZrpcClient) SearchUserRole(ctx context.Context, in *SearchUserRoleReq, opts ...grpc.CallOption) (*SearchUserRoleResp, error) {
	client := pb.NewUserRoleClient(m.cli.Conn())
	return client.SearchUserRole(ctx, in, opts...)
}
