// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: customer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Customer_AddCustomer_FullMethodName                       = "/pb.customer/AddCustomer"
	Customer_UpdateCustomer_FullMethodName                    = "/pb.customer/UpdateCustomer"
	Customer_GetCustomerById_FullMethodName                   = "/pb.customer/GetCustomerById"
	Customer_GetCustomerByCode_FullMethodName                 = "/pb.customer/GetCustomerByCode"
	Customer_SearchCustomer_FullMethodName                    = "/pb.customer/SearchCustomer"
	Customer_AddCustomerCategory_FullMethodName               = "/pb.customer/AddCustomerCategory"
	Customer_UpdateCustomerCategory_FullMethodName            = "/pb.customer/UpdateCustomerCategory"
	Customer_DelCustomerCategory_FullMethodName               = "/pb.customer/DelCustomerCategory"
	Customer_GetCustomerCategoryById_FullMethodName           = "/pb.customer/GetCustomerCategoryById"
	Customer_SearchCustomerCategory_FullMethodName            = "/pb.customer/SearchCustomerCategory"
	Customer_AddCustomerSatisfactionSurvey_FullMethodName     = "/pb.customer/AddCustomerSatisfactionSurvey"
	Customer_GetCustomerSatisfactionSurveyById_FullMethodName = "/pb.customer/GetCustomerSatisfactionSurveyById"
	Customer_SearchCustomerSatisfactionSurvey_FullMethodName  = "/pb.customer/SearchCustomerSatisfactionSurvey"
)

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerClient interface {
	// -----------------------customer-----------------------
	AddCustomer(ctx context.Context, in *AddCustomerReq, opts ...grpc.CallOption) (*AddCustomerResp, error)
	UpdateCustomer(ctx context.Context, in *UpdateCustomerReq, opts ...grpc.CallOption) (*UpdateCustomerResp, error)
	// rpc DelCustomer(DelCustomerReq) returns (DelCustomerResp);
	GetCustomerById(ctx context.Context, in *GetCustomerByIdReq, opts ...grpc.CallOption) (*GetCustomerByIdResp, error)
	GetCustomerByCode(ctx context.Context, in *GetCustomerByCodeReq, opts ...grpc.CallOption) (*GetCustomerByCodeResp, error)
	SearchCustomer(ctx context.Context, in *SearchCustomerReq, opts ...grpc.CallOption) (*SearchCustomerResp, error)
	// -----------------------customerCategory-----------------------
	AddCustomerCategory(ctx context.Context, in *AddCustomerCategoryReq, opts ...grpc.CallOption) (*AddCustomerCategoryResp, error)
	UpdateCustomerCategory(ctx context.Context, in *UpdateCustomerCategoryReq, opts ...grpc.CallOption) (*UpdateCustomerCategoryResp, error)
	DelCustomerCategory(ctx context.Context, in *DelCustomerCategoryReq, opts ...grpc.CallOption) (*DelCustomerCategoryResp, error)
	GetCustomerCategoryById(ctx context.Context, in *GetCustomerCategoryByIdReq, opts ...grpc.CallOption) (*GetCustomerCategoryByIdResp, error)
	SearchCustomerCategory(ctx context.Context, in *SearchCustomerCategoryReq, opts ...grpc.CallOption) (*SearchCustomerCategoryResp, error)
	// -----------------------customerSatisfactionSurvey-----------------------
	AddCustomerSatisfactionSurvey(ctx context.Context, in *AddCustomerSatisfactionSurveyReq, opts ...grpc.CallOption) (*AddCustomerSatisfactionSurveyResp, error)
	// rpc UpdateCustomerSatisfactionSurvey(UpdateCustomerSatisfactionSurveyReq) returns (UpdateCustomerSatisfactionSurveyResp);
	// rpc DelCustomerSatisfactionSurvey(DelCustomerSatisfactionSurveyReq) returns (DelCustomerSatisfactionSurveyResp);
	GetCustomerSatisfactionSurveyById(ctx context.Context, in *GetCustomerSatisfactionSurveyByIdReq, opts ...grpc.CallOption) (*GetCustomerSatisfactionSurveyByIdResp, error)
	SearchCustomerSatisfactionSurvey(ctx context.Context, in *SearchCustomerSatisfactionSurveyReq, opts ...grpc.CallOption) (*SearchCustomerSatisfactionSurveyResp, error)
}

type customerClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerClient(cc grpc.ClientConnInterface) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) AddCustomer(ctx context.Context, in *AddCustomerReq, opts ...grpc.CallOption) (*AddCustomerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCustomerResp)
	err := c.cc.Invoke(ctx, Customer_AddCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) UpdateCustomer(ctx context.Context, in *UpdateCustomerReq, opts ...grpc.CallOption) (*UpdateCustomerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCustomerResp)
	err := c.cc.Invoke(ctx, Customer_UpdateCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCustomerById(ctx context.Context, in *GetCustomerByIdReq, opts ...grpc.CallOption) (*GetCustomerByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerByIdResp)
	err := c.cc.Invoke(ctx, Customer_GetCustomerById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCustomerByCode(ctx context.Context, in *GetCustomerByCodeReq, opts ...grpc.CallOption) (*GetCustomerByCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerByCodeResp)
	err := c.cc.Invoke(ctx, Customer_GetCustomerByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) SearchCustomer(ctx context.Context, in *SearchCustomerReq, opts ...grpc.CallOption) (*SearchCustomerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCustomerResp)
	err := c.cc.Invoke(ctx, Customer_SearchCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) AddCustomerCategory(ctx context.Context, in *AddCustomerCategoryReq, opts ...grpc.CallOption) (*AddCustomerCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCustomerCategoryResp)
	err := c.cc.Invoke(ctx, Customer_AddCustomerCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) UpdateCustomerCategory(ctx context.Context, in *UpdateCustomerCategoryReq, opts ...grpc.CallOption) (*UpdateCustomerCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCustomerCategoryResp)
	err := c.cc.Invoke(ctx, Customer_UpdateCustomerCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) DelCustomerCategory(ctx context.Context, in *DelCustomerCategoryReq, opts ...grpc.CallOption) (*DelCustomerCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelCustomerCategoryResp)
	err := c.cc.Invoke(ctx, Customer_DelCustomerCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCustomerCategoryById(ctx context.Context, in *GetCustomerCategoryByIdReq, opts ...grpc.CallOption) (*GetCustomerCategoryByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerCategoryByIdResp)
	err := c.cc.Invoke(ctx, Customer_GetCustomerCategoryById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) SearchCustomerCategory(ctx context.Context, in *SearchCustomerCategoryReq, opts ...grpc.CallOption) (*SearchCustomerCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCustomerCategoryResp)
	err := c.cc.Invoke(ctx, Customer_SearchCustomerCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) AddCustomerSatisfactionSurvey(ctx context.Context, in *AddCustomerSatisfactionSurveyReq, opts ...grpc.CallOption) (*AddCustomerSatisfactionSurveyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCustomerSatisfactionSurveyResp)
	err := c.cc.Invoke(ctx, Customer_AddCustomerSatisfactionSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCustomerSatisfactionSurveyById(ctx context.Context, in *GetCustomerSatisfactionSurveyByIdReq, opts ...grpc.CallOption) (*GetCustomerSatisfactionSurveyByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerSatisfactionSurveyByIdResp)
	err := c.cc.Invoke(ctx, Customer_GetCustomerSatisfactionSurveyById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) SearchCustomerSatisfactionSurvey(ctx context.Context, in *SearchCustomerSatisfactionSurveyReq, opts ...grpc.CallOption) (*SearchCustomerSatisfactionSurveyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCustomerSatisfactionSurveyResp)
	err := c.cc.Invoke(ctx, Customer_SearchCustomerSatisfactionSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServer is the server API for Customer service.
// All implementations must embed UnimplementedCustomerServer
// for forward compatibility.
type CustomerServer interface {
	// -----------------------customer-----------------------
	AddCustomer(context.Context, *AddCustomerReq) (*AddCustomerResp, error)
	UpdateCustomer(context.Context, *UpdateCustomerReq) (*UpdateCustomerResp, error)
	// rpc DelCustomer(DelCustomerReq) returns (DelCustomerResp);
	GetCustomerById(context.Context, *GetCustomerByIdReq) (*GetCustomerByIdResp, error)
	GetCustomerByCode(context.Context, *GetCustomerByCodeReq) (*GetCustomerByCodeResp, error)
	SearchCustomer(context.Context, *SearchCustomerReq) (*SearchCustomerResp, error)
	// -----------------------customerCategory-----------------------
	AddCustomerCategory(context.Context, *AddCustomerCategoryReq) (*AddCustomerCategoryResp, error)
	UpdateCustomerCategory(context.Context, *UpdateCustomerCategoryReq) (*UpdateCustomerCategoryResp, error)
	DelCustomerCategory(context.Context, *DelCustomerCategoryReq) (*DelCustomerCategoryResp, error)
	GetCustomerCategoryById(context.Context, *GetCustomerCategoryByIdReq) (*GetCustomerCategoryByIdResp, error)
	SearchCustomerCategory(context.Context, *SearchCustomerCategoryReq) (*SearchCustomerCategoryResp, error)
	// -----------------------customerSatisfactionSurvey-----------------------
	AddCustomerSatisfactionSurvey(context.Context, *AddCustomerSatisfactionSurveyReq) (*AddCustomerSatisfactionSurveyResp, error)
	// rpc UpdateCustomerSatisfactionSurvey(UpdateCustomerSatisfactionSurveyReq) returns (UpdateCustomerSatisfactionSurveyResp);
	// rpc DelCustomerSatisfactionSurvey(DelCustomerSatisfactionSurveyReq) returns (DelCustomerSatisfactionSurveyResp);
	GetCustomerSatisfactionSurveyById(context.Context, *GetCustomerSatisfactionSurveyByIdReq) (*GetCustomerSatisfactionSurveyByIdResp, error)
	SearchCustomerSatisfactionSurvey(context.Context, *SearchCustomerSatisfactionSurveyReq) (*SearchCustomerSatisfactionSurveyResp, error)
	mustEmbedUnimplementedCustomerServer()
}

// UnimplementedCustomerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerServer struct{}

func (UnimplementedCustomerServer) AddCustomer(context.Context, *AddCustomerReq) (*AddCustomerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCustomer not implemented")
}
func (UnimplementedCustomerServer) UpdateCustomer(context.Context, *UpdateCustomerReq) (*UpdateCustomerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomer not implemented")
}
func (UnimplementedCustomerServer) GetCustomerById(context.Context, *GetCustomerByIdReq) (*GetCustomerByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerById not implemented")
}
func (UnimplementedCustomerServer) GetCustomerByCode(context.Context, *GetCustomerByCodeReq) (*GetCustomerByCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerByCode not implemented")
}
func (UnimplementedCustomerServer) SearchCustomer(context.Context, *SearchCustomerReq) (*SearchCustomerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCustomer not implemented")
}
func (UnimplementedCustomerServer) AddCustomerCategory(context.Context, *AddCustomerCategoryReq) (*AddCustomerCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCustomerCategory not implemented")
}
func (UnimplementedCustomerServer) UpdateCustomerCategory(context.Context, *UpdateCustomerCategoryReq) (*UpdateCustomerCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomerCategory not implemented")
}
func (UnimplementedCustomerServer) DelCustomerCategory(context.Context, *DelCustomerCategoryReq) (*DelCustomerCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelCustomerCategory not implemented")
}
func (UnimplementedCustomerServer) GetCustomerCategoryById(context.Context, *GetCustomerCategoryByIdReq) (*GetCustomerCategoryByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerCategoryById not implemented")
}
func (UnimplementedCustomerServer) SearchCustomerCategory(context.Context, *SearchCustomerCategoryReq) (*SearchCustomerCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCustomerCategory not implemented")
}
func (UnimplementedCustomerServer) AddCustomerSatisfactionSurvey(context.Context, *AddCustomerSatisfactionSurveyReq) (*AddCustomerSatisfactionSurveyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCustomerSatisfactionSurvey not implemented")
}
func (UnimplementedCustomerServer) GetCustomerSatisfactionSurveyById(context.Context, *GetCustomerSatisfactionSurveyByIdReq) (*GetCustomerSatisfactionSurveyByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerSatisfactionSurveyById not implemented")
}
func (UnimplementedCustomerServer) SearchCustomerSatisfactionSurvey(context.Context, *SearchCustomerSatisfactionSurveyReq) (*SearchCustomerSatisfactionSurveyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCustomerSatisfactionSurvey not implemented")
}
func (UnimplementedCustomerServer) mustEmbedUnimplementedCustomerServer() {}
func (UnimplementedCustomerServer) testEmbeddedByValue()                  {}

// UnsafeCustomerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerServer will
// result in compilation errors.
type UnsafeCustomerServer interface {
	mustEmbedUnimplementedCustomerServer()
}

func RegisterCustomerServer(s grpc.ServiceRegistrar, srv CustomerServer) {
	// If the following call pancis, it indicates UnimplementedCustomerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Customer_ServiceDesc, srv)
}

func _Customer_AddCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCustomerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).AddCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_AddCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).AddCustomer(ctx, req.(*AddCustomerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_UpdateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).UpdateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_UpdateCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).UpdateCustomer(ctx, req.(*UpdateCustomerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCustomerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetCustomerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_GetCustomerById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetCustomerById(ctx, req.(*GetCustomerByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCustomerByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerByCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetCustomerByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_GetCustomerByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetCustomerByCode(ctx, req.(*GetCustomerByCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_SearchCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCustomerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).SearchCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_SearchCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).SearchCustomer(ctx, req.(*SearchCustomerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_AddCustomerCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCustomerCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).AddCustomerCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_AddCustomerCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).AddCustomerCategory(ctx, req.(*AddCustomerCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_UpdateCustomerCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomerCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).UpdateCustomerCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_UpdateCustomerCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).UpdateCustomerCategory(ctx, req.(*UpdateCustomerCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_DelCustomerCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelCustomerCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).DelCustomerCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_DelCustomerCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).DelCustomerCategory(ctx, req.(*DelCustomerCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCustomerCategoryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerCategoryByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetCustomerCategoryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_GetCustomerCategoryById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetCustomerCategoryById(ctx, req.(*GetCustomerCategoryByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_SearchCustomerCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCustomerCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).SearchCustomerCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_SearchCustomerCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).SearchCustomerCategory(ctx, req.(*SearchCustomerCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_AddCustomerSatisfactionSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCustomerSatisfactionSurveyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).AddCustomerSatisfactionSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_AddCustomerSatisfactionSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).AddCustomerSatisfactionSurvey(ctx, req.(*AddCustomerSatisfactionSurveyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCustomerSatisfactionSurveyById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerSatisfactionSurveyByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetCustomerSatisfactionSurveyById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_GetCustomerSatisfactionSurveyById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetCustomerSatisfactionSurveyById(ctx, req.(*GetCustomerSatisfactionSurveyByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_SearchCustomerSatisfactionSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCustomerSatisfactionSurveyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).SearchCustomerSatisfactionSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_SearchCustomerSatisfactionSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).SearchCustomerSatisfactionSurvey(ctx, req.(*SearchCustomerSatisfactionSurveyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Customer_ServiceDesc is the grpc.ServiceDesc for Customer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Customer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCustomer",
			Handler:    _Customer_AddCustomer_Handler,
		},
		{
			MethodName: "UpdateCustomer",
			Handler:    _Customer_UpdateCustomer_Handler,
		},
		{
			MethodName: "GetCustomerById",
			Handler:    _Customer_GetCustomerById_Handler,
		},
		{
			MethodName: "GetCustomerByCode",
			Handler:    _Customer_GetCustomerByCode_Handler,
		},
		{
			MethodName: "SearchCustomer",
			Handler:    _Customer_SearchCustomer_Handler,
		},
		{
			MethodName: "AddCustomerCategory",
			Handler:    _Customer_AddCustomerCategory_Handler,
		},
		{
			MethodName: "UpdateCustomerCategory",
			Handler:    _Customer_UpdateCustomerCategory_Handler,
		},
		{
			MethodName: "DelCustomerCategory",
			Handler:    _Customer_DelCustomerCategory_Handler,
		},
		{
			MethodName: "GetCustomerCategoryById",
			Handler:    _Customer_GetCustomerCategoryById_Handler,
		},
		{
			MethodName: "SearchCustomerCategory",
			Handler:    _Customer_SearchCustomerCategory_Handler,
		},
		{
			MethodName: "AddCustomerSatisfactionSurvey",
			Handler:    _Customer_AddCustomerSatisfactionSurvey_Handler,
		},
		{
			MethodName: "GetCustomerSatisfactionSurveyById",
			Handler:    _Customer_GetCustomerSatisfactionSurveyById_Handler,
		},
		{
			MethodName: "SearchCustomerSatisfactionSurvey",
			Handler:    _Customer_SearchCustomerSatisfactionSurvey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}
