// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: xAuth.proto

package server

import (
	"context"

	"erp/app/auth/rpc/internal/logic/role"
	"erp/app/auth/rpc/internal/svc"
	"erp/app/auth/rpc/pb"
)

type RoleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRoleServer
}

func NewRoleServer(svcCtx *svc.ServiceContext) *RoleServer {
	return &RoleServer{
		svcCtx: svcCtx,
	}
}

// -----------------------role-----------------------
func (s *RoleServer) AddRole(ctx context.Context, in *pb.AddRoleReq) (*pb.AddRoleResp, error) {
	l := rolelogic.NewAddRoleLogic(ctx, s.svcCtx)
	return l.AddRole(in)
}

func (s *RoleServer) UpdateRole(ctx context.Context, in *pb.UpdateRoleReq) (*pb.UpdateRoleResp, error) {
	l := rolelogic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *RoleServer) DelRole(ctx context.Context, in *pb.DelRoleReq) (*pb.DelRoleResp, error) {
	l := rolelogic.NewDelRoleLogic(ctx, s.svcCtx)
	return l.DelRole(in)
}

func (s *RoleServer) GetRoleById(ctx context.Context, in *pb.GetRoleByIdReq) (*pb.GetRoleByIdResp, error) {
	l := rolelogic.NewGetRoleByIdLogic(ctx, s.svcCtx)
	return l.GetRoleById(in)
}

func (s *RoleServer) SearchRole(ctx context.Context, in *pb.SearchRoleReq) (*pb.SearchRoleResp, error) {
	l := rolelogic.NewSearchRoleLogic(ctx, s.svcCtx)
	return l.SearchRole(in)
}
