// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: product.proto

package productcategory

import (
	"context"

	"erp/app/product/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddProductBatchReq         = pb.AddProductBatchReq
	AddProductBatchResp        = pb.AddProductBatchResp
	AddProductCategoryReq      = pb.AddProductCategoryReq
	AddProductCategoryResp     = pb.AddProductCategoryResp
	AddProductReq              = pb.AddProductReq
	AddProductResp             = pb.AddProductResp
	DelProductCategoryReq      = pb.DelProductCategoryReq
	DelProductCategoryResp     = pb.DelProductCategoryResp
	GetProductBatchByIdReq     = pb.GetProductBatchByIdReq
	GetProductBatchByIdResp    = pb.GetProductBatchByIdResp
	GetProductByIdReq          = pb.GetProductByIdReq
	GetProductByIdResp         = pb.GetProductByIdResp
	GetProductByNoReq          = pb.GetProductByNoReq
	GetProductByNoResp         = pb.GetProductByNoResp
	GetProductCategoryByIdReq  = pb.GetProductCategoryByIdReq
	GetProductCategoryByIdResp = pb.GetProductCategoryByIdResp
	Product                    = pb.Product
	ProductBatch               = pb.ProductBatch
	ProductCategory            = pb.ProductCategory
	SearchProductBatchReq      = pb.SearchProductBatchReq
	SearchProductBatchResp     = pb.SearchProductBatchResp
	SearchProductCategoryReq   = pb.SearchProductCategoryReq
	SearchProductCategoryResp  = pb.SearchProductCategoryResp
	SearchProductReq           = pb.SearchProductReq
	SearchProductResp          = pb.SearchProductResp
	UpdateProductCategoryReq   = pb.UpdateProductCategoryReq
	UpdateProductCategoryResp  = pb.UpdateProductCategoryResp
	UpdateProductReq           = pb.UpdateProductReq
	UpdateProductResp          = pb.UpdateProductResp

	ProductCategoryZrpcClient interface {
		// -----------------------productCategory-----------------------
		AddProductCategory(ctx context.Context, in *AddProductCategoryReq, opts ...grpc.CallOption) (*AddProductCategoryResp, error)
		UpdateProductCategory(ctx context.Context, in *UpdateProductCategoryReq, opts ...grpc.CallOption) (*UpdateProductCategoryResp, error)
		DelProductCategory(ctx context.Context, in *DelProductCategoryReq, opts ...grpc.CallOption) (*DelProductCategoryResp, error)
		GetProductCategoryById(ctx context.Context, in *GetProductCategoryByIdReq, opts ...grpc.CallOption) (*GetProductCategoryByIdResp, error)
		SearchProductCategory(ctx context.Context, in *SearchProductCategoryReq, opts ...grpc.CallOption) (*SearchProductCategoryResp, error)
	}

	defaultProductCategoryZrpcClient struct {
		cli zrpc.Client
	}
)

func NewProductCategoryZrpcClient(cli zrpc.Client) ProductCategoryZrpcClient {
	return &defaultProductCategoryZrpcClient{
		cli: cli,
	}
}

// -----------------------productCategory-----------------------
func (m *defaultProductCategoryZrpcClient) AddProductCategory(ctx context.Context, in *AddProductCategoryReq, opts ...grpc.CallOption) (*AddProductCategoryResp, error) {
	client := pb.NewProductCategoryClient(m.cli.Conn())
	return client.AddProductCategory(ctx, in, opts...)
}

func (m *defaultProductCategoryZrpcClient) UpdateProductCategory(ctx context.Context, in *UpdateProductCategoryReq, opts ...grpc.CallOption) (*UpdateProductCategoryResp, error) {
	client := pb.NewProductCategoryClient(m.cli.Conn())
	return client.UpdateProductCategory(ctx, in, opts...)
}

func (m *defaultProductCategoryZrpcClient) DelProductCategory(ctx context.Context, in *DelProductCategoryReq, opts ...grpc.CallOption) (*DelProductCategoryResp, error) {
	client := pb.NewProductCategoryClient(m.cli.Conn())
	return client.DelProductCategory(ctx, in, opts...)
}

func (m *defaultProductCategoryZrpcClient) GetProductCategoryById(ctx context.Context, in *GetProductCategoryByIdReq, opts ...grpc.CallOption) (*GetProductCategoryByIdResp, error) {
	client := pb.NewProductCategoryClient(m.cli.Conn())
	return client.GetProductCategoryById(ctx, in, opts...)
}

func (m *defaultProductCategoryZrpcClient) SearchProductCategory(ctx context.Context, in *SearchProductCategoryReq, opts ...grpc.CallOption) (*SearchProductCategoryResp, error) {
	client := pb.NewProductCategoryClient(m.cli.Conn())
	return client.SearchProductCategory(ctx, in, opts...)
}
