// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	permissionFieldNames          = builder.RawFieldNames(&Permission{})
	permissionRows                = strings.Join(permissionFieldNames, ",")
	permissionRowsExpectAutoSet   = strings.Join(stringx.Remove(permissionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	permissionRowsWithPlaceHolder = strings.Join(stringx.Remove(permissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpAuthPermissionIdPrefix = "cache:erpAuth:permission:id:"
)

type (
	permissionModel interface {
		Insert(ctx context.Context, data *Permission) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Permission, error)
		Update(ctx context.Context, data *Permission) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPermissionModel struct {
		sqlc.CachedConn
		table string
	}

	Permission struct {
		Id          int64          `db:"id"`          // 主键ID，雪花
		ParentId    int64          `db:"parent_id"`   // 父级权限ID。0：根节点
		Code        sql.NullString `db:"code"`        // 权限代码
		Description sql.NullString `db:"description"` // 权限描述/名称
		Url         sql.NullString `db:"url"`
		Method      sql.NullString `db:"method"`
	}
)

func newPermissionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPermissionModel {
	return &defaultPermissionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`permission`",
	}
}

func (m *defaultPermissionModel) Delete(ctx context.Context, id int64) error {
	erpAuthPermissionIdKey := fmt.Sprintf("%s%v", cacheErpAuthPermissionIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpAuthPermissionIdKey)
	return err
}

func (m *defaultPermissionModel) FindOne(ctx context.Context, id int64) (*Permission, error) {
	erpAuthPermissionIdKey := fmt.Sprintf("%s%v", cacheErpAuthPermissionIdPrefix, id)
	var resp Permission
	err := m.QueryRowCtx(ctx, &resp, erpAuthPermissionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", permissionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPermissionModel) Insert(ctx context.Context, data *Permission) (sql.Result, error) {
	erpAuthPermissionIdKey := fmt.Sprintf("%s%v", cacheErpAuthPermissionIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, permissionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.ParentId, data.Code, data.Description, data.Url, data.Method)
	}, erpAuthPermissionIdKey)
	return ret, err
}

func (m *defaultPermissionModel) Update(ctx context.Context, data *Permission) error {
	erpAuthPermissionIdKey := fmt.Sprintf("%s%v", cacheErpAuthPermissionIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, permissionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Code, data.Description, data.Url, data.Method, data.Id)
	}, erpAuthPermissionIdKey)
	return err
}

func (m *defaultPermissionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpAuthPermissionIdPrefix, primary)
}

func (m *defaultPermissionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", permissionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPermissionModel) tableName() string {
	return m.table
}
