// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: hr.proto

package server

import (
	"context"

	"erp/app/hr/rpc/internal/logic/employeedetail"
	"erp/app/hr/rpc/internal/svc"
	"erp/app/hr/rpc/pb"
)

type EmployeeDetailServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedEmployeeDetailServer
}

func NewEmployeeDetailServer(svcCtx *svc.ServiceContext) *EmployeeDetailServer {
	return &EmployeeDetailServer{
		svcCtx: svcCtx,
	}
}

// -----------------------员工信息扩展表-----------------------
func (s *EmployeeDetailServer) AddEmployeeDetail(ctx context.Context, in *pb.AddEmployeeDetailReq) (*pb.AddEmployeeDetailResp, error) {
	l := employeedetaillogic.NewAddEmployeeDetailLogic(ctx, s.svcCtx)
	return l.AddEmployeeDetail(in)
}

// 已废弃：补偿由 Msg 实现。原说明：Saga 补偿：删除新增的员工扩展信息，入参与 AddEmployeeDetailReq 相同
func (s *EmployeeDetailServer) BulkAddEmployeeDetail(ctx context.Context, in *pb.BulkAddEmployeeDetailReq) (*pb.BulkAddEmployeeDetailResp, error) {
	l := employeedetaillogic.NewBulkAddEmployeeDetailLogic(ctx, s.svcCtx)
	return l.BulkAddEmployeeDetail(in)
}

func (s *EmployeeDetailServer) UpdateEmployeeDetail(ctx context.Context, in *pb.UpdateEmployeeDetailReq) (*pb.UpdateEmployeeDetailResp, error) {
	l := employeedetaillogic.NewUpdateEmployeeDetailLogic(ctx, s.svcCtx)
	return l.UpdateEmployeeDetail(in)
}

// 已废弃：补偿由 Msg 实现。原说明：Saga 补偿：将离职日期回滚为未离职（与正向同请求体，约定 leaveDate=0 表示清空）
func (s *EmployeeDetailServer) DelEmployeeDetail(ctx context.Context, in *pb.DelEmployeeDetailReq) (*pb.DelEmployeeDetailResp, error) {
	l := employeedetaillogic.NewDelEmployeeDetailLogic(ctx, s.svcCtx)
	return l.DelEmployeeDetail(in)
}

func (s *EmployeeDetailServer) GetEmployeeDetailByEmployeeNo(ctx context.Context, in *pb.GetEmployeeDetailByEmployeeNoReq) (*pb.GetEmployeeDetailByEmployeeNoResp, error) {
	l := employeedetaillogic.NewGetEmployeeDetailByEmployeeNoLogic(ctx, s.svcCtx)
	return l.GetEmployeeDetailByEmployeeNo(in)
}

func (s *EmployeeDetailServer) GetEmployeeDetailById(ctx context.Context, in *pb.GetEmployeeDetailByIdReq) (*pb.GetEmployeeDetailByIdResp, error) {
	l := employeedetaillogic.NewGetEmployeeDetailByIdLogic(ctx, s.svcCtx)
	return l.GetEmployeeDetailById(in)
}

func (s *EmployeeDetailServer) SearchEmployeeDetail(ctx context.Context, in *pb.SearchEmployeeDetailReq) (*pb.SearchEmployeeDetailResp, error) {
	l := employeedetaillogic.NewSearchEmployeeDetailLogic(ctx, s.svcCtx)
	return l.SearchEmployeeDetail(in)
}
