// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productBatchFieldNames          = builder.RawFieldNames(&ProductBatch{})
	productBatchRows                = strings.Join(productBatchFieldNames, ",")
	productBatchRowsExpectAutoSet   = strings.Join(stringx.Remove(productBatchFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productBatchRowsWithPlaceHolder = strings.Join(stringx.Remove(productBatchFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpProductProductBatchIdPrefix = "cache:erpProduct:productBatch:id:"
)

type (
	productBatchModel interface {
		Insert(ctx context.Context, data *ProductBatch) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProductBatch, error)
		Update(ctx context.Context, data *ProductBatch) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductBatchModel struct {
		sqlc.CachedConn
		table string
	}

	ProductBatch struct {
		Id             int64     `db:"id"`              // 主键ID，雪花
		ProductId      int64     `db:"product_id"`      // 商品id
		BatchNo        string    `db:"batch_no"`        // 批次号
		ProductionDate time.Time `db:"production_date"` // 生产日期
		CreatedAt      time.Time `db:"created_at"`
	}
)

func newProductBatchModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProductBatchModel {
	return &defaultProductBatchModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`product_batch`",
	}
}

func (m *defaultProductBatchModel) Delete(ctx context.Context, id int64) error {
	erpProductProductBatchIdKey := fmt.Sprintf("%s%v", cacheErpProductProductBatchIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpProductProductBatchIdKey)
	return err
}

func (m *defaultProductBatchModel) FindOne(ctx context.Context, id int64) (*ProductBatch, error) {
	erpProductProductBatchIdKey := fmt.Sprintf("%s%v", cacheErpProductProductBatchIdPrefix, id)
	var resp ProductBatch
	err := m.QueryRowCtx(ctx, &resp, erpProductProductBatchIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productBatchRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductBatchModel) Insert(ctx context.Context, data *ProductBatch) (sql.Result, error) {
	erpProductProductBatchIdKey := fmt.Sprintf("%s%v", cacheErpProductProductBatchIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, productBatchRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.ProductId, data.BatchNo, data.ProductionDate)
	}, erpProductProductBatchIdKey)
	return ret, err
}

func (m *defaultProductBatchModel) Update(ctx context.Context, data *ProductBatch) error {
	erpProductProductBatchIdKey := fmt.Sprintf("%s%v", cacheErpProductProductBatchIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productBatchRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ProductId, data.BatchNo, data.ProductionDate, data.Id)
	}, erpProductProductBatchIdKey)
	return err
}

func (m *defaultProductBatchModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpProductProductBatchIdPrefix, primary)
}

func (m *defaultProductBatchModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productBatchRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProductBatchModel) tableName() string {
	return m.table
}
