// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: hr.proto

package server

import (
	"context"

	"erp/app/hr/rpc/internal/logic/position"
	"erp/app/hr/rpc/internal/svc"
	"erp/app/hr/rpc/pb"
)

type PositionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPositionServer
}

func NewPositionServer(svcCtx *svc.ServiceContext) *PositionServer {
	return &PositionServer{
		svcCtx: svcCtx,
	}
}

// -----------------------岗位表-----------------------
func (s *PositionServer) AddPosition(ctx context.Context, in *pb.AddPositionReq) (*pb.AddPositionResp, error) {
	l := positionlogic.NewAddPositionLogic(ctx, s.svcCtx)
	return l.AddPosition(in)
}

func (s *PositionServer) UpdatePosition(ctx context.Context, in *pb.UpdatePositionReq) (*pb.UpdatePositionResp, error) {
	l := positionlogic.NewUpdatePositionLogic(ctx, s.svcCtx)
	return l.UpdatePosition(in)
}

func (s *PositionServer) DelPosition(ctx context.Context, in *pb.DelPositionReq) (*pb.DelPositionResp, error) {
	l := positionlogic.NewDelPositionLogic(ctx, s.svcCtx)
	return l.DelPosition(in)
}

func (s *PositionServer) GetPositionById(ctx context.Context, in *pb.GetPositionByIdReq) (*pb.GetPositionByIdResp, error) {
	l := positionlogic.NewGetPositionByIdLogic(ctx, s.svcCtx)
	return l.GetPositionById(in)
}

func (s *PositionServer) SearchPosition(ctx context.Context, in *pb.SearchPositionReq) (*pb.SearchPositionResp, error) {
	l := positionlogic.NewSearchPositionLogic(ctx, s.svcCtx)
	return l.SearchPosition(in)
}
