// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	salesOrderFieldNames          = builder.RawFieldNames(&SalesOrder{})
	salesOrderRows                = strings.Join(salesOrderFieldNames, ",")
	salesOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(salesOrderFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	salesOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(salesOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpSalesSalesOrderIdPrefix      = "cache:erpSales:salesOrder:id:"
	cacheErpSalesSalesOrderOrderNoPrefix = "cache:erpSales:salesOrder:orderNo:"
)

type (
	salesOrderModel interface {
		Insert(ctx context.Context, data *SalesOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SalesOrder, error)
		FindOneByOrderNo(ctx context.Context, orderNo string) (*SalesOrder, error)
		Update(ctx context.Context, data *SalesOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSalesOrderModel struct {
		sqlc.CachedConn
		table string
	}

	SalesOrder struct {
		Id           int64          `db:"id"`            // 销售订单ID
		OrderNo      string         `db:"order_no"`      // 销售订单号
		CustomerId   int64          `db:"customer_id"`   // 客户ID
		OrderDate    time.Time      `db:"order_date"`    // 订单日期
		PromisedDate sql.NullTime   `db:"promised_date"` // 承诺交货日期
		TotalAmount  float64        `db:"total_amount"`  // 订单总金额
		Status       int64          `db:"status"`        // 状态：1-草稿 2-已确认 3-部分发货 4-已完成 5-已取消
		SalesmanId   int64          `db:"salesman_id"`   // 销售员（员工工号）
		ContractUrl  sql.NullString `db:"contract_url"`  // 合同URL
		CreatedAt    time.Time      `db:"created_at"`
	}
)

func newSalesOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSalesOrderModel {
	return &defaultSalesOrderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sales_order`",
	}
}

func (m *defaultSalesOrderModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	erpSalesSalesOrderIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderIdPrefix, id)
	erpSalesSalesOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpSalesSalesOrderIdKey, erpSalesSalesOrderOrderNoKey)
	return err
}

func (m *defaultSalesOrderModel) FindOne(ctx context.Context, id int64) (*SalesOrder, error) {
	erpSalesSalesOrderIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderIdPrefix, id)
	var resp SalesOrder
	err := m.QueryRowCtx(ctx, &resp, erpSalesSalesOrderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", salesOrderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSalesOrderModel) FindOneByOrderNo(ctx context.Context, orderNo string) (*SalesOrder, error) {
	erpSalesSalesOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderOrderNoPrefix, orderNo)
	var resp SalesOrder
	err := m.QueryRowIndexCtx(ctx, &resp, erpSalesSalesOrderOrderNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", salesOrderRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, orderNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSalesOrderModel) Insert(ctx context.Context, data *SalesOrder) (sql.Result, error) {
	erpSalesSalesOrderIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderIdPrefix, data.Id)
	erpSalesSalesOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderOrderNoPrefix, data.OrderNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, salesOrderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.OrderNo, data.CustomerId, data.OrderDate, data.PromisedDate, data.TotalAmount, data.Status, data.SalesmanId, data.ContractUrl)
	}, erpSalesSalesOrderIdKey, erpSalesSalesOrderOrderNoKey)
	return ret, err
}

func (m *defaultSalesOrderModel) Update(ctx context.Context, newData *SalesOrder) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	erpSalesSalesOrderIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderIdPrefix, data.Id)
	erpSalesSalesOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, salesOrderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.OrderNo, newData.CustomerId, newData.OrderDate, newData.PromisedDate, newData.TotalAmount, newData.Status, newData.SalesmanId, newData.ContractUrl, newData.Id)
	}, erpSalesSalesOrderIdKey, erpSalesSalesOrderOrderNoKey)
	return err
}

func (m *defaultSalesOrderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpSalesSalesOrderIdPrefix, primary)
}

func (m *defaultSalesOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", salesOrderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSalesOrderModel) tableName() string {
	return m.table
}
