package model

import (
	"context"
	"database/sql"
	"erp/app/sale/rpc/internal/types"
	"erp/common/xtime"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var _ SalesOrderModel = (*customSalesOrderModel)(nil)

type (
	// SalesOrderModel is an interface to be customized, add more methods here,
	// and implement the added methods in customSalesOrderModel.
	SalesOrderModel interface {
		salesOrderModel
		AddWithDetails(ctx context.Context, data *types.AddSalesOrderParam) error
		//UpdateStatus(ctx context.Context, id int64, status int64) error
		//UpdateContractURL(ctx context.Context, id int64, url string) error
		XUpdate(ctx context.Context, newData *SalesOrder) error
		Search(ctx context.Context, data *types.SearchOrderParams) ([]*SalesOrder, int64, error)
	}

	customSalesOrderModel struct {
		*defaultSalesOrderModel
		conn sqlx.SqlConn
	}
)

// NewSalesOrderModel returns a model for the database table.
func NewSalesOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) SalesOrderModel {
	return &customSalesOrderModel{
		defaultSalesOrderModel: newSalesOrderModel(conn, c, opts...),
		conn:                   conn,
	}
}

// -------- custom methods implementation --------
// Note: keep SQL compatible with existing schema generated by *_gen.go

func (m *customSalesOrderModel) AddWithDetails(ctx context.Context, data *types.AddSalesOrderParam) error {
	err := m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {

		_, err := session.ExecCtx(ctx,
			`INSERT INTO sales_order (id,order_no, customer_id, order_date, promised_date, total_amount, status, 
			salesman_id, contract_url) VALUES (?, ?, ?, FROM_UNIXTIME(?), FROM_UNIXTIME(?), ?, ?, ?, ?)`,
			data.Id, data.OrderNo, data.CustomerId, data.OrderDate, data.PromisedDate, data.TotalAmount, data.Status, data.SalesmanId, data.ContractUrl,
		)
		if err != nil {
			return err
		}

		// insert details
		if len(data.Details) > 0 {
			// per row insert to keep it simple and clear
			for _, d := range data.Details {
				_, err := session.ExecCtx(ctx,
					`INSERT INTO sales_order_detail (id,order_id, product_id, product_name, unit, quantity, 
unit_price, amount, delivered_qty, remark) VALUES (?,?, ?, ?, ?, ?, ?, ?, ?, ?)`,
					d.Id, d.OrderId, d.ProductId, d.ProductName, d.Unit, d.Quantity, d.UnitPrice, d.Amount, d.DeliveredQty,
					d.Remark,
				)
				if err != nil {
					return err
				}
			}
		}
		return nil
	})
	return err
}
func (m *customSalesOrderModel) XUpdate(ctx context.Context, newData *SalesOrder) error {
	var setClauses []string
	var args []interface{}

	if newData.Status != 0 {
		setClauses = append(setClauses, "status = ?")
		args = append(args, newData.Status)
	}
	if newData.ContractUrl.String != "" {
		setClauses = append(setClauses, "contract_url = ?")
		args = append(args, newData.ContractUrl.String)
	}

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	erpSaleSalesOrderIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderIdPrefix, data.Id)
	erpSaleSalesOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, strings.Join(setClauses, ", "))
		args = append(args, newData.Id)
		return conn.ExecCtx(ctx, query, args...)
	}, erpSaleSalesOrderIdKey, erpSaleSalesOrderOrderNoKey)
	return err
}

func (m *customSalesOrderModel) UpdateStatus(ctx context.Context, id int64, status int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	erpSaleSalesOrderIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderIdPrefix, data.Id)
	erpSaleSalesOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("UPDATE %s SET status = ? WHERE id = ?", m.table, salesOrderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, status, id)
	}, erpSaleSalesOrderIdKey, erpSaleSalesOrderOrderNoKey)
	return err
}
func (m *customSalesOrderModel) UpdateContractURL(ctx context.Context, id int64, url string) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	erpSaleSalesOrderIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderIdPrefix, data.Id)
	erpSaleSalesOrderOrderNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("UPDATE %s SET contract_url = ? WHERE id = ?", m.table)
		return conn.ExecCtx(ctx, query, url, id)
	}, erpSaleSalesOrderIdKey, erpSaleSalesOrderOrderNoKey)
	return err
}

func (m *customSalesOrderModel) Search(ctx context.Context, data *types.SearchOrderParams) ([]*SalesOrder, int64, error) {
	var orders []*SalesOrder
	conditions := []string{}
	args := []any{}

	if data.OrderNo != "" {
		conditions = append(conditions, "order_no = ?")
		args = append(args, data.OrderNo)
	}
	if data.CustomerId != 0 {
		conditions = append(conditions, "customer_id = ?")
		args = append(args, data.CustomerId)
	}
	if data.Status != 0 {
		conditions = append(conditions, "status = ?")
		args = append(args, data.Status)
	}
	if data.SalesmanId != 0 {
		conditions = append(conditions, "salesman_id = ?")
		args = append(args, data.SalesmanId)
	}

	if !xtime.IsZeroTime(data.StartOrderDate) && !xtime.IsZeroTime(data.EndOrderDate) {
		conditions = append(conditions, "order_date BETWEEN ? AND ?")
		args = append(args, data.StartOrderDate, data.EndOrderDate)
	} else if !xtime.IsZeroTime(data.StartOrderDate) {
		conditions = append(conditions, "order_date >= ?")
		args = append(args, data.StartOrderDate)
	} else if !xtime.IsZeroTime(data.EndOrderDate) {
		conditions = append(conditions, "order_date <= ?")
		args = append(args, data.EndOrderDate)
	}

	base := fmt.Sprintf("select %s from %s", salesOrderRows, m.table)
	countBase := fmt.Sprintf("select count(*) from %s", m.table)
	if len(conditions) > 0 {
		where := " where " + strings.Join(conditions, " AND ")
		base += where
		countBase += where
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, countBase, args...); err != nil {
		return nil, 0, err
	}

	if data.Limit != -1 {
		base += fmt.Sprintf(" ORDER BY status LIMIT %d OFFSET %d", data.Limit, (data.Page-1)*data.Limit)
	}

	if err := m.QueryRowsNoCacheCtx(ctx, &orders, base, args...); err != nil {
		return nil, 0, err
	}
	return orders, total, nil
}
