// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	salesOrderDetailFieldNames          = builder.RawFieldNames(&SalesOrderDetail{})
	salesOrderDetailRows                = strings.Join(salesOrderDetailFieldNames, ",")
	salesOrderDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(salesOrderDetailFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	salesOrderDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(salesOrderDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpSalesSalesOrderDetailIdPrefix = "cache:erpSales:salesOrderDetail:id:"
)

type (
	salesOrderDetailModel interface {
		Insert(ctx context.Context, data *SalesOrderDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SalesOrderDetail, error)
		Update(ctx context.Context, data *SalesOrderDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSalesOrderDetailModel struct {
		sqlc.CachedConn
		table string
	}

	SalesOrderDetail struct {
		Id           int64          `db:"id"`
		OrderId      int64          `db:"order_id"`      // 销售订单ID
		ProductId    int64          `db:"product_id"`    // 商品ID
		ProductName  sql.NullString `db:"product_name"`  // 商品名称
		Unit         string         `db:"unit"`          // 计量单位
		Quantity     float64        `db:"quantity"`      // 销售数量
		UnitPrice    float64        `db:"unit_price"`    // 销售单价
		Amount       float64        `db:"amount"`        // 金额
		DeliveredQty float64        `db:"delivered_qty"` // 已发货数量
		Remark       sql.NullString `db:"remark"`        // 备注
	}
)

func newSalesOrderDetailModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSalesOrderDetailModel {
	return &defaultSalesOrderDetailModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sales_order_detail`",
	}
}

func (m *defaultSalesOrderDetailModel) Delete(ctx context.Context, id int64) error {
	erpSalesSalesOrderDetailIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderDetailIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpSalesSalesOrderDetailIdKey)
	return err
}

func (m *defaultSalesOrderDetailModel) FindOne(ctx context.Context, id int64) (*SalesOrderDetail, error) {
	erpSalesSalesOrderDetailIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderDetailIdPrefix, id)
	var resp SalesOrderDetail
	err := m.QueryRowCtx(ctx, &resp, erpSalesSalesOrderDetailIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", salesOrderDetailRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSalesOrderDetailModel) Insert(ctx context.Context, data *SalesOrderDetail) (sql.Result, error) {
	erpSalesSalesOrderDetailIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderDetailIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, salesOrderDetailRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.OrderId, data.ProductId, data.ProductName, data.Unit, data.Quantity, data.UnitPrice, data.Amount, data.DeliveredQty, data.Remark)
	}, erpSalesSalesOrderDetailIdKey)
	return ret, err
}

func (m *defaultSalesOrderDetailModel) Update(ctx context.Context, data *SalesOrderDetail) error {
	erpSalesSalesOrderDetailIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesOrderDetailIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, salesOrderDetailRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.OrderId, data.ProductId, data.ProductName, data.Unit, data.Quantity, data.UnitPrice, data.Amount, data.DeliveredQty, data.Remark, data.Id)
	}, erpSalesSalesOrderDetailIdKey)
	return err
}

func (m *defaultSalesOrderDetailModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpSalesSalesOrderDetailIdPrefix, primary)
}

func (m *defaultSalesOrderDetailModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", salesOrderDetailRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSalesOrderDetailModel) tableName() string {
	return m.table
}
