// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	salesDeliveryFieldNames          = builder.RawFieldNames(&SalesDelivery{})
	salesDeliveryRows                = strings.Join(salesDeliveryFieldNames, ",")
	salesDeliveryRowsExpectAutoSet   = strings.Join(stringx.Remove(salesDeliveryFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	salesDeliveryRowsWithPlaceHolder = strings.Join(stringx.Remove(salesDeliveryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheErpSalesSalesDeliveryIdPrefix         = "cache:erpSales:salesDelivery:id:"
	cacheErpSalesSalesDeliveryDeliveryNoPrefix = "cache:erpSales:salesDelivery:deliveryNo:"
)

type (
	salesDeliveryModel interface {
		Insert(ctx context.Context, data *SalesDelivery) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SalesDelivery, error)
		FindOneByDeliveryNo(ctx context.Context, deliveryNo string) (*SalesDelivery, error)
		Update(ctx context.Context, data *SalesDelivery) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSalesDeliveryModel struct {
		sqlc.CachedConn
		table string
	}

	SalesDelivery struct {
		Id            int64         `db:"id"`             // 出库单ID
		DeliveryNo    string        `db:"delivery_no"`    // 出库单号
		OrderId       sql.NullInt64 `db:"order_id"`       // 销售订单ID
		WarehouseId   int64         `db:"warehouse_id"`   // 出库仓库
		DeliveryDate  time.Time     `db:"delivery_date"`  // 出库日期
		TotalQuantity float64       `db:"total_quantity"` // 总数量
		TotalAmount   float64       `db:"total_amount"`   // 总金额
		Status        int64         `db:"status"`         // 状态：1-未出库 2-已出库 3-部分出库 4-已完成 5-已取消
		CreatedBy     int64         `db:"created_by"`     // 操作人
		CreatedAt     time.Time     `db:"created_at"`
	}
)

func newSalesDeliveryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSalesDeliveryModel {
	return &defaultSalesDeliveryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sales_delivery`",
	}
}

func (m *defaultSalesDeliveryModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	erpSalesSalesDeliveryDeliveryNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesDeliveryDeliveryNoPrefix, data.DeliveryNo)
	erpSalesSalesDeliveryIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesDeliveryIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, erpSalesSalesDeliveryDeliveryNoKey, erpSalesSalesDeliveryIdKey)
	return err
}

func (m *defaultSalesDeliveryModel) FindOne(ctx context.Context, id int64) (*SalesDelivery, error) {
	erpSalesSalesDeliveryIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesDeliveryIdPrefix, id)
	var resp SalesDelivery
	err := m.QueryRowCtx(ctx, &resp, erpSalesSalesDeliveryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", salesDeliveryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSalesDeliveryModel) FindOneByDeliveryNo(ctx context.Context, deliveryNo string) (*SalesDelivery, error) {
	erpSalesSalesDeliveryDeliveryNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesDeliveryDeliveryNoPrefix, deliveryNo)
	var resp SalesDelivery
	err := m.QueryRowIndexCtx(ctx, &resp, erpSalesSalesDeliveryDeliveryNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `delivery_no` = ? limit 1", salesDeliveryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, deliveryNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSalesDeliveryModel) Insert(ctx context.Context, data *SalesDelivery) (sql.Result, error) {
	erpSalesSalesDeliveryDeliveryNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesDeliveryDeliveryNoPrefix, data.DeliveryNo)
	erpSalesSalesDeliveryIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesDeliveryIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, salesDeliveryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.DeliveryNo, data.OrderId, data.WarehouseId, data.DeliveryDate, data.TotalQuantity, data.TotalAmount, data.Status, data.CreatedBy)
	}, erpSalesSalesDeliveryDeliveryNoKey, erpSalesSalesDeliveryIdKey)
	return ret, err
}

func (m *defaultSalesDeliveryModel) Update(ctx context.Context, newData *SalesDelivery) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	erpSalesSalesDeliveryDeliveryNoKey := fmt.Sprintf("%s%v", cacheErpSalesSalesDeliveryDeliveryNoPrefix, data.DeliveryNo)
	erpSalesSalesDeliveryIdKey := fmt.Sprintf("%s%v", cacheErpSalesSalesDeliveryIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, salesDeliveryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeliveryNo, newData.OrderId, newData.WarehouseId, newData.DeliveryDate, newData.TotalQuantity, newData.TotalAmount, newData.Status, newData.CreatedBy, newData.Id)
	}, erpSalesSalesDeliveryDeliveryNoKey, erpSalesSalesDeliveryIdKey)
	return err
}

func (m *defaultSalesDeliveryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheErpSalesSalesDeliveryIdPrefix, primary)
}

func (m *defaultSalesDeliveryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", salesDeliveryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSalesDeliveryModel) tableName() string {
	return m.table
}
