// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: finance.proto

package server

import (
	"context"

	"erp/app/finance/rpc/internal/logic/fixedasset"
	"erp/app/finance/rpc/internal/svc"
	"erp/app/finance/rpc/pb"
)

type FixedAssetServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFixedAssetServer
}

func NewFixedAssetServer(svcCtx *svc.ServiceContext) *FixedAssetServer {
	return &FixedAssetServer{
		svcCtx: svcCtx,
	}
}

// -----------------------fixedAsset-----------------------
func (s *FixedAssetServer) AddFixedAsset(ctx context.Context, in *pb.AddFixedAssetReq) (*pb.AddFixedAssetResp, error) {
	l := fixedassetlogic.NewAddFixedAssetLogic(ctx, s.svcCtx)
	return l.AddFixedAsset(in)
}

func (s *FixedAssetServer) UpdateFixedAsset(ctx context.Context, in *pb.UpdateFixedAssetReq) (*pb.UpdateFixedAssetResp, error) {
	l := fixedassetlogic.NewUpdateFixedAssetLogic(ctx, s.svcCtx)
	return l.UpdateFixedAsset(in)
}

func (s *FixedAssetServer) GetFixedAssetById(ctx context.Context, in *pb.GetFixedAssetByIdReq) (*pb.GetFixedAssetByIdResp, error) {
	l := fixedassetlogic.NewGetFixedAssetByIdLogic(ctx, s.svcCtx)
	return l.GetFixedAssetById(in)
}

func (s *FixedAssetServer) SearchFixedAsset(ctx context.Context, in *pb.SearchFixedAssetReq) (*pb.SearchFixedAssetResp, error) {
	l := fixedassetlogic.NewSearchFixedAssetLogic(ctx, s.svcCtx)
	return l.SearchFixedAsset(in)
}
