// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type AddUserItem struct {
	EmployeeId string `json:"employee_id"` // 员工ID
	EmployeeNo string `json:"employee_no"` // 员工ID
	Username   string `json:"username"`    // 用户名
	RealName   string `json:"real_name"`   // 真实姓名
	Password   string `json:"password"`    // 密码(未加密)
	Email      string `json:"email"`       // 邮箱
	Phone      string `json:"phone"`       // 手机号
}

type AddUserReq struct {
	Users []AddUserItem `json:"users"`
}

type EmptyResponse struct {
}

type ForgotPasswordReq struct {
	Phone      string `json:"phone"`
	Password   string `json:"password"`
	VerifyCode string `json:"verify_code"`
}

type GetMyUserByIdResp struct {
	User User `json:"user"` // user
}

type GetUserByIdReq struct {
	Id string `path:"id"` // id
}

type GetUserByIdResp struct {
	User User `json:"user"` // user
}

type LoginReq struct {
	EmployeeNo string `json:"employee_no"`
	Password   string `json:"password"`
}

type LoginResp struct {
	Id           string `json:"id"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type SearchUserReq struct {
	Page     int64  `form:"page,optional,default=1"`   // page
	Limit    int64  `form:"limit,optional,default=20"` // limit
	Username string `form:"username,optional"`         // 用户名
	RealName string `form:"real_name,optional"`        // 真实姓名
	Phone    string `form:"phone,optional"`            // 手机号
	Email    string `form:"email,optional"`            // 邮箱
}

type SearchUserResp struct {
	Total int64  `json:"total"`
	Users []User `json:"users"` // user
}

type SendVerifyCodeReq struct {
	Phone string `json:"phone"`
}

type UpdatePasswordReq struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type UpdateUserInfoReq struct {
	Username string `json:"username,optional"`
	RealName string `json:"real_name,optional"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`  // 邮箱
	Avatar   string `json:"avatar,optional"` // 头像
}

type User struct {
	Id         string `json:"id"`          // 用户ID
	EmployeeId string `json:"employee_id"` // 员工ID
	EmployeeNo string `json:"employee_no"` // 员工no
	Username   string `json:"username"`    // 用户名
	RealName   string `json:"real_name"`   // 真实姓名
	Phone      string `json:"phone"`       // 手机号
	Email      string `json:"email"`       // 邮箱
	Avatar     string `json:"avatar"`      // 头像
	Resigned   bool   `json:"resigned"`    // 已离职
	CreatedBy  string `json:"created_by"`  // 创建人ID
	CreatedAt  int64  `json:"created_at"`  // 创建时间
	UpdatedAt  int64  `json:"updated_at"`  // 更新时间
	UpdatedBy  string `json:"updated_by"`  // 更新人ID
}
