// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: hr.proto

package server

import (
	"context"

	"erp/app/hr/rpc/internal/logic/leaveapplication"
	"erp/app/hr/rpc/internal/svc"
	"erp/app/hr/rpc/pb"
)

type LeaveApplicationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLeaveApplicationServer
}

func NewLeaveApplicationServer(svcCtx *svc.ServiceContext) *LeaveApplicationServer {
	return &LeaveApplicationServer{
		svcCtx: svcCtx,
	}
}

// -----------------------请假申请表-----------------------
func (s *LeaveApplicationServer) AddLeaveApplication(ctx context.Context, in *pb.AddLeaveApplicationReq) (*pb.AddLeaveApplicationResp, error) {
	l := leaveapplicationlogic.NewAddLeaveApplicationLogic(ctx, s.svcCtx)
	return l.AddLeaveApplication(in)
}

func (s *LeaveApplicationServer) UpdateLeaveApplication(ctx context.Context, in *pb.UpdateLeaveApplicationReq) (*pb.UpdateLeaveApplicationResp, error) {
	l := leaveapplicationlogic.NewUpdateLeaveApplicationLogic(ctx, s.svcCtx)
	return l.UpdateLeaveApplication(in)
}

func (s *LeaveApplicationServer) GetLeaveApplicationById(ctx context.Context, in *pb.GetLeaveApplicationByIdReq) (*pb.GetLeaveApplicationByIdResp, error) {
	l := leaveapplicationlogic.NewGetLeaveApplicationByIdLogic(ctx, s.svcCtx)
	return l.GetLeaveApplicationById(in)
}

func (s *LeaveApplicationServer) SearchLeaveApplication(ctx context.Context, in *pb.SearchLeaveApplicationReq) (*pb.SearchLeaveApplicationResp, error) {
	l := leaveapplicationlogic.NewSearchLeaveApplicationLogic(ctx, s.svcCtx)
	return l.SearchLeaveApplication(in)
}
