// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	bom "erp/app/production/api/internal/handler/bom"
	bomitem "erp/app/production/api/internal/handler/bomitem"
	requisition "erp/app/production/api/internal/handler/requisition"
	requisitionitem "erp/app/production/api/internal/handler/requisitionitem"
	workorder "erp/app/production/api/internal/handler/workorder"
	"erp/app/production/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建BOM
					Method:  http.MethodPost,
					Path:    "/boms",
					Handler: bom.CreateBomHandler(serverCtx),
				},
				{
					// 获取BOM列表
					Method:  http.MethodGet,
					Path:    "/boms",
					Handler: bom.GetBomListHandler(serverCtx),
				},
				{
					// 更新BOM
					Method:  http.MethodPut,
					Path:    "/boms/:id",
					Handler: bom.UpdateBomHandler(serverCtx),
				},
				{
					// 删除BOM
					Method:  http.MethodDelete,
					Path:    "/boms/:id",
					Handler: bom.DeleteBomHandler(serverCtx),
				},
				{
					// 获取BOM详情
					Method:  http.MethodGet,
					Path:    "/boms/:id",
					Handler: bom.GetBomDetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/production"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建BOM明细
					Method:  http.MethodPost,
					Path:    "/bom-items",
					Handler: bomitem.CreateBomItemHandler(serverCtx),
				},
				{
					// 更新BOM明细
					Method:  http.MethodPut,
					Path:    "/bom-items/:id",
					Handler: bomitem.UpdateBomItemHandler(serverCtx),
				},
				{
					// 删除BOM明细
					Method:  http.MethodDelete,
					Path:    "/bom-items/:id",
					Handler: bomitem.DeleteBomItemHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/production"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建领料单
					Method:  http.MethodPost,
					Path:    "/requisitions",
					Handler: requisition.CreateRequisitionHandler(serverCtx),
				},
				{
					// 获取领料单列表
					Method:  http.MethodGet,
					Path:    "/requisitions",
					Handler: requisition.GetRequisitionListHandler(serverCtx),
				},
				{
					// 更新领料单
					Method:  http.MethodPut,
					Path:    "/requisitions/:id",
					Handler: requisition.UpdateRequisitionHandler(serverCtx),
				},
				{
					// 获取领料单详情
					Method:  http.MethodGet,
					Path:    "/requisitions/:id",
					Handler: requisition.GetRequisitionDetailHandler(serverCtx),
				},
				{
					// 审批领料单
					Method:  http.MethodPut,
					Path:    "/requisitions/:id/approve",
					Handler: requisition.ApproveRequisitionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/production"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建领料单明细
					Method:  http.MethodPost,
					Path:    "/requisition-items",
					Handler: requisitionitem.CreateRequisitionItemHandler(serverCtx),
				},
				{
					// 更新领料单明细
					Method:  http.MethodPut,
					Path:    "/requisition-items/:id",
					Handler: requisitionitem.UpdateRequisitionItemHandler(serverCtx),
				},
				{
					// 删除领料单明细
					Method:  http.MethodDelete,
					Path:    "/requisition-items/:id",
					Handler: requisitionitem.DeleteRequisitionItemHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/production"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建生产工单
					Method:  http.MethodPost,
					Path:    "/work-orders",
					Handler: workorder.CreateWorkOrderHandler(serverCtx),
				},
				{
					// 获取生产工单列表
					Method:  http.MethodGet,
					Path:    "/work-orders",
					Handler: workorder.GetWorkOrderListHandler(serverCtx),
				},
				{
					// 更新生产工单
					Method:  http.MethodPut,
					Path:    "/work-orders/:id",
					Handler: workorder.UpdateWorkOrderHandler(serverCtx),
				},
				{
					// 删除生产工单
					Method:  http.MethodDelete,
					Path:    "/work-orders/:id",
					Handler: workorder.DeleteWorkOrderHandler(serverCtx),
				},
				{
					// 获取生产工单详情
					Method:  http.MethodGet,
					Path:    "/work-orders/:id",
					Handler: workorder.GetWorkOrderDetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/production"),
	)
}
