// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	purchaseOrder "erp/app/purchase/api/internal/handler/purchaseOrder"
	purchaseReceipt "erp/app/purchase/api/internal/handler/purchaseReceipt"
	purchaseRequisition "erp/app/purchase/api/internal/handler/purchaseRequisition"
	"erp/app/purchase/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: purchaseOrder.CreateOrderWithDetailsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: purchaseOrder.UpdateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:order_id",
					Handler: purchaseOrder.GetOrderWithDetailsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cancel",
					Handler: purchaseOrder.CancelPurchaseOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/createFromRequisition",
					Handler: purchaseOrder.CreateOrderFromRequisitionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/detail",
					Handler: purchaseOrder.UpdateOrderDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/search",
					Handler: purchaseOrder.SearchOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/:id",
					Handler: purchaseOrder.UploadContractFileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/purchase/order"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: purchaseReceipt.UpdateReceiptHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:receipt_id",
					Handler: purchaseReceipt.GetReceiptWithDetailsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: purchaseReceipt.CreateReceiptWithDetailsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/createFromOrder",
					Handler: purchaseReceipt.CreateReceiptFromOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/detail",
					Handler: purchaseReceipt.UpdateReceiptDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/search",
					Handler: purchaseReceipt.SearchReceiptHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/purchase/receipt"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: purchaseRequisition.CreateRequisitionWithDetailsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: purchaseRequisition.SearchRequisitionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: purchaseRequisition.UpdateRequisitionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:requisition_id",
					Handler: purchaseRequisition.GetRequisitionWithDetailsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/approve",
					Handler: purchaseRequisition.ApproveRequisitionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/detail",
					Handler: purchaseRequisition.UpdateRequisitionDetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/purchase/requisitions"),
	)
}
