// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CreateSupplierReq struct {
	Uscc         string `json:"uscc"`                   // 统一社会信用代码
	Name         string `json:"name"`                   // 供应商名称
	Contact      string `json:"contact,optional"`       // 联系人
	Phone        string `json:"phone,optional"`         // 联系电话
	Address      string `json:"address,optional"`       // 地址
	PaymentTerms string `json:"payment_terms,optional"` // 付款条件
	Credit       string `json:"credit,optional"`        // 信用等级
	IsActive     int64  `json:"is_active,optional"`     // 状态筛选
}

type CreateSupplierResp struct {
	Id string `json:"id"` // 返回创建的供应商ID
}

type EvaluateSupplierReq struct {
	SupplierId    string  `json:"supplier_id"`     // 供应商ID
	QualityScore  float64 `json:"quality_score"`   // 质量评分(0-100)
	DeliveryScore float64 `json:"delivery_score"`  // 交付评分(0-100)
	ServiceScore  float64 `json:"service_score"`   // 服务评分(0-100)
	Remark        string  `json:"remark,optional"` // 备注
}

type EvaluateSupplierResp struct {
	EvaluationId string `json:"evaluation_id"` // 评估记录ID
}

type GetSupplierDetailReq struct {
	Id string `path:"id"`
}

type GetSupplierDetailResp struct {
	Supplier Supplier `json:"supplier"`
}

type GetSupplierListReq struct {
	Page     int64  `form:"page,optional,default=1"`
	Limit    int64  `form:"limit,optional,default=10"` // limit
	Code     string `form:"code,optional"`             // 供应商编码
	Uscc     string `form:"uscc,optional"`             // 统一社会信用代码
	Name     string `form:"name,optional"`             // 供应商名称
	Contact  string `form:"contact,optional"`          // 联系人
	Address  string `form:"address,optional"`          // 地址
	Credit   string `form:"credit,optional"`           // 信用等级筛选
	IsActive int64  `form:"is_active,optional"`        // 状态筛选
}

type GetSupplierListResp struct {
	Total     int64       `json:"total"`
	Suppliers []*Supplier `json:"suppliers"`
}

type SearchSupplierEvaluationsReq struct {
	Page        int64   `form:"page,optional,default=1"`
	Limit       int64   `form:"limit,optional,default=10"` // limit
	SupplierId  string  `form:"supplier_id,optional"`      // 供应商ID
	QualityMin  float64 `form:"quality_min,optional"`      // 质量评分最小值
	QualityMax  float64 `form:"quality_max,optional"`      // 质量评分最大值
	QualityOp   string  `form:"quality_op,optional"`       // 质量评分操作符: gt/gte/eq/lt/lte
	DeliveryMin float64 `form:"delivery_min,optional"`     // 交付评分最小值
	DeliveryMax float64 `form:"delivery_max,optional"`     // 交付评分最大值
	DeliveryOp  string  `form:"delivery_op,optional"`      // 交付评分操作符
	ServiceMin  float64 `form:"service_min,optional"`      // 服务评分最小值
	ServiceMax  float64 `form:"service_max,optional"`      // 服务评分最大值
	ServiceOp   string  `form:"service_op,optional"`       // 服务评分操作符
	OverallMin  float64 `form:"overall_min,optional"`      // 综合评分最小值
	OverallMax  float64 `form:"overall_max,optional"`      // 综合评分最大值
	OverallOp   string  `form:"overall_op,optional"`       // 综合评分操作符
	StartDate   int64   `form:"start_date,optional"`       // 开始时间
	EndDate     int64   `form:"end_date,optional"`         // 结束时间
	EvaluatorId string  `form:"evaluator_id,optional"`     // 评估人ID
}

type SearchSupplierEvaluationsResp struct {
	Total       int64                 `json:"total"`
	Evaluations []*SupplierEvaluation `json:"evaluations"`
}

type Supplier struct {
	Id            string `json:"id"`              // 供应商ID
	Code          string `json:"code"`            // 供应商编码
	Uscc          string `json:"uscc"`            // 统一社会信用代码
	Name          string `json:"name"`            // 供应商名称
	Contact       string `json:"contact"`         // 联系人
	Phone         string `json:"phone"`           // 联系电话
	Address       string `json:"address"`         // 地址
	PaymentTerms  string `json:"payment_terms"`   // 付款条件
	Credit        string `json:"credit"`          // 信用等级: A/B/C/D/E
	IsActive      int64  `json:"is_active"`       // 是否合作中
	CreatedAt     int64  `json:"created_at"`      // 创建时间
	CreatedBy     string `json:"created_by"`      // 创建人ID
	CreatedByNo   string `json:"created_by_no"`   // 创建人工号
	CreatedByName string `json:"created_by_name"` // 创建人姓名
	UpdatedAt     int64  `json:"updated_at"`      // 更新时间
	UpdatedBy     string `json:"updated_by"`      // 更新人ID
	UpdatedByNo   string `json:"updated_by_no"`   // 修改人工号
	UpdatedByName string `json:"updated_by_name"` // 修改人姓名
}

type SupplierEvaluation struct {
	Id            string  `json:"id"`             // 评估ID
	SupplierId    string  `json:"supplier_id"`    // 供应商ID
	QualityScore  float64 `json:"quality_score"`  // 质量评分(0-10)
	DeliveryScore float64 `json:"delivery_score"` // 交付评分(0-10)
	ServiceScore  float64 `json:"service_score"`  // 服务评分(0-10)
	OverallScore  float64 `json:"overall_score"`  // 综合评分
	EvaluatorId   string  `json:"evaluator_id"`   // 评估人ID
	EvaluatorNo   string  `json:"evaluator_no"`   // 评估人工号
	EvaluatorName string  `json:"evaluator_name"` // 评估人姓名
	CreatedAt     int64   `json:"created_at"`     // 评估时间
	Remark        string  `json:"remark"`         // 备注
}

type UpdateSupplierReq struct {
	Id           string `json:"id"`                     // 供应商ID
	Name         string `json:"name,optional"`          // 供应商名称
	Contact      string `json:"contact,optional"`       // 联系人
	Phone        string `json:"phone,optional"`         // 联系电话
	Address      string `json:"address,optional"`       // 地址
	PaymentTerms string `json:"payment_terms,optional"` // 付款条件
	Credit       string `json:"credit,optional"`        // 信用等级
	IsActive     int64  `json:"is_active,optional"`     // 是否合作中
}

type UpdateSupplierResp struct {
}
