// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: xAuth.proto

package permission

import (
	"context"

	"erp/app/auth/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRolePermissionReq           = pb.AddRolePermissionReq
	AddRolePermissionResp          = pb.AddRolePermissionResp
	AddRoleReq                     = pb.AddRoleReq
	AddRoleResp                    = pb.AddRoleResp
	AddUserRoleReq                 = pb.AddUserRoleReq
	AddUserRoleResp                = pb.AddUserRoleResp
	DelRolePermissionReq           = pb.DelRolePermissionReq
	DelRolePermissionResp          = pb.DelRolePermissionResp
	DelRoleReq                     = pb.DelRoleReq
	DelRoleResp                    = pb.DelRoleResp
	DelUserRoleByUserIdReq         = pb.DelUserRoleByUserIdReq
	DelUserRoleByUserIdResp        = pb.DelUserRoleByUserIdResp
	DelUserRoleReq                 = pb.DelUserRoleReq
	DelUserRoleResp                = pb.DelUserRoleResp
	GetAllPermissionsReq           = pb.GetAllPermissionsReq
	GetAllPermissionsResp          = pb.GetAllPermissionsResp
	GetRoleByIdReq                 = pb.GetRoleByIdReq
	GetRoleByIdResp                = pb.GetRoleByIdResp
	GetRolePermissionByRoleIdReq   = pb.GetRolePermissionByRoleIdReq
	GetRolePermissionByRoleIdResp  = pb.GetRolePermissionByRoleIdResp
	GetUserRoleByUserIdReq         = pb.GetUserRoleByUserIdReq
	GetUserRoleByUserIdResp        = pb.GetUserRoleByUserIdResp
	Permission                     = pb.Permission
	PermissionItem                 = pb.PermissionItem
	PermissionWithRolePermissionId = pb.PermissionWithRolePermissionId
	Role                           = pb.Role
	RoleAndPermissionDetails       = pb.RoleAndPermissionDetails
	RoleAndPermissions             = pb.RoleAndPermissions
	RolePermission                 = pb.RolePermission
	SearchRolePermissionReq        = pb.SearchRolePermissionReq
	SearchRolePermissionResp       = pb.SearchRolePermissionResp
	SearchRoleReq                  = pb.SearchRoleReq
	SearchRoleResp                 = pb.SearchRoleResp
	SearchUserRoleReq              = pb.SearchUserRoleReq
	SearchUserRoleResp             = pb.SearchUserRoleResp
	UpdateRolePermissionReq        = pb.UpdateRolePermissionReq
	UpdateRolePermissionResp       = pb.UpdateRolePermissionResp
	UpdateRoleReq                  = pb.UpdateRoleReq
	UpdateRoleResp                 = pb.UpdateRoleResp
	UpdateUserRoleReq              = pb.UpdateUserRoleReq
	UpdateUserRoleResp             = pb.UpdateUserRoleResp
	UserRole                       = pb.UserRole

	PermissionZrpcClient interface {
		// -----------------------permission-----------------------
		GetAllPermissions(ctx context.Context, in *GetAllPermissionsReq, opts ...grpc.CallOption) (*GetAllPermissionsResp, error)
	}

	defaultPermissionZrpcClient struct {
		cli zrpc.Client
	}
)

func NewPermissionZrpcClient(cli zrpc.Client) PermissionZrpcClient {
	return &defaultPermissionZrpcClient{
		cli: cli,
	}
}

// -----------------------permission-----------------------
func (m *defaultPermissionZrpcClient) GetAllPermissions(ctx context.Context, in *GetAllPermissionsReq, opts ...grpc.CallOption) (*GetAllPermissionsResp, error) {
	client := pb.NewPermissionClient(m.cli.Conn())
	return client.GetAllPermissions(ctx, in, opts...)
}
