// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: xAuth.proto

package rolepermission

import (
	"context"

	"erp/app/auth/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRolePermissionReq           = pb.AddRolePermissionReq
	AddRolePermissionResp          = pb.AddRolePermissionResp
	AddRoleReq                     = pb.AddRoleReq
	AddRoleResp                    = pb.AddRoleResp
	AddUserRoleReq                 = pb.AddUserRoleReq
	AddUserRoleResp                = pb.AddUserRoleResp
	DelRolePermissionReq           = pb.DelRolePermissionReq
	DelRolePermissionResp          = pb.DelRolePermissionResp
	DelRoleReq                     = pb.DelRoleReq
	DelRoleResp                    = pb.DelRoleResp
	DelUserRoleByUserIdReq         = pb.DelUserRoleByUserIdReq
	DelUserRoleByUserIdResp        = pb.DelUserRoleByUserIdResp
	DelUserRoleReq                 = pb.DelUserRoleReq
	DelUserRoleResp                = pb.DelUserRoleResp
	GetAllPermissionsReq           = pb.GetAllPermissionsReq
	GetAllPermissionsResp          = pb.GetAllPermissionsResp
	GetRoleByIdReq                 = pb.GetRoleByIdReq
	GetRoleByIdResp                = pb.GetRoleByIdResp
	GetRolePermissionByRoleIdReq   = pb.GetRolePermissionByRoleIdReq
	GetRolePermissionByRoleIdResp  = pb.GetRolePermissionByRoleIdResp
	GetUserRoleByUserIdReq         = pb.GetUserRoleByUserIdReq
	GetUserRoleByUserIdResp        = pb.GetUserRoleByUserIdResp
	Permission                     = pb.Permission
	PermissionItem                 = pb.PermissionItem
	PermissionWithRolePermissionId = pb.PermissionWithRolePermissionId
	Role                           = pb.Role
	RoleAndPermissionDetails       = pb.RoleAndPermissionDetails
	RoleAndPermissions             = pb.RoleAndPermissions
	RolePermission                 = pb.RolePermission
	SearchRolePermissionReq        = pb.SearchRolePermissionReq
	SearchRolePermissionResp       = pb.SearchRolePermissionResp
	SearchRoleReq                  = pb.SearchRoleReq
	SearchRoleResp                 = pb.SearchRoleResp
	SearchUserRoleReq              = pb.SearchUserRoleReq
	SearchUserRoleResp             = pb.SearchUserRoleResp
	UpdateRolePermissionReq        = pb.UpdateRolePermissionReq
	UpdateRolePermissionResp       = pb.UpdateRolePermissionResp
	UpdateRoleReq                  = pb.UpdateRoleReq
	UpdateRoleResp                 = pb.UpdateRoleResp
	UpdateUserRoleReq              = pb.UpdateUserRoleReq
	UpdateUserRoleResp             = pb.UpdateUserRoleResp
	UserRole                       = pb.UserRole

	RolePermissionZrpcClient interface {
		// -----------------------rolePermission-----------------------
		AddRolePermission(ctx context.Context, in *AddRolePermissionReq, opts ...grpc.CallOption) (*AddRolePermissionResp, error)
		DelRolePermission(ctx context.Context, in *DelRolePermissionReq, opts ...grpc.CallOption) (*DelRolePermissionResp, error)
		GetRolePermissionByRoleId(ctx context.Context, in *GetRolePermissionByRoleIdReq, opts ...grpc.CallOption) (*GetRolePermissionByRoleIdResp, error)
		SearchRolePermission(ctx context.Context, in *SearchRolePermissionReq, opts ...grpc.CallOption) (*SearchRolePermissionResp, error)
	}

	defaultRolePermissionZrpcClient struct {
		cli zrpc.Client
	}
)

func NewRolePermissionZrpcClient(cli zrpc.Client) RolePermissionZrpcClient {
	return &defaultRolePermissionZrpcClient{
		cli: cli,
	}
}

// -----------------------rolePermission-----------------------
func (m *defaultRolePermissionZrpcClient) AddRolePermission(ctx context.Context, in *AddRolePermissionReq, opts ...grpc.CallOption) (*AddRolePermissionResp, error) {
	client := pb.NewRolePermissionClient(m.cli.Conn())
	return client.AddRolePermission(ctx, in, opts...)
}

func (m *defaultRolePermissionZrpcClient) DelRolePermission(ctx context.Context, in *DelRolePermissionReq, opts ...grpc.CallOption) (*DelRolePermissionResp, error) {
	client := pb.NewRolePermissionClient(m.cli.Conn())
	return client.DelRolePermission(ctx, in, opts...)
}

func (m *defaultRolePermissionZrpcClient) GetRolePermissionByRoleId(ctx context.Context, in *GetRolePermissionByRoleIdReq, opts ...grpc.CallOption) (*GetRolePermissionByRoleIdResp, error) {
	client := pb.NewRolePermissionClient(m.cli.Conn())
	return client.GetRolePermissionByRoleId(ctx, in, opts...)
}

func (m *defaultRolePermissionZrpcClient) SearchRolePermission(ctx context.Context, in *SearchRolePermissionReq, opts ...grpc.CallOption) (*SearchRolePermissionResp, error) {
	client := pb.NewRolePermissionClient(m.cli.Conn())
	return client.SearchRolePermission(ctx, in, opts...)
}
