// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: supplier.proto

package server

import (
	"context"

	"erp/app/supplier/rpc/internal/logic"
	"erp/app/supplier/rpc/internal/svc"
	"erp/app/supplier/rpc/pb"
)

type SupplierServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSupplierServer
}

func NewSupplierServer(svcCtx *svc.ServiceContext) *SupplierServer {
	return &SupplierServer{
		svcCtx: svcCtx,
	}
}

// -----------------------supplier-----------------------
func (s *SupplierServer) AddSupplier(ctx context.Context, in *pb.AddSupplierReq) (*pb.AddSupplierResp, error) {
	l := logic.NewAddSupplierLogic(ctx, s.svcCtx)
	return l.AddSupplier(in)
}

func (s *SupplierServer) UpdateSupplier(ctx context.Context, in *pb.UpdateSupplierReq) (*pb.UpdateSupplierResp, error) {
	l := logic.NewUpdateSupplierLogic(ctx, s.svcCtx)
	return l.UpdateSupplier(in)
}

// rpc DelSupplier(DelSupplierReq) returns (DelSupplierResp);
func (s *SupplierServer) GetSupplierById(ctx context.Context, in *pb.GetSupplierByIdReq) (*pb.GetSupplierByIdResp, error) {
	l := logic.NewGetSupplierByIdLogic(ctx, s.svcCtx)
	return l.GetSupplierById(in)
}

func (s *SupplierServer) SearchSupplier(ctx context.Context, in *pb.SearchSupplierReq) (*pb.SearchSupplierResp, error) {
	l := logic.NewSearchSupplierLogic(ctx, s.svcCtx)
	return l.SearchSupplier(in)
}

// -----------------------supplierEvaluation-----------------------
func (s *SupplierServer) AddSupplierEvaluation(ctx context.Context, in *pb.AddSupplierEvaluationReq) (*pb.AddSupplierEvaluationResp, error) {
	l := logic.NewAddSupplierEvaluationLogic(ctx, s.svcCtx)
	return l.AddSupplierEvaluation(in)
}

// rpc UpdateSupplierEvaluation(UpdateSupplierEvaluationReq) returns (UpdateSupplierEvaluationResp);
func (s *SupplierServer) GetSupplierEvaluationById(ctx context.Context, in *pb.GetSupplierEvaluationByIdReq) (*pb.GetSupplierEvaluationByIdResp, error) {
	l := logic.NewGetSupplierEvaluationByIdLogic(ctx, s.svcCtx)
	return l.GetSupplierEvaluationById(in)
}

func (s *SupplierServer) SearchSupplierEvaluation(ctx context.Context, in *pb.SearchSupplierEvaluationReq) (*pb.SearchSupplierEvaluationResp, error) {
	l := logic.NewSearchSupplierEvaluationLogic(ctx, s.svcCtx)
	return l.SearchSupplierEvaluation(in)
}
