// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: hr.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttendanceRecord_Clock_FullMethodName                   = "/pb.attendanceRecord/Clock"
	AttendanceRecord_AttendanceChecker_FullMethodName       = "/pb.attendanceRecord/AttendanceChecker"
	AttendanceRecord_GetAttendanceRecordById_FullMethodName = "/pb.attendanceRecord/GetAttendanceRecordById"
	AttendanceRecord_SearchAttendanceRecord_FullMethodName  = "/pb.attendanceRecord/SearchAttendanceRecord"
)

// AttendanceRecordClient is the client API for AttendanceRecord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttendanceRecordClient interface {
	// -----------------------考勤记录表-----------------------
	Clock(ctx context.Context, in *ClockReq, opts ...grpc.CallOption) (*ClockResp, error)
	// rpc AddAttendanceRecord(AddAttendanceRecordReq) returns (AddAttendanceRecordResp);
	// rpc UpdateAttendanceRecord(UpdateAttendanceRecordReq) returns (UpdateAttendanceRecordResp);
	AttendanceChecker(ctx context.Context, in *AttendanceCheckerReq, opts ...grpc.CallOption) (*AttendanceCheckerResp, error)
	GetAttendanceRecordById(ctx context.Context, in *GetAttendanceRecordByIdReq, opts ...grpc.CallOption) (*GetAttendanceRecordByIdResp, error)
	SearchAttendanceRecord(ctx context.Context, in *SearchAttendanceRecordReq, opts ...grpc.CallOption) (*SearchAttendanceRecordResp, error)
}

type attendanceRecordClient struct {
	cc grpc.ClientConnInterface
}

func NewAttendanceRecordClient(cc grpc.ClientConnInterface) AttendanceRecordClient {
	return &attendanceRecordClient{cc}
}

func (c *attendanceRecordClient) Clock(ctx context.Context, in *ClockReq, opts ...grpc.CallOption) (*ClockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClockResp)
	err := c.cc.Invoke(ctx, AttendanceRecord_Clock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceRecordClient) AttendanceChecker(ctx context.Context, in *AttendanceCheckerReq, opts ...grpc.CallOption) (*AttendanceCheckerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttendanceCheckerResp)
	err := c.cc.Invoke(ctx, AttendanceRecord_AttendanceChecker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceRecordClient) GetAttendanceRecordById(ctx context.Context, in *GetAttendanceRecordByIdReq, opts ...grpc.CallOption) (*GetAttendanceRecordByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttendanceRecordByIdResp)
	err := c.cc.Invoke(ctx, AttendanceRecord_GetAttendanceRecordById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceRecordClient) SearchAttendanceRecord(ctx context.Context, in *SearchAttendanceRecordReq, opts ...grpc.CallOption) (*SearchAttendanceRecordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAttendanceRecordResp)
	err := c.cc.Invoke(ctx, AttendanceRecord_SearchAttendanceRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttendanceRecordServer is the server API for AttendanceRecord service.
// All implementations must embed UnimplementedAttendanceRecordServer
// for forward compatibility.
type AttendanceRecordServer interface {
	// -----------------------考勤记录表-----------------------
	Clock(context.Context, *ClockReq) (*ClockResp, error)
	// rpc AddAttendanceRecord(AddAttendanceRecordReq) returns (AddAttendanceRecordResp);
	// rpc UpdateAttendanceRecord(UpdateAttendanceRecordReq) returns (UpdateAttendanceRecordResp);
	AttendanceChecker(context.Context, *AttendanceCheckerReq) (*AttendanceCheckerResp, error)
	GetAttendanceRecordById(context.Context, *GetAttendanceRecordByIdReq) (*GetAttendanceRecordByIdResp, error)
	SearchAttendanceRecord(context.Context, *SearchAttendanceRecordReq) (*SearchAttendanceRecordResp, error)
	mustEmbedUnimplementedAttendanceRecordServer()
}

// UnimplementedAttendanceRecordServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttendanceRecordServer struct{}

func (UnimplementedAttendanceRecordServer) Clock(context.Context, *ClockReq) (*ClockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clock not implemented")
}
func (UnimplementedAttendanceRecordServer) AttendanceChecker(context.Context, *AttendanceCheckerReq) (*AttendanceCheckerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttendanceChecker not implemented")
}
func (UnimplementedAttendanceRecordServer) GetAttendanceRecordById(context.Context, *GetAttendanceRecordByIdReq) (*GetAttendanceRecordByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceRecordById not implemented")
}
func (UnimplementedAttendanceRecordServer) SearchAttendanceRecord(context.Context, *SearchAttendanceRecordReq) (*SearchAttendanceRecordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAttendanceRecord not implemented")
}
func (UnimplementedAttendanceRecordServer) mustEmbedUnimplementedAttendanceRecordServer() {}
func (UnimplementedAttendanceRecordServer) testEmbeddedByValue()                          {}

// UnsafeAttendanceRecordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttendanceRecordServer will
// result in compilation errors.
type UnsafeAttendanceRecordServer interface {
	mustEmbedUnimplementedAttendanceRecordServer()
}

func RegisterAttendanceRecordServer(s grpc.ServiceRegistrar, srv AttendanceRecordServer) {
	// If the following call pancis, it indicates UnimplementedAttendanceRecordServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttendanceRecord_ServiceDesc, srv)
}

func _AttendanceRecord_Clock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceRecordServer).Clock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceRecord_Clock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceRecordServer).Clock(ctx, req.(*ClockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceRecord_AttendanceChecker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttendanceCheckerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceRecordServer).AttendanceChecker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceRecord_AttendanceChecker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceRecordServer).AttendanceChecker(ctx, req.(*AttendanceCheckerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceRecord_GetAttendanceRecordById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceRecordByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceRecordServer).GetAttendanceRecordById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceRecord_GetAttendanceRecordById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceRecordServer).GetAttendanceRecordById(ctx, req.(*GetAttendanceRecordByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceRecord_SearchAttendanceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAttendanceRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceRecordServer).SearchAttendanceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceRecord_SearchAttendanceRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceRecordServer).SearchAttendanceRecord(ctx, req.(*SearchAttendanceRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AttendanceRecord_ServiceDesc is the grpc.ServiceDesc for AttendanceRecord service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttendanceRecord_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.attendanceRecord",
	HandlerType: (*AttendanceRecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Clock",
			Handler:    _AttendanceRecord_Clock_Handler,
		},
		{
			MethodName: "AttendanceChecker",
			Handler:    _AttendanceRecord_AttendanceChecker_Handler,
		},
		{
			MethodName: "GetAttendanceRecordById",
			Handler:    _AttendanceRecord_GetAttendanceRecordById_Handler,
		},
		{
			MethodName: "SearchAttendanceRecord",
			Handler:    _AttendanceRecord_SearchAttendanceRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hr.proto",
}

const (
	AttendanceReplenish_AddAttendanceReplenish_FullMethodName     = "/pb.attendanceReplenish/AddAttendanceReplenish"
	AttendanceReplenish_UpdateAttendanceReplenish_FullMethodName  = "/pb.attendanceReplenish/UpdateAttendanceReplenish"
	AttendanceReplenish_GetAttendanceReplenishById_FullMethodName = "/pb.attendanceReplenish/GetAttendanceReplenishById"
	AttendanceReplenish_SearchAttendanceReplenish_FullMethodName  = "/pb.attendanceReplenish/SearchAttendanceReplenish"
)

// AttendanceReplenishClient is the client API for AttendanceReplenish service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttendanceReplenishClient interface {
	// -----------------------补卡申请表-----------------------
	AddAttendanceReplenish(ctx context.Context, in *AddAttendanceReplenishReq, opts ...grpc.CallOption) (*AddAttendanceReplenishResp, error)
	UpdateAttendanceReplenish(ctx context.Context, in *UpdateAttendanceReplenishReq, opts ...grpc.CallOption) (*UpdateAttendanceReplenishResp, error)
	GetAttendanceReplenishById(ctx context.Context, in *GetAttendanceReplenishByIdReq, opts ...grpc.CallOption) (*GetAttendanceReplenishByIdResp, error)
	SearchAttendanceReplenish(ctx context.Context, in *SearchAttendanceReplenishReq, opts ...grpc.CallOption) (*SearchAttendanceReplenishResp, error)
}

type attendanceReplenishClient struct {
	cc grpc.ClientConnInterface
}

func NewAttendanceReplenishClient(cc grpc.ClientConnInterface) AttendanceReplenishClient {
	return &attendanceReplenishClient{cc}
}

func (c *attendanceReplenishClient) AddAttendanceReplenish(ctx context.Context, in *AddAttendanceReplenishReq, opts ...grpc.CallOption) (*AddAttendanceReplenishResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAttendanceReplenishResp)
	err := c.cc.Invoke(ctx, AttendanceReplenish_AddAttendanceReplenish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceReplenishClient) UpdateAttendanceReplenish(ctx context.Context, in *UpdateAttendanceReplenishReq, opts ...grpc.CallOption) (*UpdateAttendanceReplenishResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAttendanceReplenishResp)
	err := c.cc.Invoke(ctx, AttendanceReplenish_UpdateAttendanceReplenish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceReplenishClient) GetAttendanceReplenishById(ctx context.Context, in *GetAttendanceReplenishByIdReq, opts ...grpc.CallOption) (*GetAttendanceReplenishByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttendanceReplenishByIdResp)
	err := c.cc.Invoke(ctx, AttendanceReplenish_GetAttendanceReplenishById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceReplenishClient) SearchAttendanceReplenish(ctx context.Context, in *SearchAttendanceReplenishReq, opts ...grpc.CallOption) (*SearchAttendanceReplenishResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAttendanceReplenishResp)
	err := c.cc.Invoke(ctx, AttendanceReplenish_SearchAttendanceReplenish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttendanceReplenishServer is the server API for AttendanceReplenish service.
// All implementations must embed UnimplementedAttendanceReplenishServer
// for forward compatibility.
type AttendanceReplenishServer interface {
	// -----------------------补卡申请表-----------------------
	AddAttendanceReplenish(context.Context, *AddAttendanceReplenishReq) (*AddAttendanceReplenishResp, error)
	UpdateAttendanceReplenish(context.Context, *UpdateAttendanceReplenishReq) (*UpdateAttendanceReplenishResp, error)
	GetAttendanceReplenishById(context.Context, *GetAttendanceReplenishByIdReq) (*GetAttendanceReplenishByIdResp, error)
	SearchAttendanceReplenish(context.Context, *SearchAttendanceReplenishReq) (*SearchAttendanceReplenishResp, error)
	mustEmbedUnimplementedAttendanceReplenishServer()
}

// UnimplementedAttendanceReplenishServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttendanceReplenishServer struct{}

func (UnimplementedAttendanceReplenishServer) AddAttendanceReplenish(context.Context, *AddAttendanceReplenishReq) (*AddAttendanceReplenishResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAttendanceReplenish not implemented")
}
func (UnimplementedAttendanceReplenishServer) UpdateAttendanceReplenish(context.Context, *UpdateAttendanceReplenishReq) (*UpdateAttendanceReplenishResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttendanceReplenish not implemented")
}
func (UnimplementedAttendanceReplenishServer) GetAttendanceReplenishById(context.Context, *GetAttendanceReplenishByIdReq) (*GetAttendanceReplenishByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceReplenishById not implemented")
}
func (UnimplementedAttendanceReplenishServer) SearchAttendanceReplenish(context.Context, *SearchAttendanceReplenishReq) (*SearchAttendanceReplenishResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAttendanceReplenish not implemented")
}
func (UnimplementedAttendanceReplenishServer) mustEmbedUnimplementedAttendanceReplenishServer() {}
func (UnimplementedAttendanceReplenishServer) testEmbeddedByValue()                             {}

// UnsafeAttendanceReplenishServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttendanceReplenishServer will
// result in compilation errors.
type UnsafeAttendanceReplenishServer interface {
	mustEmbedUnimplementedAttendanceReplenishServer()
}

func RegisterAttendanceReplenishServer(s grpc.ServiceRegistrar, srv AttendanceReplenishServer) {
	// If the following call pancis, it indicates UnimplementedAttendanceReplenishServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttendanceReplenish_ServiceDesc, srv)
}

func _AttendanceReplenish_AddAttendanceReplenish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAttendanceReplenishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceReplenishServer).AddAttendanceReplenish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceReplenish_AddAttendanceReplenish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceReplenishServer).AddAttendanceReplenish(ctx, req.(*AddAttendanceReplenishReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceReplenish_UpdateAttendanceReplenish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttendanceReplenishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceReplenishServer).UpdateAttendanceReplenish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceReplenish_UpdateAttendanceReplenish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceReplenishServer).UpdateAttendanceReplenish(ctx, req.(*UpdateAttendanceReplenishReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceReplenish_GetAttendanceReplenishById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceReplenishByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceReplenishServer).GetAttendanceReplenishById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceReplenish_GetAttendanceReplenishById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceReplenishServer).GetAttendanceReplenishById(ctx, req.(*GetAttendanceReplenishByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceReplenish_SearchAttendanceReplenish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAttendanceReplenishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceReplenishServer).SearchAttendanceReplenish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceReplenish_SearchAttendanceReplenish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceReplenishServer).SearchAttendanceReplenish(ctx, req.(*SearchAttendanceReplenishReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AttendanceReplenish_ServiceDesc is the grpc.ServiceDesc for AttendanceReplenish service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttendanceReplenish_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.attendanceReplenish",
	HandlerType: (*AttendanceReplenishServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAttendanceReplenish",
			Handler:    _AttendanceReplenish_AddAttendanceReplenish_Handler,
		},
		{
			MethodName: "UpdateAttendanceReplenish",
			Handler:    _AttendanceReplenish_UpdateAttendanceReplenish_Handler,
		},
		{
			MethodName: "GetAttendanceReplenishById",
			Handler:    _AttendanceReplenish_GetAttendanceReplenishById_Handler,
		},
		{
			MethodName: "SearchAttendanceReplenish",
			Handler:    _AttendanceReplenish_SearchAttendanceReplenish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hr.proto",
}

const (
	Department_AddDepartment_FullMethodName     = "/pb.department/AddDepartment"
	Department_UpdateDepartment_FullMethodName  = "/pb.department/UpdateDepartment"
	Department_DelDepartment_FullMethodName     = "/pb.department/DelDepartment"
	Department_GetDepartmentById_FullMethodName = "/pb.department/GetDepartmentById"
	Department_SearchDepartment_FullMethodName  = "/pb.department/SearchDepartment"
)

// DepartmentClient is the client API for Department service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepartmentClient interface {
	// -----------------------部门表-----------------------
	AddDepartment(ctx context.Context, in *AddDepartmentReq, opts ...grpc.CallOption) (*AddDepartmentResp, error)
	// rpc BulkAddDepartment(BulkAddDepartmentReq) returns (BulkAddDepartmentResp);
	UpdateDepartment(ctx context.Context, in *UpdateDepartmentReq, opts ...grpc.CallOption) (*UpdateDepartmentResp, error)
	DelDepartment(ctx context.Context, in *DelDepartmentReq, opts ...grpc.CallOption) (*DelDepartmentResp, error)
	GetDepartmentById(ctx context.Context, in *GetDepartmentByIdReq, opts ...grpc.CallOption) (*GetDepartmentByIdResp, error)
	SearchDepartment(ctx context.Context, in *SearchDepartmentReq, opts ...grpc.CallOption) (*SearchDepartmentResp, error)
}

type departmentClient struct {
	cc grpc.ClientConnInterface
}

func NewDepartmentClient(cc grpc.ClientConnInterface) DepartmentClient {
	return &departmentClient{cc}
}

func (c *departmentClient) AddDepartment(ctx context.Context, in *AddDepartmentReq, opts ...grpc.CallOption) (*AddDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDepartmentResp)
	err := c.cc.Invoke(ctx, Department_AddDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentClient) UpdateDepartment(ctx context.Context, in *UpdateDepartmentReq, opts ...grpc.CallOption) (*UpdateDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDepartmentResp)
	err := c.cc.Invoke(ctx, Department_UpdateDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentClient) DelDepartment(ctx context.Context, in *DelDepartmentReq, opts ...grpc.CallOption) (*DelDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelDepartmentResp)
	err := c.cc.Invoke(ctx, Department_DelDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentClient) GetDepartmentById(ctx context.Context, in *GetDepartmentByIdReq, opts ...grpc.CallOption) (*GetDepartmentByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepartmentByIdResp)
	err := c.cc.Invoke(ctx, Department_GetDepartmentById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentClient) SearchDepartment(ctx context.Context, in *SearchDepartmentReq, opts ...grpc.CallOption) (*SearchDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDepartmentResp)
	err := c.cc.Invoke(ctx, Department_SearchDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepartmentServer is the server API for Department service.
// All implementations must embed UnimplementedDepartmentServer
// for forward compatibility.
type DepartmentServer interface {
	// -----------------------部门表-----------------------
	AddDepartment(context.Context, *AddDepartmentReq) (*AddDepartmentResp, error)
	// rpc BulkAddDepartment(BulkAddDepartmentReq) returns (BulkAddDepartmentResp);
	UpdateDepartment(context.Context, *UpdateDepartmentReq) (*UpdateDepartmentResp, error)
	DelDepartment(context.Context, *DelDepartmentReq) (*DelDepartmentResp, error)
	GetDepartmentById(context.Context, *GetDepartmentByIdReq) (*GetDepartmentByIdResp, error)
	SearchDepartment(context.Context, *SearchDepartmentReq) (*SearchDepartmentResp, error)
	mustEmbedUnimplementedDepartmentServer()
}

// UnimplementedDepartmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDepartmentServer struct{}

func (UnimplementedDepartmentServer) AddDepartment(context.Context, *AddDepartmentReq) (*AddDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDepartment not implemented")
}
func (UnimplementedDepartmentServer) UpdateDepartment(context.Context, *UpdateDepartmentReq) (*UpdateDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDepartment not implemented")
}
func (UnimplementedDepartmentServer) DelDepartment(context.Context, *DelDepartmentReq) (*DelDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelDepartment not implemented")
}
func (UnimplementedDepartmentServer) GetDepartmentById(context.Context, *GetDepartmentByIdReq) (*GetDepartmentByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartmentById not implemented")
}
func (UnimplementedDepartmentServer) SearchDepartment(context.Context, *SearchDepartmentReq) (*SearchDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDepartment not implemented")
}
func (UnimplementedDepartmentServer) mustEmbedUnimplementedDepartmentServer() {}
func (UnimplementedDepartmentServer) testEmbeddedByValue()                    {}

// UnsafeDepartmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepartmentServer will
// result in compilation errors.
type UnsafeDepartmentServer interface {
	mustEmbedUnimplementedDepartmentServer()
}

func RegisterDepartmentServer(s grpc.ServiceRegistrar, srv DepartmentServer) {
	// If the following call pancis, it indicates UnimplementedDepartmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Department_ServiceDesc, srv)
}

func _Department_AddDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServer).AddDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Department_AddDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServer).AddDepartment(ctx, req.(*AddDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Department_UpdateDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServer).UpdateDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Department_UpdateDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServer).UpdateDepartment(ctx, req.(*UpdateDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Department_DelDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServer).DelDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Department_DelDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServer).DelDepartment(ctx, req.(*DelDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Department_GetDepartmentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServer).GetDepartmentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Department_GetDepartmentById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServer).GetDepartmentById(ctx, req.(*GetDepartmentByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Department_SearchDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServer).SearchDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Department_SearchDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServer).SearchDepartment(ctx, req.(*SearchDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Department_ServiceDesc is the grpc.ServiceDesc for Department service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Department_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.department",
	HandlerType: (*DepartmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDepartment",
			Handler:    _Department_AddDepartment_Handler,
		},
		{
			MethodName: "UpdateDepartment",
			Handler:    _Department_UpdateDepartment_Handler,
		},
		{
			MethodName: "DelDepartment",
			Handler:    _Department_DelDepartment_Handler,
		},
		{
			MethodName: "GetDepartmentById",
			Handler:    _Department_GetDepartmentById_Handler,
		},
		{
			MethodName: "SearchDepartment",
			Handler:    _Department_SearchDepartment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hr.proto",
}

const (
	EmployeeDetail_AddEmployeeDetail_FullMethodName             = "/pb.employeeDetail/AddEmployeeDetail"
	EmployeeDetail_BulkAddEmployeeDetail_FullMethodName         = "/pb.employeeDetail/BulkAddEmployeeDetail"
	EmployeeDetail_UpdateEmployeeDetail_FullMethodName          = "/pb.employeeDetail/UpdateEmployeeDetail"
	EmployeeDetail_DelEmployeeDetail_FullMethodName             = "/pb.employeeDetail/DelEmployeeDetail"
	EmployeeDetail_GetEmployeeDetailByEmployeeNo_FullMethodName = "/pb.employeeDetail/GetEmployeeDetailByEmployeeNo"
	EmployeeDetail_GetEmployeeDetailById_FullMethodName         = "/pb.employeeDetail/GetEmployeeDetailById"
	EmployeeDetail_SearchEmployeeDetail_FullMethodName          = "/pb.employeeDetail/SearchEmployeeDetail"
)

// EmployeeDetailClient is the client API for EmployeeDetail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeDetailClient interface {
	// -----------------------员工信息扩展表-----------------------
	AddEmployeeDetail(ctx context.Context, in *AddEmployeeDetailReq, opts ...grpc.CallOption) (*AddEmployeeDetailResp, error)
	// 已废弃：补偿由 Msg 实现。原说明：Saga 补偿：删除新增的员工扩展信息，入参与 AddEmployeeDetailReq 相同
	//
	//	rpc CompensateAddEmployeeDetail(AddEmployeeDetailReq) returns (DelEmployeeDetailResp);
	BulkAddEmployeeDetail(ctx context.Context, in *BulkAddEmployeeDetailReq, opts ...grpc.CallOption) (*BulkAddEmployeeDetailResp, error)
	UpdateEmployeeDetail(ctx context.Context, in *UpdateEmployeeDetailReq, opts ...grpc.CallOption) (*UpdateEmployeeDetailResp, error)
	// 已废弃：补偿由 Msg 实现。原说明：Saga 补偿：将离职日期回滚为未离职（与正向同请求体，约定 leaveDate=0 表示清空）
	//
	//	rpc CompensateUpdateEmployeeDetail(UpdateEmployeeDetailReq) returns (UpdateEmployeeDetailResp);
	DelEmployeeDetail(ctx context.Context, in *DelEmployeeDetailReq, opts ...grpc.CallOption) (*DelEmployeeDetailResp, error)
	GetEmployeeDetailByEmployeeNo(ctx context.Context, in *GetEmployeeDetailByEmployeeNoReq, opts ...grpc.CallOption) (*GetEmployeeDetailByEmployeeNoResp, error)
	GetEmployeeDetailById(ctx context.Context, in *GetEmployeeDetailByIdReq, opts ...grpc.CallOption) (*GetEmployeeDetailByIdResp, error)
	SearchEmployeeDetail(ctx context.Context, in *SearchEmployeeDetailReq, opts ...grpc.CallOption) (*SearchEmployeeDetailResp, error)
}

type employeeDetailClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeDetailClient(cc grpc.ClientConnInterface) EmployeeDetailClient {
	return &employeeDetailClient{cc}
}

func (c *employeeDetailClient) AddEmployeeDetail(ctx context.Context, in *AddEmployeeDetailReq, opts ...grpc.CallOption) (*AddEmployeeDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEmployeeDetailResp)
	err := c.cc.Invoke(ctx, EmployeeDetail_AddEmployeeDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDetailClient) BulkAddEmployeeDetail(ctx context.Context, in *BulkAddEmployeeDetailReq, opts ...grpc.CallOption) (*BulkAddEmployeeDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkAddEmployeeDetailResp)
	err := c.cc.Invoke(ctx, EmployeeDetail_BulkAddEmployeeDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDetailClient) UpdateEmployeeDetail(ctx context.Context, in *UpdateEmployeeDetailReq, opts ...grpc.CallOption) (*UpdateEmployeeDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEmployeeDetailResp)
	err := c.cc.Invoke(ctx, EmployeeDetail_UpdateEmployeeDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDetailClient) DelEmployeeDetail(ctx context.Context, in *DelEmployeeDetailReq, opts ...grpc.CallOption) (*DelEmployeeDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelEmployeeDetailResp)
	err := c.cc.Invoke(ctx, EmployeeDetail_DelEmployeeDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDetailClient) GetEmployeeDetailByEmployeeNo(ctx context.Context, in *GetEmployeeDetailByEmployeeNoReq, opts ...grpc.CallOption) (*GetEmployeeDetailByEmployeeNoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeDetailByEmployeeNoResp)
	err := c.cc.Invoke(ctx, EmployeeDetail_GetEmployeeDetailByEmployeeNo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDetailClient) GetEmployeeDetailById(ctx context.Context, in *GetEmployeeDetailByIdReq, opts ...grpc.CallOption) (*GetEmployeeDetailByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeDetailByIdResp)
	err := c.cc.Invoke(ctx, EmployeeDetail_GetEmployeeDetailById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDetailClient) SearchEmployeeDetail(ctx context.Context, in *SearchEmployeeDetailReq, opts ...grpc.CallOption) (*SearchEmployeeDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEmployeeDetailResp)
	err := c.cc.Invoke(ctx, EmployeeDetail_SearchEmployeeDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeDetailServer is the server API for EmployeeDetail service.
// All implementations must embed UnimplementedEmployeeDetailServer
// for forward compatibility.
type EmployeeDetailServer interface {
	// -----------------------员工信息扩展表-----------------------
	AddEmployeeDetail(context.Context, *AddEmployeeDetailReq) (*AddEmployeeDetailResp, error)
	// 已废弃：补偿由 Msg 实现。原说明：Saga 补偿：删除新增的员工扩展信息，入参与 AddEmployeeDetailReq 相同
	//
	//	rpc CompensateAddEmployeeDetail(AddEmployeeDetailReq) returns (DelEmployeeDetailResp);
	BulkAddEmployeeDetail(context.Context, *BulkAddEmployeeDetailReq) (*BulkAddEmployeeDetailResp, error)
	UpdateEmployeeDetail(context.Context, *UpdateEmployeeDetailReq) (*UpdateEmployeeDetailResp, error)
	// 已废弃：补偿由 Msg 实现。原说明：Saga 补偿：将离职日期回滚为未离职（与正向同请求体，约定 leaveDate=0 表示清空）
	//
	//	rpc CompensateUpdateEmployeeDetail(UpdateEmployeeDetailReq) returns (UpdateEmployeeDetailResp);
	DelEmployeeDetail(context.Context, *DelEmployeeDetailReq) (*DelEmployeeDetailResp, error)
	GetEmployeeDetailByEmployeeNo(context.Context, *GetEmployeeDetailByEmployeeNoReq) (*GetEmployeeDetailByEmployeeNoResp, error)
	GetEmployeeDetailById(context.Context, *GetEmployeeDetailByIdReq) (*GetEmployeeDetailByIdResp, error)
	SearchEmployeeDetail(context.Context, *SearchEmployeeDetailReq) (*SearchEmployeeDetailResp, error)
	mustEmbedUnimplementedEmployeeDetailServer()
}

// UnimplementedEmployeeDetailServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmployeeDetailServer struct{}

func (UnimplementedEmployeeDetailServer) AddEmployeeDetail(context.Context, *AddEmployeeDetailReq) (*AddEmployeeDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEmployeeDetail not implemented")
}
func (UnimplementedEmployeeDetailServer) BulkAddEmployeeDetail(context.Context, *BulkAddEmployeeDetailReq) (*BulkAddEmployeeDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkAddEmployeeDetail not implemented")
}
func (UnimplementedEmployeeDetailServer) UpdateEmployeeDetail(context.Context, *UpdateEmployeeDetailReq) (*UpdateEmployeeDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmployeeDetail not implemented")
}
func (UnimplementedEmployeeDetailServer) DelEmployeeDetail(context.Context, *DelEmployeeDetailReq) (*DelEmployeeDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelEmployeeDetail not implemented")
}
func (UnimplementedEmployeeDetailServer) GetEmployeeDetailByEmployeeNo(context.Context, *GetEmployeeDetailByEmployeeNoReq) (*GetEmployeeDetailByEmployeeNoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeDetailByEmployeeNo not implemented")
}
func (UnimplementedEmployeeDetailServer) GetEmployeeDetailById(context.Context, *GetEmployeeDetailByIdReq) (*GetEmployeeDetailByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeDetailById not implemented")
}
func (UnimplementedEmployeeDetailServer) SearchEmployeeDetail(context.Context, *SearchEmployeeDetailReq) (*SearchEmployeeDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchEmployeeDetail not implemented")
}
func (UnimplementedEmployeeDetailServer) mustEmbedUnimplementedEmployeeDetailServer() {}
func (UnimplementedEmployeeDetailServer) testEmbeddedByValue()                        {}

// UnsafeEmployeeDetailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeDetailServer will
// result in compilation errors.
type UnsafeEmployeeDetailServer interface {
	mustEmbedUnimplementedEmployeeDetailServer()
}

func RegisterEmployeeDetailServer(s grpc.ServiceRegistrar, srv EmployeeDetailServer) {
	// If the following call pancis, it indicates UnimplementedEmployeeDetailServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmployeeDetail_ServiceDesc, srv)
}

func _EmployeeDetail_AddEmployeeDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEmployeeDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDetailServer).AddEmployeeDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeDetail_AddEmployeeDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDetailServer).AddEmployeeDetail(ctx, req.(*AddEmployeeDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDetail_BulkAddEmployeeDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkAddEmployeeDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDetailServer).BulkAddEmployeeDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeDetail_BulkAddEmployeeDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDetailServer).BulkAddEmployeeDetail(ctx, req.(*BulkAddEmployeeDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDetail_UpdateEmployeeDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmployeeDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDetailServer).UpdateEmployeeDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeDetail_UpdateEmployeeDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDetailServer).UpdateEmployeeDetail(ctx, req.(*UpdateEmployeeDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDetail_DelEmployeeDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelEmployeeDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDetailServer).DelEmployeeDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeDetail_DelEmployeeDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDetailServer).DelEmployeeDetail(ctx, req.(*DelEmployeeDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDetail_GetEmployeeDetailByEmployeeNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeDetailByEmployeeNoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDetailServer).GetEmployeeDetailByEmployeeNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeDetail_GetEmployeeDetailByEmployeeNo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDetailServer).GetEmployeeDetailByEmployeeNo(ctx, req.(*GetEmployeeDetailByEmployeeNoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDetail_GetEmployeeDetailById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeDetailByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDetailServer).GetEmployeeDetailById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeDetail_GetEmployeeDetailById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDetailServer).GetEmployeeDetailById(ctx, req.(*GetEmployeeDetailByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDetail_SearchEmployeeDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEmployeeDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDetailServer).SearchEmployeeDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeDetail_SearchEmployeeDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDetailServer).SearchEmployeeDetail(ctx, req.(*SearchEmployeeDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeDetail_ServiceDesc is the grpc.ServiceDesc for EmployeeDetail service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeDetail_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.employeeDetail",
	HandlerType: (*EmployeeDetailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEmployeeDetail",
			Handler:    _EmployeeDetail_AddEmployeeDetail_Handler,
		},
		{
			MethodName: "BulkAddEmployeeDetail",
			Handler:    _EmployeeDetail_BulkAddEmployeeDetail_Handler,
		},
		{
			MethodName: "UpdateEmployeeDetail",
			Handler:    _EmployeeDetail_UpdateEmployeeDetail_Handler,
		},
		{
			MethodName: "DelEmployeeDetail",
			Handler:    _EmployeeDetail_DelEmployeeDetail_Handler,
		},
		{
			MethodName: "GetEmployeeDetailByEmployeeNo",
			Handler:    _EmployeeDetail_GetEmployeeDetailByEmployeeNo_Handler,
		},
		{
			MethodName: "GetEmployeeDetailById",
			Handler:    _EmployeeDetail_GetEmployeeDetailById_Handler,
		},
		{
			MethodName: "SearchEmployeeDetail",
			Handler:    _EmployeeDetail_SearchEmployeeDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hr.proto",
}

const (
	LeaveApplication_AddLeaveApplication_FullMethodName     = "/pb.leaveApplication/AddLeaveApplication"
	LeaveApplication_UpdateLeaveApplication_FullMethodName  = "/pb.leaveApplication/UpdateLeaveApplication"
	LeaveApplication_GetLeaveApplicationById_FullMethodName = "/pb.leaveApplication/GetLeaveApplicationById"
	LeaveApplication_SearchLeaveApplication_FullMethodName  = "/pb.leaveApplication/SearchLeaveApplication"
)

// LeaveApplicationClient is the client API for LeaveApplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaveApplicationClient interface {
	// -----------------------请假申请表-----------------------
	AddLeaveApplication(ctx context.Context, in *AddLeaveApplicationReq, opts ...grpc.CallOption) (*AddLeaveApplicationResp, error)
	UpdateLeaveApplication(ctx context.Context, in *UpdateLeaveApplicationReq, opts ...grpc.CallOption) (*UpdateLeaveApplicationResp, error)
	GetLeaveApplicationById(ctx context.Context, in *GetLeaveApplicationByIdReq, opts ...grpc.CallOption) (*GetLeaveApplicationByIdResp, error)
	SearchLeaveApplication(ctx context.Context, in *SearchLeaveApplicationReq, opts ...grpc.CallOption) (*SearchLeaveApplicationResp, error)
}

type leaveApplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaveApplicationClient(cc grpc.ClientConnInterface) LeaveApplicationClient {
	return &leaveApplicationClient{cc}
}

func (c *leaveApplicationClient) AddLeaveApplication(ctx context.Context, in *AddLeaveApplicationReq, opts ...grpc.CallOption) (*AddLeaveApplicationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLeaveApplicationResp)
	err := c.cc.Invoke(ctx, LeaveApplication_AddLeaveApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaveApplicationClient) UpdateLeaveApplication(ctx context.Context, in *UpdateLeaveApplicationReq, opts ...grpc.CallOption) (*UpdateLeaveApplicationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLeaveApplicationResp)
	err := c.cc.Invoke(ctx, LeaveApplication_UpdateLeaveApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaveApplicationClient) GetLeaveApplicationById(ctx context.Context, in *GetLeaveApplicationByIdReq, opts ...grpc.CallOption) (*GetLeaveApplicationByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaveApplicationByIdResp)
	err := c.cc.Invoke(ctx, LeaveApplication_GetLeaveApplicationById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaveApplicationClient) SearchLeaveApplication(ctx context.Context, in *SearchLeaveApplicationReq, opts ...grpc.CallOption) (*SearchLeaveApplicationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchLeaveApplicationResp)
	err := c.cc.Invoke(ctx, LeaveApplication_SearchLeaveApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaveApplicationServer is the server API for LeaveApplication service.
// All implementations must embed UnimplementedLeaveApplicationServer
// for forward compatibility.
type LeaveApplicationServer interface {
	// -----------------------请假申请表-----------------------
	AddLeaveApplication(context.Context, *AddLeaveApplicationReq) (*AddLeaveApplicationResp, error)
	UpdateLeaveApplication(context.Context, *UpdateLeaveApplicationReq) (*UpdateLeaveApplicationResp, error)
	GetLeaveApplicationById(context.Context, *GetLeaveApplicationByIdReq) (*GetLeaveApplicationByIdResp, error)
	SearchLeaveApplication(context.Context, *SearchLeaveApplicationReq) (*SearchLeaveApplicationResp, error)
	mustEmbedUnimplementedLeaveApplicationServer()
}

// UnimplementedLeaveApplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaveApplicationServer struct{}

func (UnimplementedLeaveApplicationServer) AddLeaveApplication(context.Context, *AddLeaveApplicationReq) (*AddLeaveApplicationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLeaveApplication not implemented")
}
func (UnimplementedLeaveApplicationServer) UpdateLeaveApplication(context.Context, *UpdateLeaveApplicationReq) (*UpdateLeaveApplicationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLeaveApplication not implemented")
}
func (UnimplementedLeaveApplicationServer) GetLeaveApplicationById(context.Context, *GetLeaveApplicationByIdReq) (*GetLeaveApplicationByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaveApplicationById not implemented")
}
func (UnimplementedLeaveApplicationServer) SearchLeaveApplication(context.Context, *SearchLeaveApplicationReq) (*SearchLeaveApplicationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchLeaveApplication not implemented")
}
func (UnimplementedLeaveApplicationServer) mustEmbedUnimplementedLeaveApplicationServer() {}
func (UnimplementedLeaveApplicationServer) testEmbeddedByValue()                          {}

// UnsafeLeaveApplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaveApplicationServer will
// result in compilation errors.
type UnsafeLeaveApplicationServer interface {
	mustEmbedUnimplementedLeaveApplicationServer()
}

func RegisterLeaveApplicationServer(s grpc.ServiceRegistrar, srv LeaveApplicationServer) {
	// If the following call pancis, it indicates UnimplementedLeaveApplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaveApplication_ServiceDesc, srv)
}

func _LeaveApplication_AddLeaveApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLeaveApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaveApplicationServer).AddLeaveApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaveApplication_AddLeaveApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaveApplicationServer).AddLeaveApplication(ctx, req.(*AddLeaveApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaveApplication_UpdateLeaveApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLeaveApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaveApplicationServer).UpdateLeaveApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaveApplication_UpdateLeaveApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaveApplicationServer).UpdateLeaveApplication(ctx, req.(*UpdateLeaveApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaveApplication_GetLeaveApplicationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaveApplicationByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaveApplicationServer).GetLeaveApplicationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaveApplication_GetLeaveApplicationById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaveApplicationServer).GetLeaveApplicationById(ctx, req.(*GetLeaveApplicationByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaveApplication_SearchLeaveApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLeaveApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaveApplicationServer).SearchLeaveApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaveApplication_SearchLeaveApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaveApplicationServer).SearchLeaveApplication(ctx, req.(*SearchLeaveApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaveApplication_ServiceDesc is the grpc.ServiceDesc for LeaveApplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaveApplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.leaveApplication",
	HandlerType: (*LeaveApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLeaveApplication",
			Handler:    _LeaveApplication_AddLeaveApplication_Handler,
		},
		{
			MethodName: "UpdateLeaveApplication",
			Handler:    _LeaveApplication_UpdateLeaveApplication_Handler,
		},
		{
			MethodName: "GetLeaveApplicationById",
			Handler:    _LeaveApplication_GetLeaveApplicationById_Handler,
		},
		{
			MethodName: "SearchLeaveApplication",
			Handler:    _LeaveApplication_SearchLeaveApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hr.proto",
}

const (
	PayrollRecord_AddPayrollRecord_FullMethodName       = "/pb.payrollRecord/AddPayrollRecord"
	PayrollRecord_BulkAddPayrollRecord_FullMethodName   = "/pb.payrollRecord/BulkAddPayrollRecord"
	PayrollRecord_UpdatePayrollRecord_FullMethodName    = "/pb.payrollRecord/UpdatePayrollRecord"
	PayrollRecord_GetPayrollRecordById_FullMethodName   = "/pb.payrollRecord/GetPayrollRecordById"
	PayrollRecord_SearchPayrollRecord_FullMethodName    = "/pb.payrollRecord/SearchPayrollRecord"
	PayrollRecord_GenerateMonthlyPayroll_FullMethodName = "/pb.payrollRecord/GenerateMonthlyPayroll"
)

// PayrollRecordClient is the client API for PayrollRecord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayrollRecordClient interface {
	// -----------------------payrollRecord-----------------------
	AddPayrollRecord(ctx context.Context, in *AddPayrollRecordReq, opts ...grpc.CallOption) (*AddPayrollRecordResp, error)
	BulkAddPayrollRecord(ctx context.Context, in *BulkAddPayrollRecordReq, opts ...grpc.CallOption) (*BulkAddPayrollRecordResp, error)
	UpdatePayrollRecord(ctx context.Context, in *UpdatePayrollRecordReq, opts ...grpc.CallOption) (*UpdatePayrollRecordResp, error)
	// rpc DelPayrollRecord(DelPayrollRecordReq) returns (DelPayrollRecordResp);
	GetPayrollRecordById(ctx context.Context, in *GetPayrollRecordByIdReq, opts ...grpc.CallOption) (*GetPayrollRecordByIdResp, error)
	SearchPayrollRecord(ctx context.Context, in *SearchPayrollRecordReq, opts ...grpc.CallOption) (*SearchPayrollRecordResp, error)
	// 新增：按月份批量生成工资单
	GenerateMonthlyPayroll(ctx context.Context, in *GenerateMonthlyPayrollReq, opts ...grpc.CallOption) (*GenerateMonthlyPayrollResp, error)
}

type payrollRecordClient struct {
	cc grpc.ClientConnInterface
}

func NewPayrollRecordClient(cc grpc.ClientConnInterface) PayrollRecordClient {
	return &payrollRecordClient{cc}
}

func (c *payrollRecordClient) AddPayrollRecord(ctx context.Context, in *AddPayrollRecordReq, opts ...grpc.CallOption) (*AddPayrollRecordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPayrollRecordResp)
	err := c.cc.Invoke(ctx, PayrollRecord_AddPayrollRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrollRecordClient) BulkAddPayrollRecord(ctx context.Context, in *BulkAddPayrollRecordReq, opts ...grpc.CallOption) (*BulkAddPayrollRecordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkAddPayrollRecordResp)
	err := c.cc.Invoke(ctx, PayrollRecord_BulkAddPayrollRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrollRecordClient) UpdatePayrollRecord(ctx context.Context, in *UpdatePayrollRecordReq, opts ...grpc.CallOption) (*UpdatePayrollRecordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePayrollRecordResp)
	err := c.cc.Invoke(ctx, PayrollRecord_UpdatePayrollRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrollRecordClient) GetPayrollRecordById(ctx context.Context, in *GetPayrollRecordByIdReq, opts ...grpc.CallOption) (*GetPayrollRecordByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayrollRecordByIdResp)
	err := c.cc.Invoke(ctx, PayrollRecord_GetPayrollRecordById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrollRecordClient) SearchPayrollRecord(ctx context.Context, in *SearchPayrollRecordReq, opts ...grpc.CallOption) (*SearchPayrollRecordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPayrollRecordResp)
	err := c.cc.Invoke(ctx, PayrollRecord_SearchPayrollRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrollRecordClient) GenerateMonthlyPayroll(ctx context.Context, in *GenerateMonthlyPayrollReq, opts ...grpc.CallOption) (*GenerateMonthlyPayrollResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateMonthlyPayrollResp)
	err := c.cc.Invoke(ctx, PayrollRecord_GenerateMonthlyPayroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayrollRecordServer is the server API for PayrollRecord service.
// All implementations must embed UnimplementedPayrollRecordServer
// for forward compatibility.
type PayrollRecordServer interface {
	// -----------------------payrollRecord-----------------------
	AddPayrollRecord(context.Context, *AddPayrollRecordReq) (*AddPayrollRecordResp, error)
	BulkAddPayrollRecord(context.Context, *BulkAddPayrollRecordReq) (*BulkAddPayrollRecordResp, error)
	UpdatePayrollRecord(context.Context, *UpdatePayrollRecordReq) (*UpdatePayrollRecordResp, error)
	// rpc DelPayrollRecord(DelPayrollRecordReq) returns (DelPayrollRecordResp);
	GetPayrollRecordById(context.Context, *GetPayrollRecordByIdReq) (*GetPayrollRecordByIdResp, error)
	SearchPayrollRecord(context.Context, *SearchPayrollRecordReq) (*SearchPayrollRecordResp, error)
	// 新增：按月份批量生成工资单
	GenerateMonthlyPayroll(context.Context, *GenerateMonthlyPayrollReq) (*GenerateMonthlyPayrollResp, error)
	mustEmbedUnimplementedPayrollRecordServer()
}

// UnimplementedPayrollRecordServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayrollRecordServer struct{}

func (UnimplementedPayrollRecordServer) AddPayrollRecord(context.Context, *AddPayrollRecordReq) (*AddPayrollRecordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPayrollRecord not implemented")
}
func (UnimplementedPayrollRecordServer) BulkAddPayrollRecord(context.Context, *BulkAddPayrollRecordReq) (*BulkAddPayrollRecordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkAddPayrollRecord not implemented")
}
func (UnimplementedPayrollRecordServer) UpdatePayrollRecord(context.Context, *UpdatePayrollRecordReq) (*UpdatePayrollRecordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePayrollRecord not implemented")
}
func (UnimplementedPayrollRecordServer) GetPayrollRecordById(context.Context, *GetPayrollRecordByIdReq) (*GetPayrollRecordByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayrollRecordById not implemented")
}
func (UnimplementedPayrollRecordServer) SearchPayrollRecord(context.Context, *SearchPayrollRecordReq) (*SearchPayrollRecordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPayrollRecord not implemented")
}
func (UnimplementedPayrollRecordServer) GenerateMonthlyPayroll(context.Context, *GenerateMonthlyPayrollReq) (*GenerateMonthlyPayrollResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateMonthlyPayroll not implemented")
}
func (UnimplementedPayrollRecordServer) mustEmbedUnimplementedPayrollRecordServer() {}
func (UnimplementedPayrollRecordServer) testEmbeddedByValue()                       {}

// UnsafePayrollRecordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayrollRecordServer will
// result in compilation errors.
type UnsafePayrollRecordServer interface {
	mustEmbedUnimplementedPayrollRecordServer()
}

func RegisterPayrollRecordServer(s grpc.ServiceRegistrar, srv PayrollRecordServer) {
	// If the following call pancis, it indicates UnimplementedPayrollRecordServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayrollRecord_ServiceDesc, srv)
}

func _PayrollRecord_AddPayrollRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPayrollRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrollRecordServer).AddPayrollRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayrollRecord_AddPayrollRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrollRecordServer).AddPayrollRecord(ctx, req.(*AddPayrollRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayrollRecord_BulkAddPayrollRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkAddPayrollRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrollRecordServer).BulkAddPayrollRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayrollRecord_BulkAddPayrollRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrollRecordServer).BulkAddPayrollRecord(ctx, req.(*BulkAddPayrollRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayrollRecord_UpdatePayrollRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePayrollRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrollRecordServer).UpdatePayrollRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayrollRecord_UpdatePayrollRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrollRecordServer).UpdatePayrollRecord(ctx, req.(*UpdatePayrollRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayrollRecord_GetPayrollRecordById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayrollRecordByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrollRecordServer).GetPayrollRecordById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayrollRecord_GetPayrollRecordById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrollRecordServer).GetPayrollRecordById(ctx, req.(*GetPayrollRecordByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayrollRecord_SearchPayrollRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPayrollRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrollRecordServer).SearchPayrollRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayrollRecord_SearchPayrollRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrollRecordServer).SearchPayrollRecord(ctx, req.(*SearchPayrollRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayrollRecord_GenerateMonthlyPayroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMonthlyPayrollReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrollRecordServer).GenerateMonthlyPayroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayrollRecord_GenerateMonthlyPayroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrollRecordServer).GenerateMonthlyPayroll(ctx, req.(*GenerateMonthlyPayrollReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PayrollRecord_ServiceDesc is the grpc.ServiceDesc for PayrollRecord service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayrollRecord_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.payrollRecord",
	HandlerType: (*PayrollRecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPayrollRecord",
			Handler:    _PayrollRecord_AddPayrollRecord_Handler,
		},
		{
			MethodName: "BulkAddPayrollRecord",
			Handler:    _PayrollRecord_BulkAddPayrollRecord_Handler,
		},
		{
			MethodName: "UpdatePayrollRecord",
			Handler:    _PayrollRecord_UpdatePayrollRecord_Handler,
		},
		{
			MethodName: "GetPayrollRecordById",
			Handler:    _PayrollRecord_GetPayrollRecordById_Handler,
		},
		{
			MethodName: "SearchPayrollRecord",
			Handler:    _PayrollRecord_SearchPayrollRecord_Handler,
		},
		{
			MethodName: "GenerateMonthlyPayroll",
			Handler:    _PayrollRecord_GenerateMonthlyPayroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hr.proto",
}

const (
	Position_AddPosition_FullMethodName     = "/pb.position/AddPosition"
	Position_UpdatePosition_FullMethodName  = "/pb.position/UpdatePosition"
	Position_DelPosition_FullMethodName     = "/pb.position/DelPosition"
	Position_GetPositionById_FullMethodName = "/pb.position/GetPositionById"
	Position_SearchPosition_FullMethodName  = "/pb.position/SearchPosition"
)

// PositionClient is the client API for Position service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PositionClient interface {
	// -----------------------岗位表-----------------------
	AddPosition(ctx context.Context, in *AddPositionReq, opts ...grpc.CallOption) (*AddPositionResp, error)
	UpdatePosition(ctx context.Context, in *UpdatePositionReq, opts ...grpc.CallOption) (*UpdatePositionResp, error)
	DelPosition(ctx context.Context, in *DelPositionReq, opts ...grpc.CallOption) (*DelPositionResp, error)
	GetPositionById(ctx context.Context, in *GetPositionByIdReq, opts ...grpc.CallOption) (*GetPositionByIdResp, error)
	SearchPosition(ctx context.Context, in *SearchPositionReq, opts ...grpc.CallOption) (*SearchPositionResp, error)
}

type positionClient struct {
	cc grpc.ClientConnInterface
}

func NewPositionClient(cc grpc.ClientConnInterface) PositionClient {
	return &positionClient{cc}
}

func (c *positionClient) AddPosition(ctx context.Context, in *AddPositionReq, opts ...grpc.CallOption) (*AddPositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPositionResp)
	err := c.cc.Invoke(ctx, Position_AddPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionClient) UpdatePosition(ctx context.Context, in *UpdatePositionReq, opts ...grpc.CallOption) (*UpdatePositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePositionResp)
	err := c.cc.Invoke(ctx, Position_UpdatePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionClient) DelPosition(ctx context.Context, in *DelPositionReq, opts ...grpc.CallOption) (*DelPositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelPositionResp)
	err := c.cc.Invoke(ctx, Position_DelPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionClient) GetPositionById(ctx context.Context, in *GetPositionByIdReq, opts ...grpc.CallOption) (*GetPositionByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPositionByIdResp)
	err := c.cc.Invoke(ctx, Position_GetPositionById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionClient) SearchPosition(ctx context.Context, in *SearchPositionReq, opts ...grpc.CallOption) (*SearchPositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPositionResp)
	err := c.cc.Invoke(ctx, Position_SearchPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PositionServer is the server API for Position service.
// All implementations must embed UnimplementedPositionServer
// for forward compatibility.
type PositionServer interface {
	// -----------------------岗位表-----------------------
	AddPosition(context.Context, *AddPositionReq) (*AddPositionResp, error)
	UpdatePosition(context.Context, *UpdatePositionReq) (*UpdatePositionResp, error)
	DelPosition(context.Context, *DelPositionReq) (*DelPositionResp, error)
	GetPositionById(context.Context, *GetPositionByIdReq) (*GetPositionByIdResp, error)
	SearchPosition(context.Context, *SearchPositionReq) (*SearchPositionResp, error)
	mustEmbedUnimplementedPositionServer()
}

// UnimplementedPositionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPositionServer struct{}

func (UnimplementedPositionServer) AddPosition(context.Context, *AddPositionReq) (*AddPositionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPosition not implemented")
}
func (UnimplementedPositionServer) UpdatePosition(context.Context, *UpdatePositionReq) (*UpdatePositionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePosition not implemented")
}
func (UnimplementedPositionServer) DelPosition(context.Context, *DelPositionReq) (*DelPositionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelPosition not implemented")
}
func (UnimplementedPositionServer) GetPositionById(context.Context, *GetPositionByIdReq) (*GetPositionByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPositionById not implemented")
}
func (UnimplementedPositionServer) SearchPosition(context.Context, *SearchPositionReq) (*SearchPositionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPosition not implemented")
}
func (UnimplementedPositionServer) mustEmbedUnimplementedPositionServer() {}
func (UnimplementedPositionServer) testEmbeddedByValue()                  {}

// UnsafePositionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PositionServer will
// result in compilation errors.
type UnsafePositionServer interface {
	mustEmbedUnimplementedPositionServer()
}

func RegisterPositionServer(s grpc.ServiceRegistrar, srv PositionServer) {
	// If the following call pancis, it indicates UnimplementedPositionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Position_ServiceDesc, srv)
}

func _Position_AddPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).AddPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_AddPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).AddPosition(ctx, req.(*AddPositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Position_UpdatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).UpdatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_UpdatePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).UpdatePosition(ctx, req.(*UpdatePositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Position_DelPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).DelPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_DelPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).DelPosition(ctx, req.(*DelPositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Position_GetPositionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).GetPositionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_GetPositionById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).GetPositionById(ctx, req.(*GetPositionByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Position_SearchPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).SearchPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_SearchPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).SearchPosition(ctx, req.(*SearchPositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Position_ServiceDesc is the grpc.ServiceDesc for Position service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Position_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.position",
	HandlerType: (*PositionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPosition",
			Handler:    _Position_AddPosition_Handler,
		},
		{
			MethodName: "UpdatePosition",
			Handler:    _Position_UpdatePosition_Handler,
		},
		{
			MethodName: "DelPosition",
			Handler:    _Position_DelPosition_Handler,
		},
		{
			MethodName: "GetPositionById",
			Handler:    _Position_GetPositionById_Handler,
		},
		{
			MethodName: "SearchPosition",
			Handler:    _Position_SearchPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hr.proto",
}

const (
	ResignedApplication_AddResignedApplication_FullMethodName     = "/pb.resignedApplication/AddResignedApplication"
	ResignedApplication_UpdateResignedApplication_FullMethodName  = "/pb.resignedApplication/UpdateResignedApplication"
	ResignedApplication_GetResignedApplicationById_FullMethodName = "/pb.resignedApplication/GetResignedApplicationById"
	ResignedApplication_SearchResignedApplication_FullMethodName  = "/pb.resignedApplication/SearchResignedApplication"
)

// ResignedApplicationClient is the client API for ResignedApplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResignedApplicationClient interface {
	// -----------------------离职申请表-----------------------
	AddResignedApplication(ctx context.Context, in *AddResignedApplicationReq, opts ...grpc.CallOption) (*AddResignedApplicationResp, error)
	UpdateResignedApplication(ctx context.Context, in *UpdateResignedApplicationReq, opts ...grpc.CallOption) (*UpdateResignedApplicationResp, error)
	GetResignedApplicationById(ctx context.Context, in *GetResignedApplicationByIdReq, opts ...grpc.CallOption) (*GetResignedApplicationByIdResp, error)
	SearchResignedApplication(ctx context.Context, in *SearchResignedApplicationReq, opts ...grpc.CallOption) (*SearchResignedApplicationResp, error)
}

type resignedApplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewResignedApplicationClient(cc grpc.ClientConnInterface) ResignedApplicationClient {
	return &resignedApplicationClient{cc}
}

func (c *resignedApplicationClient) AddResignedApplication(ctx context.Context, in *AddResignedApplicationReq, opts ...grpc.CallOption) (*AddResignedApplicationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResignedApplicationResp)
	err := c.cc.Invoke(ctx, ResignedApplication_AddResignedApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resignedApplicationClient) UpdateResignedApplication(ctx context.Context, in *UpdateResignedApplicationReq, opts ...grpc.CallOption) (*UpdateResignedApplicationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResignedApplicationResp)
	err := c.cc.Invoke(ctx, ResignedApplication_UpdateResignedApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resignedApplicationClient) GetResignedApplicationById(ctx context.Context, in *GetResignedApplicationByIdReq, opts ...grpc.CallOption) (*GetResignedApplicationByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResignedApplicationByIdResp)
	err := c.cc.Invoke(ctx, ResignedApplication_GetResignedApplicationById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resignedApplicationClient) SearchResignedApplication(ctx context.Context, in *SearchResignedApplicationReq, opts ...grpc.CallOption) (*SearchResignedApplicationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResignedApplicationResp)
	err := c.cc.Invoke(ctx, ResignedApplication_SearchResignedApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResignedApplicationServer is the server API for ResignedApplication service.
// All implementations must embed UnimplementedResignedApplicationServer
// for forward compatibility.
type ResignedApplicationServer interface {
	// -----------------------离职申请表-----------------------
	AddResignedApplication(context.Context, *AddResignedApplicationReq) (*AddResignedApplicationResp, error)
	UpdateResignedApplication(context.Context, *UpdateResignedApplicationReq) (*UpdateResignedApplicationResp, error)
	GetResignedApplicationById(context.Context, *GetResignedApplicationByIdReq) (*GetResignedApplicationByIdResp, error)
	SearchResignedApplication(context.Context, *SearchResignedApplicationReq) (*SearchResignedApplicationResp, error)
	mustEmbedUnimplementedResignedApplicationServer()
}

// UnimplementedResignedApplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResignedApplicationServer struct{}

func (UnimplementedResignedApplicationServer) AddResignedApplication(context.Context, *AddResignedApplicationReq) (*AddResignedApplicationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddResignedApplication not implemented")
}
func (UnimplementedResignedApplicationServer) UpdateResignedApplication(context.Context, *UpdateResignedApplicationReq) (*UpdateResignedApplicationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResignedApplication not implemented")
}
func (UnimplementedResignedApplicationServer) GetResignedApplicationById(context.Context, *GetResignedApplicationByIdReq) (*GetResignedApplicationByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResignedApplicationById not implemented")
}
func (UnimplementedResignedApplicationServer) SearchResignedApplication(context.Context, *SearchResignedApplicationReq) (*SearchResignedApplicationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchResignedApplication not implemented")
}
func (UnimplementedResignedApplicationServer) mustEmbedUnimplementedResignedApplicationServer() {}
func (UnimplementedResignedApplicationServer) testEmbeddedByValue()                             {}

// UnsafeResignedApplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResignedApplicationServer will
// result in compilation errors.
type UnsafeResignedApplicationServer interface {
	mustEmbedUnimplementedResignedApplicationServer()
}

func RegisterResignedApplicationServer(s grpc.ServiceRegistrar, srv ResignedApplicationServer) {
	// If the following call pancis, it indicates UnimplementedResignedApplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResignedApplication_ServiceDesc, srv)
}

func _ResignedApplication_AddResignedApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddResignedApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResignedApplicationServer).AddResignedApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResignedApplication_AddResignedApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResignedApplicationServer).AddResignedApplication(ctx, req.(*AddResignedApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResignedApplication_UpdateResignedApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResignedApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResignedApplicationServer).UpdateResignedApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResignedApplication_UpdateResignedApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResignedApplicationServer).UpdateResignedApplication(ctx, req.(*UpdateResignedApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResignedApplication_GetResignedApplicationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResignedApplicationByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResignedApplicationServer).GetResignedApplicationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResignedApplication_GetResignedApplicationById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResignedApplicationServer).GetResignedApplicationById(ctx, req.(*GetResignedApplicationByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResignedApplication_SearchResignedApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchResignedApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResignedApplicationServer).SearchResignedApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResignedApplication_SearchResignedApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResignedApplicationServer).SearchResignedApplication(ctx, req.(*SearchResignedApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ResignedApplication_ServiceDesc is the grpc.ServiceDesc for ResignedApplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResignedApplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.resignedApplication",
	HandlerType: (*ResignedApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddResignedApplication",
			Handler:    _ResignedApplication_AddResignedApplication_Handler,
		},
		{
			MethodName: "UpdateResignedApplication",
			Handler:    _ResignedApplication_UpdateResignedApplication_Handler,
		},
		{
			MethodName: "GetResignedApplicationById",
			Handler:    _ResignedApplication_GetResignedApplicationById_Handler,
		},
		{
			MethodName: "SearchResignedApplication",
			Handler:    _ResignedApplication_SearchResignedApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hr.proto",
}
