// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type ApproveRequisitionReq struct {
	Id     string `json:"id"`
	Status int64  `json:"status"` // 2-已审批 3-已驳回
}

type ApproveRequisitionResp struct {
}

type BomInfo struct {
	Id            string        `json:"id"`
	BomNo         string        `json:"bom_no"`
	ProductId     string        `json:"product_id"`
	ProductNo     string        `json:"product_no"`
	ProductName   string        `json:"product_name"`
	Version       string        `json:"version"`
	UnitCost      float64       `json:"unit_cost"`
	IsActive      int64         `json:"is_active"` // 1-启用 2-停用
	Remark        string        `json:"remark,optional"`
	CreatedAt     int64         `json:"created_at"`
	CreatedById   string        `json:"created_by_id"`
	CreatedByNo   string        `json:"created_by_no"`
	CreatedByName string        `json:"created_by_name"`
	UpdatedAt     int64         `json:"updated_at,optional"`
	UpdatedById   string        `json:"updated_by_id,optional"`
	UpdatedByNo   string        `json:"updated_by_no,optional"`
	UpdatedByName string        `json:"updated_by_name,optional"`
	Items         []BomItemInfo `json:"items,optional"`
}

type BomItemInfo struct {
	Id           string  `json:"id"`
	BomId        string  `json:"bom_id"`
	MaterialId   string  `json:"material_id"`
	MaterialNo   string  `json:"material_no"`
	MaterialName string  `json:"material_name"`
	Quantity     float64 `json:"quantity"`
	Unit         string  `json:"unit,optional"`
	ScrapRate    float64 `json:"scrap_rate"`
	Remark       string  `json:"remark,optional"`
}

type BomListReq struct {
	Page      int64  `form:"page,default=1"`
	PageSize  int64  `form:"page_size,default=10"`
	ProductId string `form:"product_id,optional"`
	IsActive  int64  `form:"is_active,optional"`
}

type BomListResp struct {
	Total int64     `json:"total"`
	List  []BomInfo `json:"list"`
}

type CreateBomItemReq struct {
	BomId      string  `json:"bom_id"`
	MaterialId string  `json:"material_id"`
	Quantity   float64 `json:"quantity"`
	Unit       string  `json:"unit,optional"`
	ScrapRate  float64 `json:"scrap_rate,optional,default=0"`
	Remark     string  `json:"remark,optional"`
}

type CreateBomItemResp struct {
}

type CreateBomReq struct {
	ProductId string `json:"product_id"`
	Version   string `json:"version,optional,default=1.0"`
	Remark    string `json:"remark,optional"`
}

type CreateBomResp struct {
	Id string `json:"id"`
}

type CreateRequisitionItemReq struct {
	RequisitionId  string  `json:"requisition_id"`
	MaterialId     string  `json:"material_id"`
	PlanQuantity   float64 `json:"plan_quantity"`
	ActualQuantity float64 `json:"actual_quantity,optional,default=0"`
	Unit           string  `json:"unit,optional"`
	BatchNo        string  `json:"batch_no,optional"`
	Remark         string  `json:"remark,optional"`
}

type CreateRequisitionItemResp struct {
}

type CreateRequisitionReq struct {
	WorkOrderId     string `json:"work_order_id"`
	WarehouseId     string `json:"warehouse_id"`
	RequisitionDate int64  `json:"requisition_date"`
	ApprovedById    string `json:"approved_by_id"`
}

type CreateRequisitionResp struct {
	Id string `json:"id"`
}

type CreateWorkOrderReq struct {
	ProductId     string  `json:"product_id"`
	BomId         string  `json:"bom_id,optional"`
	Quantity      float64 `json:"quantity"`
	WarehouseId   string  `json:"warehouse_id,optional"`
	Priority      int64   `json:"priority,optional,default=2"`
	PlanStartDate int64   `json:"plan_start_date,optional"`
	PlanEndDate   int64   `json:"plan_end_date,optional"`
	Workshop      string  `json:"workshop,optional"`
	Remark        string  `json:"remark,optional"`
}

type CreateWorkOrderResp struct {
}

type DeleteBomItemResp struct {
}

type DeleteBomResp struct {
}

type DeleteRequisitionItemResp struct {
}

type DeleteWorkOrderResp struct {
}

type IdReq struct {
	Id string `path:"id"`
}

type RequisitionInfo struct {
	Id              string                `json:"id"`
	RequisitionNo   string                `json:"requisition_no"`
	WorkOrderId     string                `json:"work_order_id"`
	WorkOrderNo     string                `json:"work_order_no,optional"`
	WarehouseId     string                `json:"warehouse_id"`
	WarehouseNo     string                `json:"warehouse_no"`
	WarehouseName   string                `json:"warehouse_name,optional"`
	ProductId       string                `json:"product_id"`
	ProductName     string                `json:"product_name"`
	RequisitionDate int64                 `json:"requisition_date"`
	Status          int64                 `json:"status"` // 1-待审批 2-已审批 3-已驳回 4-已出库
	ApprovedById    string                `json:"approved_by_id,optional"`
	ApprovedByNo    string                `json:"approved_by_no,optional"`
	ApprovedByName  string                `json:"approved_by_name,optional"`
	ApprovedAt      int64                 `json:"approved_at,optional"`
	CreatedAt       int64                 `json:"created_at"`
	CreatedById     string                `json:"created_by_id"`
	CreatedByNo     string                `json:"created_by_no"`
	CreatedByName   string                `json:"created_by_name"`
	UpdatedAt       int64                 `json:"updated_at,optional"`
	UpdatedById     string                `json:"updated_by_id,optional"`
	UpdatedByNo     string                `json:"updated_by_no,optional"`
	UpdatedByName   string                `json:"updated_by_name,optional"`
	Items           []RequisitionItemInfo `json:"items,optional"`
}

type RequisitionItemInfo struct {
	Id             string  `json:"id"`
	RequisitionId  string  `json:"requisition_id"`
	MaterialId     string  `json:"material_id"`
	MaterialName   string  `json:"material_name,optional"`
	PlanQuantity   float64 `json:"plan_quantity"`
	ActualQuantity float64 `json:"actual_quantity"`
	Unit           string  `json:"unit,optional"`
	BatchNo        string  `json:"batch_no,optional"`
	Remark         string  `json:"remark,optional"`
}

type RequisitionListReq struct {
	Page        int64  `form:"page,default=1"`
	PageSize    int64  `form:"page_size,default=10"`
	WorkOrderId string `form:"work_order_id,optional"`
	WarehouseId string `form:"warehouse_id,optional"`
	Status      int64  `form:"status,optional"`
}

type RequisitionListResp struct {
	Total int64             `json:"total"`
	List  []RequisitionInfo `json:"list"`
}

type UpdateBomItemReq struct {
	Id         string  `json:"id"`
	MaterialId string  `json:"material_id,optional"`
	Quantity   float64 `json:"quantity,optional"`
	Unit       string  `json:"unit,optional"`
	ScrapRate  float64 `json:"scrap_rate,optional"`
	Remark     string  `json:"remark,optional"`
}

type UpdateBomItemResp struct {
}

type UpdateBomReq struct {
	Id       string `json:"id"`
	Version  string `json:"version,optional"`
	IsActive int64  `json:"is_active,optional"`
	Remark   string `json:"remark,optional"`
}

type UpdateBomResp struct {
}

type UpdateRequisitionItemReq struct {
	Id             string  `json:"id"`
	MaterialId     string  `json:"material_id,optional"`
	PlanQuantity   float64 `json:"plan_quantity,optional"`
	ActualQuantity float64 `json:"actual_quantity,optional"`
	Unit           string  `json:"unit,optional"`
	BatchNo        string  `json:"batch_no,optional"`
	Remark         string  `json:"remark,optional"`
}

type UpdateRequisitionItemResp struct {
}

type UpdateRequisitionReq struct {
	Id     string `json:"id"`
	Status int64  `json:"status,optional"`
}

type UpdateRequisitionResp struct {
}

type UpdateWorkOrderReq struct {
	Id              string  `json:"id"`
	Quantity        float64 `json:"quantity,optional"`
	CompletedQty    float64 `json:"completed_qty,optional"`
	QualifiedQty    float64 `json:"qualified_qty,optional"`
	DefectiveQty    float64 `json:"defective_qty,optional"`
	Status          int64   `json:"status,optional"`
	Priority        int64   `json:"priority,optional"`
	PlanStartDate   int64   `json:"plan_start_date,optional"`
	PlanEndDate     int64   `json:"plan_end_date,optional"`
	ActualStartDate int64   `json:"actual_start_date,optional"`
	ActualEndDate   int64   `json:"actual_end_date,optional"`
	Workshop        string  `json:"workshop,optional"`
	Remark          string  `json:"remark,optional"`
}

type UpdateWorkOrderResp struct {
}

type WorkOrderInfo struct {
	Id              string  `json:"id"`
	OrderNo         string  `json:"order_no"`
	ProductId       string  `json:"product_id"`
	ProductNo       string  `json:"product_no"`
	ProductName     string  `json:"product_name"`
	BomId           string  `json:"bom_id,optional"`
	BomVersion      string  `json:"bom_version,optional"`
	Quantity        float64 `json:"quantity"`
	CompletedQty    float64 `json:"completed_qty"`
	QualifiedQty    float64 `json:"qualified_qty"`
	DefectiveQty    float64 `json:"defective_qty"`
	WarehouseId     string  `json:"warehouse_id,optional"`
	WarehouseNo     string  `json:"warehouse_no,optional"`
	WarehouseName   string  `json:"warehouse_name,optional"`
	Status          int64   `json:"status"`   // 1-未开工 2-已领料 3-生产中 4-已完工 5-已入库
	Priority        int64   `json:"priority"` // 1-紧急 2-正常 3-低
	PlanStartDate   int64   `json:"plan_start_date,optional"`
	PlanEndDate     int64   `json:"plan_end_date,optional"`
	ActualStartDate int64   `json:"actual_start_date,optional"`
	ActualEndDate   int64   `json:"actual_end_date,optional"`
	Workshop        string  `json:"workshop,optional"`
	Remark          string  `json:"remark,optional"`
	CreatedAt       int64   `json:"created_at"`
	CreatedBy       string  `json:"created_by,optional"`
	UpdatedAt       int64   `json:"updated_at,optional"`
	UpdatedBy       string  `json:"updated_by,optional"`
}

type WorkOrderListReq struct {
	Page      int64  `form:"page,default=1"`
	PageSize  int64  `form:"page_size,default=10"`
	ProductId string `form:"product_id,optional"`
	Status    int64  `form:"status,optional"`
	Priority  int64  `form:"priority,optional"`
	StartDate int64  `form:"start_date,optional"`
	EndDate   int64  `form:"end_date,optional"`
}

type WorkOrderListResp struct {
	Total int64           `json:"total"`
	List  []WorkOrderInfo `json:"list"`
}
