// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: xAuth.proto

package role

import (
	"context"

	"erp/app/auth/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRolePermissionReq           = pb.AddRolePermissionReq
	AddRolePermissionResp          = pb.AddRolePermissionResp
	AddRoleReq                     = pb.AddRoleReq
	AddRoleResp                    = pb.AddRoleResp
	AddUserRoleReq                 = pb.AddUserRoleReq
	AddUserRoleResp                = pb.AddUserRoleResp
	DelRolePermissionReq           = pb.DelRolePermissionReq
	DelRolePermissionResp          = pb.DelRolePermissionResp
	DelRoleReq                     = pb.DelRoleReq
	DelRoleResp                    = pb.DelRoleResp
	DelUserRoleByUserIdReq         = pb.DelUserRoleByUserIdReq
	DelUserRoleByUserIdResp        = pb.DelUserRoleByUserIdResp
	DelUserRoleReq                 = pb.DelUserRoleReq
	DelUserRoleResp                = pb.DelUserRoleResp
	GetAllPermissionsReq           = pb.GetAllPermissionsReq
	GetAllPermissionsResp          = pb.GetAllPermissionsResp
	GetRoleByIdReq                 = pb.GetRoleByIdReq
	GetRoleByIdResp                = pb.GetRoleByIdResp
	GetRolePermissionByRoleIdReq   = pb.GetRolePermissionByRoleIdReq
	GetRolePermissionByRoleIdResp  = pb.GetRolePermissionByRoleIdResp
	GetUserRoleByUserIdReq         = pb.GetUserRoleByUserIdReq
	GetUserRoleByUserIdResp        = pb.GetUserRoleByUserIdResp
	Permission                     = pb.Permission
	PermissionItem                 = pb.PermissionItem
	PermissionWithRolePermissionId = pb.PermissionWithRolePermissionId
	Role                           = pb.Role
	RoleAndPermissionDetails       = pb.RoleAndPermissionDetails
	RoleAndPermissions             = pb.RoleAndPermissions
	RolePermission                 = pb.RolePermission
	SearchRolePermissionReq        = pb.SearchRolePermissionReq
	SearchRolePermissionResp       = pb.SearchRolePermissionResp
	SearchRoleReq                  = pb.SearchRoleReq
	SearchRoleResp                 = pb.SearchRoleResp
	SearchUserRoleReq              = pb.SearchUserRoleReq
	SearchUserRoleResp             = pb.SearchUserRoleResp
	UpdateRolePermissionReq        = pb.UpdateRolePermissionReq
	UpdateRolePermissionResp       = pb.UpdateRolePermissionResp
	UpdateRoleReq                  = pb.UpdateRoleReq
	UpdateRoleResp                 = pb.UpdateRoleResp
	UpdateUserRoleReq              = pb.UpdateUserRoleReq
	UpdateUserRoleResp             = pb.UpdateUserRoleResp
	UserRole                       = pb.UserRole

	RoleZrpcClient interface {
		// -----------------------role-----------------------
		AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleResp, error)
		UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error)
		DelRole(ctx context.Context, in *DelRoleReq, opts ...grpc.CallOption) (*DelRoleResp, error)
		GetRoleById(ctx context.Context, in *GetRoleByIdReq, opts ...grpc.CallOption) (*GetRoleByIdResp, error)
		SearchRole(ctx context.Context, in *SearchRoleReq, opts ...grpc.CallOption) (*SearchRoleResp, error)
	}

	defaultRoleZrpcClient struct {
		cli zrpc.Client
	}
)

func NewRoleZrpcClient(cli zrpc.Client) RoleZrpcClient {
	return &defaultRoleZrpcClient{
		cli: cli,
	}
}

// -----------------------role-----------------------
func (m *defaultRoleZrpcClient) AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.AddRole(ctx, in, opts...)
}

func (m *defaultRoleZrpcClient) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultRoleZrpcClient) DelRole(ctx context.Context, in *DelRoleReq, opts ...grpc.CallOption) (*DelRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.DelRole(ctx, in, opts...)
}

func (m *defaultRoleZrpcClient) GetRoleById(ctx context.Context, in *GetRoleByIdReq, opts ...grpc.CallOption) (*GetRoleByIdResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.GetRoleById(ctx, in, opts...)
}

func (m *defaultRoleZrpcClient) SearchRole(ctx context.Context, in *SearchRoleReq, opts ...grpc.CallOption) (*SearchRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.SearchRole(ctx, in, opts...)
}
