// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: product.proto

package server

import (
	"context"

	"erp/app/product/rpc/internal/logic/productbatch"
	"erp/app/product/rpc/internal/svc"
	"erp/app/product/rpc/pb"
)

type ProductBatchServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedProductBatchServer
}

func NewProductBatchServer(svcCtx *svc.ServiceContext) *ProductBatchServer {
	return &ProductBatchServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductBatchServer) AddProductBatch(ctx context.Context, in *pb.AddProductBatchReq) (*pb.AddProductBatchResp, error) {
	l := productbatchlogic.NewAddProductBatchLogic(ctx, s.svcCtx)
	return l.AddProductBatch(in)
}

func (s *ProductBatchServer) GetProductBatchById(ctx context.Context, in *pb.GetProductBatchByIdReq) (*pb.GetProductBatchByIdResp, error) {
	l := productbatchlogic.NewGetProductBatchByIdLogic(ctx, s.svcCtx)
	return l.GetProductBatchById(in)
}

func (s *ProductBatchServer) SearchProductBatch(ctx context.Context, in *pb.SearchProductBatchReq) (*pb.SearchProductBatchResp, error) {
	l := productbatchlogic.NewSearchProductBatchLogic(ctx, s.svcCtx)
	return l.SearchProductBatch(in)
}
